Use Iterable in insert() method
pixeltable/pixeltable pull request #103
Opened 2024-03-24 23:12 UTC by aaron-siegel

Modifies InsertableTable.insert() to accept an Iterable rather than a List. As currently implemented it's a functional no-op (zero performance impact in either direction); the change is purely for API hygiene.

Also changes the tests to use generators and kwargs in insert() statements whenever appropriate.

2024-03-29 15:53 UTC, mkornacker requested changes
You should also update the overview tutorial and cheat sheet.

> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/103#-:-Nu9uSVJECZ8FjtEZg7a:b-y65i24)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/catalog/insertable_table.py` line 64 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/103#-Nu9u7QA9elnkzNOHg3U:-Nu9u7QA9elnkzNOHg3V:bd391l0) ([raw file](https://github.com/pixeltable/pixeltable/blob/2937f4c995f9d47925f0d99546b257a1e1cadf10/pixeltable/catalog/insertable_table.py#L64)):*
> ```Python
> 
>     @overload
>     def insert(self, print_stats: bool = False, fail_on_exception: bool = True, **kwargs: Any): ...
> ```

I'm wondering if we should call this insert_row()
___
*[`pixeltable/catalog/insertable_table.py` line 108 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/103#-Nu9tbuvExhq8Gesy2us:-Nu9tbuvExhq8Gesy2ut:broe21y) ([raw file](https://github.com/pixeltable/pixeltable/blob/2937f4c995f9d47925f0d99546b257a1e1cadf10/pixeltable/catalog/insertable_table.py#L108)):*
> ```Python
>             # There's a positional argument; this means `rows` is expressed as a
>             # list of dicts (multi-insert)
>             rows = list(args[0])
> ```

How does this work? (And why wasn't it needed before?)


<!-- Sent from Reviewable.io -->

2024-03-29 16:40 UTC, aaron-siegel reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/103)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/catalog/insertable_table.py` line 64 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/103#-Nu9u7QA9elnkzNOHg3U:-NuA3w_RDZhQGagJyDpR:b-j034u0) ([raw file](https://github.com/pixeltable/pixeltable/blob/2937f4c995f9d47925f0d99546b257a1e1cadf10/pixeltable/catalog/insertable_table.py#L64)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

I'm wondering if we should call this insert_row()
</blockquote></details>

Isn't this out of scope for this review? This has been in there for awhile. I guess the change in this review is to update the tests to use the kwargs pattern so it's substantively related.

I don't love `insert_row` (what's the objection to `insert`?) but we can discuss.
___
*[`pixeltable/catalog/insertable_table.py` line 108 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/103#-Nu9tbuvExhq8Gesy2us:-NuA3_LdC3kgcp_HNPz3:b-2jwy51) ([raw file](https://github.com/pixeltable/pixeltable/blob/2937f4c995f9d47925f0d99546b257a1e1cadf10/pixeltable/catalog/insertable_table.py#L108)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

How does this work? (And why wasn't it needed before?)
</blockquote></details>

It just turns the `Iterable` into a `list` (and it's a no-op if it's already a `list`).

Like I said, this change is functionally a complete no-op, it's entirely an API hygiene thing.


<!-- Sent from Reviewable.io -->

2024-03-30 00:15 UTC, aaron-siegel reviewed
I updated the cheat sheet. I didn't see a super convenient place to work it into the "pixeltable basics" tutorial. Maybe we can roll this into a general rethinking of the tutorial/doc structure?

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/103#-:-NuBhQNgAsy6uFj_Ac4c:buuigrj)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @mkornacker)



<!-- Sent from Reviewable.io -->

2024-03-30 00:18 UTC, mkornacker approved these changes

2024-03-30 01:16 UTC, merged