Inference API updates
pixeltable/pixeltable pull request #123
Opened 2024-04-09 02:54 UTC by aaron-siegel

Lots of updates to the OpenAI, Together, and Fireworks APIs, including:
- Mostly complete implementations of OpenAI and Together (except model training), including image and audio endpoints
- A common pattern for registering clients with the environment and surfacing API keys
- Retries in OpenAI to account for rate limiting (using the `tenacity` library - not a great solution, since it will synchronously block the pixeltable executor; eventually pixeltable should orchestrate its own retries)
- Lots of new and expanded unit tests

2024-04-12 04:20 UTC, mkornacker commented on pixeltable/functions/openai.py
> +def _retry(fn: Callable) -> Callable:
What's the reason for doing this here? Did you run into some throttling problems?

2024-04-12 04:20 UTC, mkornacker commented on pixeltable/functions/openai.py
> +) -> PIL.Image.Image:
Do we know what the resolution is? Would be nice to return that as part of the type.

2024-04-12 04:20 UTC, mkornacker commented on pixeltable/functions/together.py
> +    result = together_client().images.generate(
What is the type of result? It would be good to decompose this into the endpoint call and the post-processing, in the form of an expr udf.

2024-04-12 04:20 UTC, mkornacker commented on pixeltable/tests/functions/test_fireworks.py
> +        t.insert(input="How's everything going today?")
check status for exceptions

2024-04-12 04:20 UTC, mkornacker commented on pixeltable/tests/functions/test_fireworks.py
> +    def skip_test_if_no_fireworks_client() -> None:
What is this for?

2024-04-12 04:20 UTC, mkornacker commented on pixeltable/type_system.py
> +                    result = copy(underlying)
Why the copy?

2024-04-12 04:20 UTC, mkornacker commented on pixeltable/type_system.py
> +            base = typing.get_origin(t)  # Discard type parameters
What is this for?

2024-04-12 04:20 UTC, mkornacker commented on pyproject.toml
> +pillow = ">=10.1"
Is there some specific reason for 10.1, as opposed to 10.0?

2024-04-12 04:42 UTC, aaron-siegel reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/123)* status: 0 of 16 files reviewed, 8 unresolved discussions (waiting on @mkornacker)

___
*[`pyproject.toml` line 22 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/123#gh-1561994700:-NvFY8327E5B_XkJXPLq:byg9l32) ([raw file](https://github.com/pixeltable/pixeltable/blob/8f893985faa43124e9eeb8426eb069bc0bc8c4a4/pyproject.toml#L22)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Is there some specific reason for 10.1, as opposed to 10.0?
</blockquote></details>

No specific reason. I can downgrade this. It's an interesting problem, though. The wider our version windows, the more flexible pxt is wrt other libraries; but it also means our tests are less exhaustive (more likely there will be some breaking combination of library versions we haven't tested).
___
*[`pixeltable/type_system.py` line 250 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/123#gh-1561994325:-NvFZ4NrEZqM710jyDIy:b-5qrh26) ([raw file](https://github.com/pixeltable/pixeltable/blob/8f893985faa43124e9eeb8426eb069bc0bc8c4a4/pixeltable/type_system.py#L250)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Why the copy?
</blockquote></details>

We have to set `result.nullable = True` for the `Optional` type. If we don't make a copy, it will set `result.nullable = True` on the dictionary instance, which will cause the incorrect type to be returned for anything non-nullable in the future.

I added a code comment to clarify this.
___
*[`pixeltable/type_system.py` line 256 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/123#gh-1561994405:-NvFZPAZ99VX-AT-t2NP:b-64uh97) ([raw file](https://github.com/pixeltable/pixeltable/blob/8f893985faa43124e9eeb8426eb069bc0bc8c4a4/pixeltable/type_system.py#L256)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

What is this for?
</blockquote></details>

To ensure that parameterized types such as `list[int]` get mapped correctly to pixeltable types.

Without this, `list` would get mapped to a `JsonType()` (for example), but not `list[int]`. This ensures that any `list[T]` gets properly mapped. I added a code comment to clarify this.
___
*[`pixeltable/functions/openai.py` line 26 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/123#gh-1561986726:-NvFZi-S4xXWT4fFTXHe:b-qvgplk) ([raw file](https://github.com/pixeltable/pixeltable/blob/8f893985faa43124e9eeb8426eb069bc0bc8c4a4/pixeltable/functions/openai.py#L26)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

What's the reason for doing this here? Did you run into some throttling problems?
</blockquote></details>

Yes, without this, rate limited accounts will run into problems. OpenAI recommends rate limiting as best general practice. See:
https://platform.openai.com/docs/guides/rate-limits?context=tier-free
___
*[`pixeltable/functions/openai.py` line 216 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/123#gh-1561988230:-NvF_-Qy19wRf-v9m84l:bo0szs7) ([raw file](https://github.com/pixeltable/pixeltable/blob/8f893985faa43124e9eeb8426eb069bc0bc8c4a4/pixeltable/functions/openai.py#L216)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Do we know what the resolution is? Would be nice to return that as part of the type.
</blockquote></details>

Nope. It depends on the parameters (and model choice), unfortunately.
___
*[`pixeltable/functions/together.py` line 108 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/123#gh-1561989514:-NvF_9bT-0QOxO3KJxag:b-xedakg) ([raw file](https://github.com/pixeltable/pixeltable/blob/8f893985faa43124e9eeb8426eb069bc0bc8c4a4/pixeltable/functions/together.py#L108)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

What is the type of result? It would be good to decompose this into the endpoint call and the post-processing, in the form of an expr udf.
</blockquote></details>

Json.

Maybe the decomposition could be a TODO? There are similar considerations with the OpenAI api.
___
*[`pixeltable/tests/functions/test_fireworks.py` line 29 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/123#gh-1561990093:-NvF_i3fE2qO2aXYgDxK:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/8f893985faa43124e9eeb8426eb069bc0bc8c4a4/pixeltable/tests/functions/test_fireworks.py#L29)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

check status for exceptions
</blockquote></details>

Done.
___
*[`pixeltable/tests/functions/test_fireworks.py` line 35 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/123#gh-1561990508:-NvF_qOM6TiWIbQrW8FG:bgd5rva) ([raw file](https://github.com/pixeltable/pixeltable/blob/8f893985faa43124e9eeb8426eb069bc0bc8c4a4/pixeltable/tests/functions/test_fireworks.py#L35)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

What is this for?
</blockquote></details>

The main reason: When a pull request runs in CI, it won't have access to the API keys (for unavoidable security reasons). This ensures that the test will skip rather than fail if no API key is present. (CI will run again post-merge, this time with access to the API keys, ensuring that the test eventually runs in CI.)


<!-- Sent from Reviewable.io -->

2024-04-13 23:03 UTC, mkornacker requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/123)* status: 0 of 16 files reviewed, 11 unresolved discussions (waiting on @aaron-siegel)

___
*[`pyproject.toml` line 22 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/123#gh-1561994700:-NvOa8Xf5LZtowDVCqs7:bjrpp4k) ([raw file](https://github.com/pixeltable/pixeltable/blob/8f893985faa43124e9eeb8426eb069bc0bc8c4a4/pyproject.toml#L22)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

No specific reason. I can downgrade this. It's an interesting problem, though. The wider our version windows, the more flexible pxt is wrt other libraries; but it also means our tests are less exhaustive (more likely there will be some breaking combination of library versions we haven't tested).
</blockquote></details>

Let's try to be more inclusive here
___
*[`pixeltable/type_system.py` line 250 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/123#gh-1561994325:-NvOaW6s-HavLUsgMlUW:b-23hm8q) ([raw file](https://github.com/pixeltable/pixeltable/blob/8f893985faa43124e9eeb8426eb069bc0bc8c4a4/pixeltable/type_system.py#L250)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

We have to set `result.nullable = True` for the `Optional` type. If we don't make a copy, it will set `result.nullable = True` on the dictionary instance, which will cause the incorrect type to be returned for anything non-nullable in the future.

I added a code comment to clarify this.
</blockquote></details>

I'm only now picking up on this. Returning shared type instance is generally unsafe.
___
*[`pixeltable/type_system.py` line 255 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/123#-NvOaynA499lVATChRJp:-NvOaynA499lVATChRJq:b-5aww7q) ([raw file](https://github.com/pixeltable/pixeltable/blob/b2ec31dec3589477bd43111d6f5a94cf2d696303/pixeltable/type_system.py#L255)):*
> ```Python
>                     return result
>         elif t in _python_type_to_column_type:
>             return _python_type_to_column_type[t]
> ```

This should return the copy.
___
*[`pixeltable/functions/openai.py` line 26 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/123#gh-1561986726:-NvObwQuA7QssFPTuFTp:bazv4km) ([raw file](https://github.com/pixeltable/pixeltable/blob/8f893985faa43124e9eeb8426eb069bc0bc8c4a4/pixeltable/functions/openai.py#L26)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Yes, without this, rate limited accounts will run into problems. OpenAI recommends rate limiting as best general practice. See:
https://platform.openai.com/docs/guides/rate-limits?context=tier-free
</blockquote></details>

Good to know.

My guess is that the correct place to do this is at the ExecNode level (ie, where you have a clear picture of all the endpoints that are being used in a single query).
___
*[`pixeltable/functions/openai.py` line 216 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/123#gh-1561988230:-NvOcTbG-z09uMG8T6Km:b-ii12e4) ([raw file](https://github.com/pixeltable/pixeltable/blob/8f893985faa43124e9eeb8426eb069bc0bc8c4a4/pixeltable/functions/openai.py#L216)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Nope. It depends on the parameters (and model choice), unfortunately.
</blockquote></details>

But this information is available at runtime, no?
___
*[`pixeltable/functions/together.py` line 108 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/123#gh-1561989514:-NvOcjBT056JSMfGyurJ:b-3uo7nu) ([raw file](https://github.com/pixeltable/pixeltable/blob/8f893985faa43124e9eeb8426eb069bc0bc8c4a4/pixeltable/functions/together.py#L108)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Json.

Maybe the decomposition could be a TODO? There are similar considerations with the OpenAI api.
</blockquote></details>

Leave a todo then (here and in the other places where it applies).
___
*[`pixeltable/tests/functions/test_fireworks.py` line 35 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/123#gh-1561990508:-NvOcwWS8e34zYw0ncd_:b-1qjfzg) ([raw file](https://github.com/pixeltable/pixeltable/blob/8f893985faa43124e9eeb8426eb069bc0bc8c4a4/pixeltable/tests/functions/test_fireworks.py#L35)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

The main reason: When a pull request runs in CI, it won't have access to the API keys (for unavoidable security reasons). This ensures that the test will skip rather than fail if no API key is present. (CI will run again post-merge, this time with access to the API keys, ensuring that the test eventually runs in CI.)
</blockquote></details>

Best to leave that comment in the code
___
*[`pixeltable/tests/functions/test_openai.py` line 27 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/123#-NvOdsxN1kQMhJlCYyv4:-NvOdsxN1kQMhJlCYyv5:b-4ed23b) ([raw file](https://github.com/pixeltable/pixeltable/blob/b2ec31dec3589477bd43111d6f5a94cf2d696303/pixeltable/tests/functions/test_openai.py#L27)):*
> ```Python
>             t.speech, model='whisper-1', prompt='Translate the recording from Spanish into English.', temperature=0.7
>         ))
>         t.insert(input='I am a banana.')
> ```

call insert() with a list and check status (that way, you test a multi-row transaction)

re checking status: add that to every insert() call
___
*[`pixeltable/tests/functions/test_openai.py` line 69 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/123#-NvOeeeh8zpTz6EvQtJ_:-NvOeeeh8zpTz6EvQtJa:b3m5qbj) ([raw file](https://github.com/pixeltable/pixeltable/blob/b2ec31dec3589477bd43111d6f5a94cf2d696303/pixeltable/tests/functions/test_openai.py#L69)):*
> ```Python
>         assert len(result['chat_output_4'][0]['choices'][0]['message']['content']) > 0
> 
>         # TODO This should probably not be throwing an exception, but rather logging the error in
> ```

This cannot be a todo, it breaks the insert semantics. Also, ExprEvalError is not meant to be user-facing.

Why is there an exception here?


<!-- Sent from Reviewable.io -->

2024-04-16 19:01 UTC, mkornacker reviewed
ColumnType.from_python_type() cannot return shared data. The dict you're using there should not be used directly outside of from_python_type(). It should probably be a class member (and should really be local to from_python_type()).

2024-04-16 19:01 UTC, mkornacker commented on pixeltable/type_system.py
> +                    result = copy(underlying)
Why is this still necessary? from_python_type() should never return a copy().

2024-04-16 22:29 UTC, mkornacker commented on pixeltable/type_system.py
> +                    result = copy(underlying)
I meant to say: from_python_type() should never return a shared ColumnType instance

2024-04-16 22:49 UTC, mkornacker approved these changes

2024-04-17 00:00 UTC, merged