Bugfix for `create_view`
pixeltable/pixeltable pull request #138
Opened 2024-04-23 21:23 UTC by aaron-siegel

Fixes a bug where `create_view` throws an exception if the predicate contains a reference to a `date` or `datetime` literal.

2024-04-23 21:23 UTC, aaron-siegel commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pixeltable/pixeltable/138)
<!-- Reviewable:end -->

2024-04-23 21:42 UTC, mkornacker requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/138)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/exprs/literal.py` line 65 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/138#-NwBtdlEDCHwDHDL5ZSj:-NwBtdlEDCHwDHDL5ZSk:b-bwkiqx) ([raw file](https://github.com/pixeltable/pixeltable/blob/5623d2edd898c10353a1b21eaf830072b4a4126f/pixeltable/exprs/literal.py#L65)):*
> ```Python
>             val_t = d['val_t']
>             if val_t == ts.ColumnType.Type.TIMESTAMP.name:
>                 return cls(datetime.datetime.fromisoformat(d['val']), ts.TimestampType())
> ```

You don't need to pass the TimestampType(), if you just pass in a datetime it'll figure out the correct type.
___
*[`pixeltable/exprs/literal.py` line 67 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/138#-NwBtm7CAqv6BnEThq1q:-NwBtm7CAqv6BnEThq1r:b-og3iic) ([raw file](https://github.com/pixeltable/pixeltable/blob/5623d2edd898c10353a1b21eaf830072b4a4126f/pixeltable/exprs/literal.py#L67)):*
> ```Python
>                 return cls(datetime.datetime.fromisoformat(d['val']), ts.TimestampType())
>             else:
>                 excs.Error(f'Invalid literal metadata: val_t = {val_t}')
> ```

This is not a user-facing error (Error is reserved for situations that bubble up to the user). It should really be an assertion.


<!-- Sent from Reviewable.io -->

2024-04-23 23:44 UTC, aaron-siegel reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/138)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/exprs/literal.py` line 65 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/138#-NwBtdlEDCHwDHDL5ZSj:-NwCLCpU7SzYm8xyTz_7:b-886gsx) ([raw file](https://github.com/pixeltable/pixeltable/blob/5623d2edd898c10353a1b21eaf830072b4a4126f/pixeltable/exprs/literal.py#L65)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

You don't need to pass the TimestampType(), if you just pass in a datetime it'll figure out the correct type.
</blockquote></details>

Fixed
___
*[`pixeltable/exprs/literal.py` line 67 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/138#-NwBtm7CAqv6BnEThq1q:-NwCLD_3BUkREYIFOW2B:b-886gsx) ([raw file](https://github.com/pixeltable/pixeltable/blob/5623d2edd898c10353a1b21eaf830072b4a4126f/pixeltable/exprs/literal.py#L67)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

This is not a user-facing error (Error is reserved for situations that bubble up to the user). It should really be an assertion.
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2024-04-24 00:24 UTC, mkornacker approved these changes

2024-04-24 00:38 UTC, merged