Use a decorator pattern for dynamic return types
pixeltable/pixeltable pull request #154
Opened 2024-05-03 17:54 UTC by aaron-siegel

Introduces a new instance decorator

@my_udf.dynamic_return_type

for specifying dynamic (arg-dependent) return types for UDFs.

2024-05-03 17:54 UTC, aaron-siegel commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pixeltable/pixeltable/154)
<!-- Reviewable:end -->

2024-05-03 23:23 UTC, mkornacker commented on pixeltable/func/function.py
> +    def dynamic_return_type(self, call_return_type: Callable[..., ts.ColumnType]) -> Callable[..., ts.ColumnType]:
I actually think call_return_type is more specific (because it takes the actual call arguments into account)

2024-05-03 23:23 UTC, mkornacker commented on pixeltable/functions/pil/image.py
> +
Should it be one or two blank lines?

2024-05-03 23:23 UTC, mkornacker commented on pixeltable/tests/test_function.py
> +def udf6(name: str) -> str:
Why move it?

2024-05-04 00:00 UTC, aaron-siegel reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/154)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/func/function.py` line 69 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/154#gh-1589802229:-Nx-tEOi1PyVBeSCniol:b542mx5) ([raw file](https://github.com/pixeltable/pixeltable/blob/c70895c9b5b4f675360cda05f0bced80b85059bf/pixeltable/func/function.py#L69)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

I actually think call_return_type is more specific (because it takes the actual call arguments into account)
</blockquote></details>

Hmmm ok. I don't feel super strongly about it, but I felt like `call_return_type` is a little awkward (it's easily mis-parsed, as in, "you use this function if you want to call the return type"). What about something like `arg_dependent_return_type` that's a little more verbose, but unambiguous?
___
*[`pixeltable/functions/pil/image.py` line 30 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/154#gh-1589802851:-Nx-ruEW4YaR4eEnm48d:b4s53l2) ([raw file](https://github.com/pixeltable/pixeltable/blob/c70895c9b5b4f675360cda05f0bced80b85059bf/pixeltable/functions/pil/image.py#L30)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Should it be one or two blank lines?
</blockquote></details>

PEP8 says two.

https://peps.python.org/pep-0008/#blank-lines
___
*[`pixeltable/tests/test_function.py` line 341 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/154#gh-1589803398:-Nx-s4Qe7HP2mSA_hnc7:b6f97eh) ([raw file](https://github.com/pixeltable/pixeltable/blob/c70895c9b5b4f675360cda05f0bced80b85059bf/pixeltable/tests/test_function.py#L341)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Why move it?
</blockquote></details>

Because now it's a valid udf definition, so if it's declared inside a function, the decorator will raise a "nested functions are not supported" exception.


<!-- Sent from Reviewable.io -->

2024-05-04 01:28 UTC, mkornacker requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/154)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/func/function.py` line 69 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/154#gh-1589802229:-Nx0CXTDB-1PFcim6wu3:be36kao) ([raw file](https://github.com/pixeltable/pixeltable/blob/c70895c9b5b4f675360cda05f0bced80b85059bf/pixeltable/func/function.py#L69)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Hmmm ok. I don't feel super strongly about it, but I felt like `call_return_type` is a little awkward (it's easily mis-parsed, as in, "you use this function if you want to call the return type"). What about something like `arg_dependent_return_type` that's a little more verbose, but unambiguous?
</blockquote></details>

How about call_args_return_type?

arg_dependent_return_type somehow sounds very chatty...


<!-- Sent from Reviewable.io -->

2024-05-08 16:00 UTC, aaron-siegel reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/154)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/func/function.py` line 69 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/154#gh-1589802229:-NxNvEPXB25dB8RdqPKy:buwa1wa) ([raw file](https://github.com/pixeltable/pixeltable/blob/c70895c9b5b4f675360cda05f0bced80b85059bf/pixeltable/func/function.py#L69)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

How about call_args_return_type?

arg_dependent_return_type somehow sounds very chatty...
</blockquote></details>

Here are my suggestions:
`conditional_return_type` for the decorator (which specifies the custom function that maps args -> return type)
`call_return_type` for the `Function` method that evaluates a list of args and produces a return type (which consults `conditional_return_type` if it exists, and otherwise falls back on ordinary return type)


<!-- Sent from Reviewable.io -->

2024-05-10 03:17 UTC, mkornacker approved these changes

2024-05-10 03:41 UTC, merged