Remove NOS-related code from Pixeltable
pixeltable/pixeltable pull request #165
Opened 2024-05-14 01:28 UTC by aaron-siegel

There are several good reasons to do this now, beyond code hygiene.

- It simplifies the `BatchedFunction` implementation, which will make batched functions easier to iterate on (which we need to do, cf. PXT-154)
- There were a few tests that relied on NOS, but provided useful coverage independent of NOS. As a byproduct of stripping out NOS, I was able to rework these to use substitutes in place of NOS functions.

2024-05-14 01:28 UTC, aaron-siegel commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pixeltable/pixeltable/165)
<!-- Reviewable:end -->

2024-05-17 23:54 UTC, mkornacker commented on tests/test_exprs.py
> -        from pixeltable.functions.nos.image_embedding import openai_clip
how about just deleting that and leaving the rest in place?

2024-05-19 17:40 UTC, aaron-siegel reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/165)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @mkornacker and @orm011)

___
*[`tests/test_exprs.py` line 0 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/165#gh-1605618725:-NyGvl48AlSvvbl-l4bD:b9n333j) ([raw file](https://github.com/pixeltable/pixeltable/blob/2ab78f4278acf8bdc511e9f4f94272b172bd68b8/tests/test_exprs.py#L0)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map [this GitHub inline comment thread](https://github.com/pixeltable/pixeltable/pull/165#discussion_r1605618725) to the right spot — sorry!)*

how about just deleting that and leaving the rest in place?
</blockquote></details>

I'd thought about it, but it seemed pointless/redundant since there is a new `test_pil.py` that is far more exhaustive.

Is there something specific in this method that you see that's missing from `test_pil.py`? If so, I think the best course is just to incorporate it into the new `test_pil.py`.


<!-- Sent from Reviewable.io -->

2024-05-19 18:29 UTC, mkornacker requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/165)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @aaron-siegel and @orm011)

___
*[`tests/test_exprs.py` line 568 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/165#-NyH5nfD5Mpuzdk_y-jj:-NyH5nfD5Mpuzdk_y-jk:beeib1g) ([raw file](https://github.com/pixeltable/pixeltable/blob/16d5ca165322551a0b2e0e22a96b25a662d282d5/tests/test_exprs.py#L568)):*
> ```Python
>         print(result)
>         _ = result._repr_html_()
>         _ = t.img.entropy() > 1
> ```

Everything from here on is about expressions, in particular combining image functions with other exprs that can be evaluated by Postgres. Those cases logically belong here, not in test_pil. Can you delete everything that precedes this and just keep the rest here?


<!-- Sent from Reviewable.io -->

2024-05-20 08:53 UTC, aaron-siegel reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/165)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @mkornacker and @orm011)

___
*[`tests/test_exprs.py` line 568 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/165#-NyH5nfD5Mpuzdk_y-jj:-NyKByIECXXCNurpjwrj:b8rvjfg) ([raw file](https://github.com/pixeltable/pixeltable/blob/16d5ca165322551a0b2e0e22a96b25a662d282d5/tests/test_exprs.py#L568)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Everything from here on is about expressions, in particular combining image functions with other exprs that can be evaluated by Postgres. Those cases logically belong here, not in test_pil. Can you delete everything that precedes this and just keep the rest here?
</blockquote></details>

Ok, done. I resurrected the test and changed its name to `test_image_expressions`.


<!-- Sent from Reviewable.io -->

2024-05-20 16:32 UTC, mkornacker approved these changes

2024-05-20 17:37 UTC, merged