more concise array and string formatting
pixeltable/pixeltable pull request #177
Opened 2024-05-17 21:19 UTC by orm011

make array columns print only a few elements by using numpys array formatting functions
also: make string columns print an abridged string if the original string is too long

rendered rag notebook here:
https://github.com/orm011/pixeltable/blob/concise_format/docs/release/tutorials/rag-operations.ipynb

compare with:
https://github.com/pixeltable/pixeltable/blob/master/docs/release/tutorials/rag-operations.ipynb

2024-05-17 21:19 UTC, aaron-siegel commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pixeltable/pixeltable/177)
<!-- Reviewable:end -->

2024-05-17 22:54 UTC, aaron-siegel requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/177)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @orm011)

___
*[`pixeltable/dataframe.py` line 55 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/177#-Ny7d7B8677cainBy32t:-Ny7d7B8677cainBy32u:b-6lp8my) ([raw file](https://github.com/pixeltable/pixeltable/blob/ff9cc8733d05d9f78b5451b35f42eadd6cb20837/pixeltable/dataframe.py#L55)):*
> ```Python
>             ts.AudioType: self._format_audio,
>             ts.DocumentType: self._format_document,
>             ts.ArrayType: self._format_array,
> ```

We also need a `_format_dict` and `_format_list`, and to process them recursively. Arrays/lists inside of dicts are fairly common.
___
*[`pixeltable/dataframe.py` line 148 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/177#-Ny7kObB5mwYfl6nioU8:-Ny7kObB5mwYfl6nioU9:bsr7v4s) ([raw file](https://github.com/pixeltable/pixeltable/blob/ff9cc8733d05d9f78b5451b35f42eadd6cb20837/pixeltable/dataframe.py#L148)):*
> ```Python
>     def _format_array(self, arr: List[Any]) -> str:
>         arr = np.array(arr)
>         return np.array2string(arr, precision=3, threshold=8, separator=',', edgeitems=3)
> ```

I'd argue for increasing threshold and edgeitems a bit, maybe to 16/6? We could think about making this a configurable parameter in the pixeltable env (but obviously that's not urgent)
___
*[`pixeltable/dataframe.py` line 152 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/177#-Ny7kZpJ1-zazTaiVGIx:-Ny7kZpJ1-zazTaiVGIy:b-62hslw) ([raw file](https://github.com/pixeltable/pixeltable/blob/ff9cc8733d05d9f78b5451b35f42eadd6cb20837/pixeltable/dataframe.py#L152)):*
> ```Python
>     def _format_string(self, string: str) -> str:
>         if len(string) > 250:
>             return f'{string[:120]}...{string[-120:]}'
> ```

Suggestion: use `......` as the separator instead of `...`

The single ellipsis is sufficient for arrays but could get buried in the string.


<!-- Sent from Reviewable.io -->

2024-05-23 05:09 UTC, aaron-siegel requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/177)* status: 0 of 7 files reviewed, 22 unresolved discussions (waiting on @orm011)

___
*[`docs/release/tutorials/rag-operations.ipynb` line 1442 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/177#-NyYgXAJD7zoVOXelkPM:-NyYgXAJD7zoVOXelkPN:b-j4jj2n) ([raw file](https://github.com/pixeltable/pixeltable/blob/f013bb4859018173b38629f553cca9c5a23e00c7/docs/release/tutorials/rag-operations.ipynb#L1442)):*
> ```
>        "      <td><pre style=\"text-align:left; background-color:transparent; margin:0;\">{1: Marc Chagall}</pre></td>\n",
>        "      <td>1015</td>\n",
>        "      <td><pre style=\"text-align:left; background-color:transparent; margin:0;\">[ 6.518e-05, 3.302e-01,-3.144e-01, 1.680e-01,-1.229e-01, 3.993e-01,...,\n",
> ```

I don't love that scientific notation is being used for values like 0.330 (just picking an example). It's more compact to write it without scientific notation! Do we have control over this (i.e. only use scientific notation when it's actually more compact than a decimal of equal precision?)
___
*[`docs/release/tutorials/rag-operations.ipynb` line 1589 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/177#-NyYh-Sg84PBXRe7JSni:-NyYh-Sg84PBXRe7JSnj:b-ltna8y) ([raw file](https://github.com/pixeltable/pixeltable/blob/f013bb4859018173b38629f553cca9c5a23e00c7/docs/release/tutorials/rag-operations.ipynb#L1589)):*
> ```
>        "\n",
>        "                                        minilm_embed  \\\n",
>        "0  [-0.26239732, -0.11875591, -0.1327097, 0.04825...   \n",
> ```

Why are we still seeing high-precision numbers in the notebooks?
___
*[`pixeltable/utils/formatter.py` line 49 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/177#-NyYi4X-62VpHjMxW9vd:-NyYi4X-62VpHjMxW9ve:b-b1o1ez) ([raw file](https://github.com/pixeltable/pixeltable/blob/f013bb4859018173b38629f553cca9c5a23e00c7/pixeltable/utils/formatter.py#L49)):*
> ```Python
> 
> 
> from typing import Union
> ```

This should go at the top of the file
___
*[`pixeltable/utils/formatter.py` line 52 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/177#-NyYiaMVBrAvmdFpLpVu:-NyYiaMVBrAvmdFpLpVv:bytol7s) ([raw file](https://github.com/pixeltable/pixeltable/blob/f013bb4859018173b38629f553cca9c5a23e00c7/pixeltable/utils/formatter.py#L52)):*
> ```Python
> 
> 
> def contains_only_simple_elements(values: Union[list[Any], dict[Any]]) -> bool:
> ```

dict has two type parameters, right?
___
*[`pixeltable/utils/formatter.py` line 55 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/177#-NyYikGUBea0iKJJbK3v:-NyYikGUBea0iKJJbK3w:b-m3c80r) ([raw file](https://github.com/pixeltable/pixeltable/blob/f013bb4859018173b38629f553cca9c5a23e00c7/pixeltable/utils/formatter.py#L55)):*
> ```Python
>     """whether all values of this array or dict are themselves elementary (no nested lists or dicts)"""
>     if isinstance(values, dict):
>         values = values.values()
> ```

This is really awkward. It'd be a clearer separation of logic to take an `Iterable` as the parameter rather than `Union[list, dict]`, and then when using it on a dict, call `contains_only_simple_elements(my_dict.values())`.

Also, I'd argue it'd be clearer to negate the function and call it `contains_collection` or some such; that also has the benefit of avoiding introducing the bespoke term `simple` (not a huge deal, but it was an extra/avoidable cognitive step for me to figure out what that meant)
___
*[`pixeltable/utils/formatter.py` line 60 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/177#-NyYnGED5wbMiec3_kul:-NyYnGED5wbMiec3_kum:bmawf9y) ([raw file](https://github.com/pixeltable/pixeltable/blob/f013bb4859018173b38629f553cca9c5a23e00c7/pixeltable/utils/formatter.py#L60)):*
> ```Python
> 
> 
> class PixeltableFormatter:
> ```

We definitely need tests for this. There's a lot of new logic in here.
___
*[`pixeltable/utils/formatter.py` line 70 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/177#-NyYjoXz0dEoaYSfix6j:-NyYjoXz0dEoaYSfix6k:bi52cjv) ([raw file](https://github.com/pixeltable/pixeltable/blob/f013bb4859018173b38629f553cca9c5a23e00c7/pixeltable/utils/formatter.py#L70)):*
> ```Python
>         return np.array2string(np.array(val), precision=FLOAT_PRECISION)
> 
>     def _format_array(self, arr: list[Any]) -> str:
> ```

why's this taking a list as input?
___
*[`pixeltable/utils/formatter.py` line 71 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/177#-NyYk6e27Y7q3WJD3cKt:-NyYk6e27Y7q3WJD3cKu:b-cn6mvw) ([raw file](https://github.com/pixeltable/pixeltable/blob/f013bb4859018173b38629f553cca9c5a23e00c7/pixeltable/utils/formatter.py#L71)):*
> ```Python
> 
>     def _format_array(self, arr: list[Any]) -> str:
>         """for numerical arrays only. to format an array type, use format_json, which also includes styling"""
> ```

I'd like to get away from docstrings that are really just notes (vs. proper documentation).

It's not necessary to have docstrings for private methods, so the simplest thing to do would be convert this to a code comment. If we do want to include the docstrings, let's write them properly (clear description of what the function does, complete sentences, correct punctuation, etc.)
___
*[`pixeltable/utils/formatter.py` line 88 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/177#-NyYk03U6NqJu8N7F4nW:-NyYk03U6NqJu8N7F4nX:bmqet18) ([raw file](https://github.com/pixeltable/pixeltable/blob/f013bb4859018173b38629f553cca9c5a23e00c7/pixeltable/utils/formatter.py#L88)):*
> ```Python
>             If the string is too long, show only the first and last STRING_EDGEITEMS characters.
> 
>             TODO: render enclosing quotes also? but need to escape inner quotes
> ```

These TODOs should definitely be in comments, not the docstring
___
*[`pixeltable/utils/formatter.py` line 96 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/177#-NyYkv1p6iYgQOg7R2CN:-NyYkv1p6iYgQOg7R2CO:bjcd0a3) ([raw file](https://github.com/pixeltable/pixeltable/blob/f013bb4859018173b38629f553cca9c5a23e00c7/pixeltable/utils/formatter.py#L96)):*
> ```Python
> 
>     def _format_json_helper(self, obj: Any, level: int) -> str:
>         def get_prefix(level):
> ```

why's this a nested function? since it depends only on level, can't it just be a variable? (`prefix = ' ' * (level * INDENT)`)
___
*[`pixeltable/utils/formatter.py` line 103 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/177#-NyYlJzN0CwachW0bJq8:-NyYlJzN0CwachW0bJq9:b7tqh8s) ([raw file](https://github.com/pixeltable/pixeltable/blob/f013bb4859018173b38629f553cca9c5a23e00c7/pixeltable/utils/formatter.py#L103)):*
> ```Python
> 
>         if isinstance(obj, np.ndarray):  # sometimes we get a numpy array, which is technically not a list
>             return self._format_json_helper(obj.tolist(), level=level)
> ```

better to say `obj = obj.tolist()` than to do a recursive call
___
*[`pixeltable/utils/formatter.py` line 112 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/177#-NyYljViCLbaym-ceNvP:-NyYljViCLbaym-ceNvQ:btsoqub) ([raw file](https://github.com/pixeltable/pixeltable/blob/f013bb4859018173b38629f553cca9c5a23e00c7/pixeltable/utils/formatter.py#L112)):*
> ```Python
>             # 3. list with at least one nested list or dict
>             #   => insert newlines between elements to help read them.
>             arr = as_numeric_ndarray(obj)
> ```

Actually (cf. my previous comment), this seems weird. we're converting to a list, then back to an ndarray again? Can't this be reorganized so as to avoid that?
___
*[`pixeltable/utils/formatter.py` line 156 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/177#-NyYnRuJEQKoTfBDC3Ec:-NyYnRuJEQKoTfBDC3Ed:bvydwc5) ([raw file](https://github.com/pixeltable/pixeltable/blob/f013bb4859018173b38629f553cca9c5a23e00c7/pixeltable/utils/formatter.py#L156)):*
> ```Python
>             return f'{get_prefix(level)}{self.format_float(obj)}'
>          [...]

2024-05-23 05:15 UTC, aaron-siegel reviewed
High level comments.
1. The formatter definitely needs tests.
2. I'm surprised we're doing the JSON rendering by hand? Seems potentially fraught/full of edge cases. Have we looked to see if there are any libraries out there that pretty-print JSON?

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/177#-:-NyYqmsZAostAkLWlodR:bj3m3jr)* status: 0 of 7 files reviewed, 22 unresolved discussions (waiting on @orm011)



<!-- Sent from Reviewable.io -->

2024-05-23 14:37 UTC, orm011 reviewed
1. I will add some tests, I have some I used during development but as they are visual, they are in a notebook.

2. I tried the built in json pretty printer first, the main dealbreaker, is it does not understand that we want to treat nested lists that happen to be numeric arrays just like numpy does, and that we ant to keep consistency between types within the json, and those in other columns, which were things you expressed.  Now we have that.  I also know there are some web-based json displays but they would still have a similar issue with consistency.   


My high level retrospective on this, the time went into:
1.  dealing with json so that we can control consistency between json and other types when they appear outside, with multiple tests written for this (will add to test suite, currently in a notebook)  (1 day)
2.  figuring out how to ensure the pretty-printing we get from numpy and our own json printer, or any text-based json pretty printer for that matter, can still render ok when put in HTML (using <pre> tags was the solution in the end, which lets us control formatting with whitespace).  .5 days
3. string types escaping (which we now escape at a fine-grain).  .5 days. In retrospective, this was a much higher priority issue than I initially thought, given we were effectively allowing injection of randomly scraped code (eg from html docs) into the notebook of users.

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/177#-:-Ny_ohyNDxyiS4c3X2eI:bjk1j3z)* status: 0 of 9 files reviewed, 22 unresolved discussions (waiting on @aaron-siegel)

___
*[`docs/release/tutorials/rag-operations.ipynb` line 1442 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/177#-NyYgXAJD7zoVOXelkPM:-Ny_rH9PE8XhDz24BUO1:bhh990j) ([raw file](https://github.com/pixeltable/pixeltable/blob/f013bb4859018173b38629f553cca9c5a23e00c7/docs/release/tutorials/rag-operations.ipynb#L1442)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I don't love that scientific notation is being used for values like 0.330 (just picking an example). It's more compact to write it without scientific notation! Do we have control over this (i.e. only use scientific notation when it's actually more compact than a decimal of equal precision?)
</blockquote></details>

This is the standard numpy setting. I believe it has to do with keeping values aligned. 
___
*[`docs/release/tutorials/rag-operations.ipynb` line 1589 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/177#-NyYh-Sg84PBXRe7JSni:-Ny_sDXQ9XtRG-sqmfVf:b-c6i1ny) ([raw file](https://github.com/pixeltable/pixeltable/blob/f013bb4859018173b38629f553cca9c5a23e00c7/docs/release/tutorials/rag-operations.ipynb#L1589)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Why are we still seeing high-precision numbers in the notebooks?
</blockquote></details>

They're not in the rendered notebook:
https://github.com/orm011/pixeltable/blob/concise_format/docs/release/tutorials/rag-operations.ipynb
___
*[`pixeltable/dataframe.py` line 55 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/177#-Ny7d7B8677cainBy32t:-Ny8-iq37qQ6Z-yKFt8H:b-a5rzeo) ([raw file](https://github.com/pixeltable/pixeltable/blob/ff9cc8733d05d9f78b5451b35f42eadd6cb20837/pixeltable/dataframe.py#L55)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

We also need a `_format_dict` and `_format_list`, and to process them recursively. Arrays/lists inside of dicts are fairly common.
</blockquote></details>

Yeah, we need to look into json col, probably needs its own PR early next week?if this works 
___
*[`pixeltable/dataframe.py` line 148 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/177#-Ny7kObB5mwYfl6nioU8:-Ny801hr6M4m5kvPqM1C:b-czlzq9) ([raw file](https://github.com/pixeltable/pixeltable/blob/ff9cc8733d05d9f78b5451b35f42eadd6cb20837/pixeltable/dataframe.py#L148)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I'd argue for increasing threshold and edgeitems a bit, maybe to 16/6? We could think about making this a configurable parameter in the pixeltable env (but obviously that's not urgent)
</blockquote></details>

yeah, we need to expose some way of controlling these.
___
*[`pixeltable/dataframe.py` line 152 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/177#-Ny7kZpJ1-zazTaiVGIx:-Ny_sVfI3FZ3sVAMvoVY:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/ff9cc8733d05d9f78b5451b35f42eadd6cb20837/pixeltable/dataframe.py#L152)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Suggestion: use `......` as the separator instead of `...`

The single ellipsis is sufficient for arrays but could get buried in the string.
</blockquote></details>

Done.
___
*[`pixeltable/utils/formatter.py` line 49 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/177#-NyYi4X-62VpHjMxW9vd:-Ny_sWdY2sbp-LmFqsPB:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/f013bb4859018173b38629f553cca9c5a23e00c7/pixeltable/utils/formatter.py#L49)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This should go at the top of the file
</blockquote></details>

Done.
___
*[`pixeltable/utils/formatter.py` line 52 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/177#-NyYiaMVBrAvmdFpLpVu:-Ny_sXSW7Bkuz3mC7mKW:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/f013bb4859018173b38629f553cca9c5a23e00c7/pixeltable/utils/formatter.py#L52)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

dict has two type parameters, right?
</blockquote></details>

Done.
___
*[`pixeltable/utils/formatter.py` line 55 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/177#-NyYikGUBea0iKJJbK3v:-Ny_kDY13fEvCiMR7bjQ:b4mo326) ([raw file](https://github.com/pixeltable/pixeltable/blob/f013bb4859018173b38629f553cca9c5a23e00c7/pixeltable/utils/formatter.py#L55)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This is really awkward. It'd be a clearer separation of logic to take an `Iterable` as the parameter rather than `Union[list, dict]`, and then when using it on a dict, call `contains_only_simple_elements(my_dict.values())`.

Also, I'd argue it'd be clearer to negate the function and call it `contains_collection` or some such; that also has the benefit of avoiding introducing the bespoke term `simple` (not a huge deal, but it was an extra/avoidable cognitive step for me to figure out what that meant)
</blockquote></details>

I can switch it to just look at the values as you say.
This is all in the context of json, where there are arrays and dictionaries,  there are no arbitrary iterables, but to call it as you would like i guess iterable would be the option.
___
*[`pixeltable/utils/formatter.py` line 60 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/177#-NyYnGED5wbMiec3_kul:-Ny_sYaW811WGHA7YuAR:btapvre) ([raw file](https://github.com/pixeltable/pixeltable/blob/f013bb4859018173b38629f553cca9c5a23e00c7/pixeltable/utils/formatter.py#L60)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

We definitely need tests for this. There's a lot of new logic in here.
</blockquote></details>

will add. 
___
*[`pixeltable/utils/formatter.py` line 70 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/177#-NyYjoXz0dEoaYSfix6j:-Ny_kpmEDu04W7SAKeQH:bhzrg1w) ([raw file](https://github.com/pixeltable/pixeltable/blob/f013bb4859018173b38629f553cca9c5a23e00c7/pixeltable/utils/formatter.py#L70)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

why's this taking a list as input?
</blockquote></details>

because its input is supposed to be a json array.
___
*[`p [...]

2024-05-23 14:43 UTC, orm011 reviewed
current state of things

object detection tutorial (json, arrays)
before: https://github.com/orm011/pixeltable/blob/04f73ac/docs/release/tutorials/object-detection-in-videos.ipynb
after: https://github.com/orm011/pixeltable/blob/concise_format/docs/release/tutorials/object-detection-in-videos.ipynb

rag operation tutorial (strings, arrays)
before:https://github.com/orm011/pixeltable/blob/04f73ac/docs/release/tutorials/rag-operations.ipynb
after: https://github.com/orm011/pixeltable/blob/concise_format/docs/release/tutorials/rag-operations.ipynb

anm tutorial (strings)
before:https://github.com/orm011/pixeltable/blob/query/docs/tutorials/document-demo-anm.ipynb
after: https://github.com/orm011/pixeltable/blob/concise_format/docs/drafts/document-demo-anm.ipynb (up to cell 14, as there is no query in this branch)

This las demo tells me:
Its possible we need to escape string whitespace (render without newlines). But the strange markup is gone.

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/177#-:-Ny_siJfAWAGwa5VGrAP:b11idt4)* status: 0 of 9 files reviewed, 22 unresolved discussions (waiting on @aaron-siegel)



<!-- Sent from Reviewable.io -->

2024-07-02 06:59 UTC, closed without merging