'Tables and Data Operations' notebook
pixeltable/pixeltable pull request #230
Opened 2024-07-24 23:34 UTC by aaron-siegel

A 'Tables and Data Operations' notebook, intended to be Part 1 of the new Fundamentals tutorial. This is based off of the 'Basic Data Manipulations' notebook from @pierrebrunelle .

2024-07-24 23:34 UTC, aaron-siegel commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pixeltable/pixeltable/230)
<!-- Reviewable:end -->

2024-07-27 18:47 UTC, mkornacker commented on docs/release/fundamentals/tables-and-data-operations.ipynb
> +    "Tables in Pixeltable are grouped into __directories__, which are simply user-defined namespaces. The following command creates a new directory, `fundamentals`, which we'll use to store the table
"which are simply hierarchical user-defined ..."

Might make sense to give an example of hierarchical directories somewhere.

2024-07-27 18:47 UTC, mkornacker commented on docs/release/fundamentals/tables-and-data-operations.ipynb
> +    "Now let's create our first table. To create a table, we must give it a name and a __schema__ that describes the table structure. Note that prefacing the name with `fundamentals` causes it to be
Probably a good place to mention the data types that are available.

2024-07-27 18:47 UTC, mkornacker commented on docs/release/fundamentals/tables-and-data-operations.ipynb
> +    "Often you want to select only certain data or certain columns in a table. You can do this with the `where()` and `select()` methods."
"certain rows and/or certain columns"?

2024-07-27 18:47 UTC, mkornacker commented on docs/release/fundamentals/tables-and-data-operations.ipynb
> +    "The second major difference is that **Pixeltable is strongly typed**. Because Pixeltable is a database, every column has a data type: that's why we specified `StringType`, `IntType`, and `FloatT
Might want to show that in a notebook you don't need to call describe() explicitly.

2024-07-27 18:47 UTC, mkornacker commented on docs/release/fundamentals/tables-and-data-operations.ipynb
> +    "To insert data into a table, we use the `insert()` method, passing it a list of Python dicts."
Probably a good place to mention again that there's also update() and delete(), and you'll get to those later.

2024-07-27 18:47 UTC, mkornacker commented on docs/release/fundamentals/tables-and-data-operations.ipynb
> +    "The dataset is in CSV format, and we can easily load it into Pixeltable with the handy `import_csv()` function, which creates a new Pixeltable table from the contents of a CSV file."
I would leave out terms like "easily", which has a slight marketing ring to it (and doesn't add anything - the user can decide how easy it is).

2024-07-27 18:47 UTC, mkornacker commented on docs/release/fundamentals/tables-and-data-operations.ipynb
> +    "The `head()` and `tail()` methods provide an alternative way to do this. Pixeltable keeps track of the insertion order of all its data, and `head()` and `tail()` will always return the _earliest
head and tail are actually not alternatives to limit; maybe "provide a different way of doing this"?

2024-07-27 18:47 UTC, mkornacker commented on docs/release/fundamentals/tables-and-data-operations.ipynb
> +    "eq_t.describe()"
omit '.describe()'?

2024-07-27 18:47 UTC, mkornacker commented on docs/release/fundamentals/tables-and-data-operations.ipynb
> +    "# Add a comment to records with IDs 123 and 127\n",
Maybe use a computed expression here somewhere? Right now it looks like the update dict can only do literals.

Increment some integer column by 1?

2024-07-27 18:47 UTC, mkornacker commented on docs/release/fundamentals/tables-and-data-operations.ipynb
> +    "Every table in Pixeltable is versioned: some or all of its modification history is preserved. If you make a mistake, you can always call `revert()` to undo the previous change to a table. Let's
Probably best to say "you can always call revert() (well, mostly, unless there are snapshots; we'll describe those in detail in part 3 of our 'fundamentals' tutorials)"

2024-07-27 18:47 UTC, mkornacker commented on docs/release/fundamentals/tables-and-data-operations.ipynb
> +    "In addition to the structured data we've been exploring so far in this tutorial, Pixeltable has native support for multimodal data types: images, video, audio, and unstructured documents such as
I don't know if "multimodal types" is really a thing (Pxt tables are multi-modal because you can mix types; but each type is "uni-modal").

2024-07-29 00:11 UTC, aaron-siegel reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/230)* status: 0 of 8 files reviewed, 11 unresolved discussions (waiting on @mkornacker)

___
*[`docs/release/fundamentals/tables-and-data-operations.ipynb` line 46 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/230#gh-1693990760:-O2voCLqDcu9rvTcUNNs:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/4778a70f2db9ac0d6de0c095646109fec0af517d/docs/release/fundamentals/tables-and-data-operations.ipynb#L46)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

"which are simply hierarchical user-defined ..."

Might make sense to give an example of hierarchical directories somewhere.
</blockquote></details>

Done.
___
*[`docs/release/fundamentals/tables-and-data-operations.ipynb` line 96 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/230#gh-1693990909:-O2voCsP3GH2fQf_pYt-:b-8xa1rd) ([raw file](https://github.com/pixeltable/pixeltable/blob/4778a70f2db9ac0d6de0c095646109fec0af517d/docs/release/fundamentals/tables-and-data-operations.ipynb#L96)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Probably a good place to mention the data types that are available.
</blockquote></details>

Done (though I put it a little further down).
___
*[`docs/release/fundamentals/tables-and-data-operations.ipynb` line 124 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/230#gh-1694001479:-O2voIUNABLtqzjLeMjl:bb6un1j) ([raw file](https://github.com/pixeltable/pixeltable/blob/4778a70f2db9ac0d6de0c095646109fec0af517d/docs/release/fundamentals/tables-and-data-operations.ipynb#L124)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Probably a good place to mention again that there's also update() and delete(), and you'll get to those later.
</blockquote></details>

Done
___
*[`docs/release/fundamentals/tables-and-data-operations.ipynb` line 264 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/230#gh-1693990980:-O2voHH9EaeVmBgTCPVG:bb6un1j) ([raw file](https://github.com/pixeltable/pixeltable/blob/4778a70f2db9ac0d6de0c095646109fec0af517d/docs/release/fundamentals/tables-and-data-operations.ipynb#L264)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

"certain rows and/or certain columns"?
</blockquote></details>

Done
___
*[`docs/release/fundamentals/tables-and-data-operations.ipynb` line 688 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/230#gh-1693991406:-O2voHs00Fn0utWVofzj:bb6un1j) ([raw file](https://github.com/pixeltable/pixeltable/blob/4778a70f2db9ac0d6de0c095646109fec0af517d/docs/release/fundamentals/tables-and-data-operations.ipynb#L688)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Might want to show that in a notebook you don't need to call describe() explicitly.
</blockquote></details>

Done
___
*[`docs/release/fundamentals/tables-and-data-operations.ipynb` line 772 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/230#gh-1694001634:-O2voJVA1q-s1si0-eaP:bb6un1j) ([raw file](https://github.com/pixeltable/pixeltable/blob/4778a70f2db9ac0d6de0c095646109fec0af517d/docs/release/fundamentals/tables-and-data-operations.ipynb#L772)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

I would leave out terms like "easily", which has a slight marketing ring to it (and doesn't add anything - the user can decide how easy it is).
</blockquote></details>

Done
___
*[`docs/release/fundamentals/tables-and-data-operations.ipynb` line 906 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/230#gh-1694001782:-O2voK8EDWq_nnq1U1zX:bb6un1j) ([raw file](https://github.com/pixeltable/pixeltable/blob/4778a70f2db9ac0d6de0c095646109fec0af517d/docs/release/fundamentals/tables-and-data-operations.ipynb#L906)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

head and tail are actually not alternatives to limit; maybe "provide a different way of doing this"?
</blockquote></details>

Done
___
*[`docs/release/fundamentals/tables-and-data-operations.ipynb` line 1169 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/230#gh-1694001844:-O2voKdmCTo3b4Uxle4q:bk40x26) ([raw file](https://github.com/pixeltable/pixeltable/blob/4778a70f2db9ac0d6de0c095646109fec0af517d/docs/release/fundamentals/tables-and-data-operations.ipynb#L1169)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

omit '.describe()'?
</blockquote></details>

I'd prefer to use describe() for clarity, although I put a mention in earlier that it's not strictly necessary.
___
*[`docs/release/fundamentals/tables-and-data-operations.ipynb` line 1834 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/230#gh-1694002460:-O2voOzkAswtBEoTwLv4:bl7hjk2) ([raw file](https://github.com/pixeltable/pixeltable/blob/4778a70f2db9ac0d6de0c095646109fec0af517d/docs/release/fundamentals/tables-and-data-operations.ipynb#L1834)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Maybe use a computed expression here somewhere? Right now it looks like the update dict can only do literals.

Increment some integer column by 1?
</blockquote></details>

I'm deliberately leaving computed columns out of this tutorial section; they can be treated exhaustively in the next one. I'm not sure what we'd gain by shoehorning a mention of them in here, I think it'd just cause confusion.
___
*[`docs/release/fundamentals/tables-and-data-operations.ipynb` line 2115 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/230#gh-1694002788:-O2voevZAGubKYQQa5z2:b-bdjujb) ([raw file](https://github.com/pixeltable/pixeltable/blob/4778a70f2db9ac0d6de0c095646109fec0af517d/docs/release/fundamentals/tables-and-data-operations.ipynb#L2115)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Probably best to say "you can always call revert() (well, mostly, unless there are snapshots; we'll describe those in detail in part 3 of our 'fundamentals' tutorials)"
</blockquote></details>

I think this would just cause confusion at this point in the tutorial.

And it seems pointless to mention it? You can't actually modify a snapshot, so why do we need to point out that you can't revert it either? Before we've even talked about what snapshots are?
___
*[`docs/release/fundamentals/tables-and-data-operations.ipynb` line 2191 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/230#gh-1694002912:-O2vosjRC_Cpxxn238EL:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/4778a70f2db9ac0d6de0c095646109fec0af517d/docs/release/fundamentals/tables-and-data-operations.ipynb#L2191)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

I don't know if "multimodal types" is really a thing (Pxt tables are multi-modal because you can mix types; but each type is "uni-modal").
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-29 05:01 UTC, aaron-siegel reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/230)* status: 0 of 9 files reviewed, 11 unresolved discussions (waiting on @mkornacker)

___
*[`docs/release/fundamentals/tables-and-data-operations.ipynb` line 1834 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/230#gh-1694002460:-O2wrHSQCk91B0jsCNtN:b-wdoee9) ([raw file](https://github.com/pixeltable/pixeltable/blob/4778a70f2db9ac0d6de0c095646109fec0af517d/docs/release/fundamentals/tables-and-data-operations.ipynb#L1834)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I'm deliberately leaving computed columns out of this tutorial section; they can be treated exhaustively in the next one. I'm not sure what we'd gain by shoehorning a mention of them in here, I think it'd just cause confusion.
</blockquote></details>

Ah, you don't mean a computed column, you just mean a computed expression used directly in an update statement. Sorry, I misunderstood when I first read this.

I'll add something to this effect.


<!-- Sent from Reviewable.io -->

2024-07-30 23:53 UTC, mkornacker requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/230)* status: 0 of 9 files reviewed, 11 unresolved discussions (waiting on @aaron-siegel)

___
*[`docs/release/fundamentals/tables-and-data-operations.ipynb` line 1169 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/230#gh-1694001844:-O352fZE8WpgCqlpXoiq:b-rs7ahf) ([raw file](https://github.com/pixeltable/pixeltable/blob/4778a70f2db9ac0d6de0c095646109fec0af517d/docs/release/fundamentals/tables-and-data-operations.ipynb#L1169)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I'd prefer to use describe() for clarity, although I put a mention in earlier that it's not strictly necessary.
</blockquote></details>

I think people will forgot that you don't need it.


<!-- Sent from Reviewable.io -->

2024-07-30 23:53 UTC, mkornacker approved these changes

2024-08-02 00:33 UTC, merged