`import_json` and `import_data` methods in `pxt.io`
pixeltable/pixeltable pull request #244
Opened 2024-08-08 22:29 UTC by aaron-siegel

2024-08-08 22:29 UTC, aaron-siegel commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pixeltable/pixeltable/244)
<!-- Reviewable:end -->

2024-08-14 18:00 UTC, mkornacker requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/244)* status: 0 of 7 files reviewed, 13 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/exprs/expr.py` line 322 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O3ryUkN0mJhU9bdobkm:-O3ryUkN0mJhU9bdobkn:b-gbi8vy) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/exprs/expr.py#L322)):*
> ```Python
>             return o
>         # try to create a literal
>         if isinstance(o, list):
> ```

Add comment why you need to do these checks here.
___
*[`pixeltable/io/globals.py` line 142 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O3ryo272l94I6Etd3dC:-O3ryo272l94I6Etd3dD:b-4boy6m) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L142)):*
> ```Python
> 
> def import_data(
>     tbl_name: str, data: list[dict[str, Any]], *,
> ```

rows instead of data? In pandas I think the default way of giving it data is column-wise. It's probably worth pointing out several times that these are rows.

Maybe the function should be called import_rows().
___
*[`pixeltable/io/globals.py` line 142 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O4GyqJN0rmX76UQmNe6:-O4GyqJN0rmX76UQmNe7:b-jholfd) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L142)):*
> ```Python
> 
> def import_data(
>     tbl_name: str, data: list[dict[str, Any]], *,
> ```

tbl_name: it looks like this is really a tbl_path
___
*[`pixeltable/io/globals.py` line 149 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O4GwIaQ16Qvnk8O0VsR:-O4GwIaQ16Qvnk8O0VsS:bnz0lv1) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L149)):*
> ```Python
>     ) -> Table:
>     """
>     Creates a new `Table` from a list of dictionaries. The dictionaries must be of the form
> ```

This could also be interpreted as 'list of column vectors'
___
*[`pixeltable/io/globals.py` line 159 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O4GyuaR0qHX221YMmZz:-O4GyuaR0qHX221YMm_-:bb7mg8a) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L159)):*
> ```Python
> 
>     Args:
>         tbl_name: The name of the table to create.
> ```

path
___
*[`pixeltable/io/globals.py` line 160 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O3rz9h7-jb5cPfoClEN:-O3rz9h7-jb5cPfoClEO:b-3fza4j) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L160)):*
> ```Python
>     Args:
>         tbl_name: The name of the table to create.
>         data: The list of dictionaries to import.
> ```

Need to spell out that these are rows.
___
*[`pixeltable/io/globals.py` line 163 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O3rzOwtCcYqhEntF2p8:-O3rzOwtCcYqhEntF2p9:b4ngenj) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L163)):*
> ```Python
>         schema_overrides: If specified, then columns in `schema_overrides` will be given the specified types
>             as described above.
>         primary_key: The primary key of the table (see `create_table`).
> ```

Link to create_table() (here and elsewhere).

We should create links wherever possible, I think that's one of the strong points of the pandas docs.
___
*[`pixeltable/io/globals.py` line 174 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O4GyE7QB39mOZaNcSMc:-O4GyE7QB39mOZaNcSMd:b-r8j7ez) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L174)):*
> ```Python
>     schema: dict[str, pxt.ColumnType] = {}
>     for row in data:
>         for key, value in row.items():
> ```

col_name instead of key would make the following code a bit easier to read
___
*[`pixeltable/io/globals.py` line 189 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O4Gxdos1zq3I1NMubql:-O4Gxdos1zq3I1NMubqm:b-lyfhfv) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L189)):*
> ```Python
>                     supertype = pxt.ColumnType.supertype(schema[key], col_type)
>                     if supertype is None:
>                         raise excs.Error(f'Could not infer type of column `{key}`.')
> ```

It would be better to give a more useful error message, such as pointing out which values conflict (ex.: "value x in row i is a string, but value y in row j is a bool")
___
*[`pixeltable/io/globals.py` line 191 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O4GyLLUBvzwS6pQSgD4:-O4GyLLUBvzwS6pQSgD5:b-f580ie) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L191)):*
> ```Python
>                         raise excs.Error(f'Could not infer type of column `{key}`.')
>                     schema[key] = supertype
>     extraneous_keys = schema_overrides.keys() - schema.keys()
> ```

Introduce blank lines to subdivide into sections?
___
*[`pixeltable/io/globals.py` line 206 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O4GywMuA1xlPl3a_lQr:-O4GywMuA1xlPl3a_lQs:b-ufdgj9) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L206)):*
> ```Python
> 
> def import_json(
>     tbl_name: str, filepath_or_url: str, *,
> ```

tbl_path
___
*[`pixeltable/io/globals.py` line 235 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O4Gz7ry4mKlAVadoQvV:-O4Gz7ry4mKlAVadoQvW:b-hl5j87) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L235)):*
> ```Python
>     import urllib.request
> 
>     # TODO Consolidate this logic with other places where files/URLs are parsed
> ```

Why not just add a utils/urls.py and put that there. It's little work, and doing this is a separate PR generates a lot of overhead in terms of review mechanics.
___
*[`tests/data/json/example.json` line 1 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O4H-WKh2QIUs8M1dwyE:-O4H-WKh2QIUs8M1dwyF:br6kv8t) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/tests/data/json/example.json#L1)):*
> ```JSON
> [{
> ```

Cover all data types in this data, to the extent possible. That tests the functionality end-to-end (I understand that test_infer() already tests all types).


<!-- Sent from Reviewable.io -->

2024-08-14 20:57 UTC, aaron-siegel reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/244)* status: 0 of 8 files reviewed, 13 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/exprs/expr.py` line 322 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O3ryUkN0mJhU9bdobkm:-O4HDzCNEglZBtST1Jhv:bb6un1j) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/exprs/expr.py#L322)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Add comment why you need to do these checks here.
</blockquote></details>

Done
___
*[`pixeltable/io/globals.py` line 142 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O3ryo272l94I6Etd3dC:-O4H9jEb-YYyCpRAqzhr:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L142)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

rows instead of data? In pandas I think the default way of giving it data is column-wise. It's probably worth pointing out several times that these are rows.

Maybe the function should be called import_rows().
</blockquote></details>

Done.
___
*[`pixeltable/io/globals.py` line 142 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O4GyqJN0rmX76UQmNe6:-O4H9k3K6oSmdgAiz5nA:bt1b19p) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L142)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

tbl_name: it looks like this is really a tbl_path
</blockquote></details>

Renamed.
___
*[`pixeltable/io/globals.py` line 149 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O4GwIaQ16Qvnk8O0VsR:-O4H9nlqD499wS2Bj3j9:b-e335qo) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L149)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

This could also be interpreted as 'list of column vectors'
</blockquote></details>

I don't understand what this comment is saying
___
*[`pixeltable/io/globals.py` line 159 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O4GyuaR0qHX221YMmZz:-O4H9wuH0vaQuQWzTYgi:ba3o3s1) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L159)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

path
</blockquote></details>

Renamed
___
*[`pixeltable/io/globals.py` line 160 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O3rz9h7-jb5cPfoClEN:-O4H9zNb57UDKTU1-l-6:bb6un1j) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L160)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Need to spell out that these are rows.
</blockquote></details>

Done
___
*[`pixeltable/io/globals.py` line 163 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O3rzOwtCcYqhEntF2p8:-O4Hf_1_DMGHnjL_YUSi:bb6un1j) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L163)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Link to create_table() (here and elsewhere).

We should create links wherever possible, I think that's one of the strong points of the pandas docs.
</blockquote></details>

Done
___
*[`pixeltable/io/globals.py` line 174 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O4GyE7QB39mOZaNcSMc:-O4HAS_34mfd-lVChWWK:bb6un1j) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L174)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

col_name instead of key would make the following code a bit easier to read
</blockquote></details>

Done
___
*[`pixeltable/io/globals.py` line 189 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O4Gxdos1zq3I1NMubql:-O4HD_XM1lLexSEmZnb7:bb6un1j) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L189)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

It would be better to give a more useful error message, such as pointing out which values conflict (ex.: "value x in row i is a string, but value y in row j is a bool")
</blockquote></details>

Done
___
*[`pixeltable/io/globals.py` line 191 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O4GyLLUBvzwS6pQSgD4:-O4HDfclApdaFJIoyzhA:bb6un1j) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L191)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Introduce blank lines to subdivide into sections?
</blockquote></details>

Done
___
*[`pixeltable/io/globals.py` line 206 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O4GywMuA1xlPl3a_lQr:-O4HDhWq1sghRhCUIsgA:ba3o3s1) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L206)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

tbl_path
</blockquote></details>

Renamed
___
*[`pixeltable/io/globals.py` line 235 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O4Gz7ry4mKlAVadoQvV:-O4HDlLf3bPfR8x4IynJ:b764rvx) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/pixeltable/io/globals.py#L235)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Why not just add a utils/urls.py and put that there. It's little work, and doing this is a separate PR generates a lot of overhead in terms of review mechanics.
</blockquote></details>

I'd prefer to factor this out as a separate problem. The changes are more nuanced than you think
___
*[`tests/data/json/example.json` line 1 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/244#-O4H-WKh2QIUs8M1dwyE:-O4HfbSGB2rrXiP0H7eg:b-ef18j1) ([raw file](https://github.com/pixeltable/pixeltable/blob/3488dfaeb46957188e24afff339ae1a5d9b61cab/tests/data/json/example.json#L1)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Cover all data types in this data, to the extent possible. That tests the functionality end-to-end (I understand that test_infer() already tests all types).
</blockquote></details>

The only valid JSON types missing were float and dict, but I added them


<!-- Sent from Reviewable.io -->

2024-08-14 21:25 UTC, mkornacker approved these changes

2024-08-15 00:36 UTC, merged