Unit test for constructing an image column from a file path
pixeltable/pixeltable pull request #245
Opened 2024-08-12 23:19 UTC by mkornacker

2024-08-12 23:19 UTC, aaron-siegel commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pixeltable/pixeltable/245)
<!-- Reviewable:end -->

2024-08-13 04:53 UTC, aaron-siegel requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/245)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @mkornacker)

___
*[`tests/test_exprs.py` line 720 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/245#-O4937H-7DrrKYrFfg16:-O4937H-7DrrKYrFfg17:bdvyex7) ([raw file](https://github.com/pixeltable/pixeltable/blob/4aa3c9d321e27d553ce56bd4309da843dfa8fa1b/tests/test_exprs.py#L720)):*
> ```Python
>         _ = new_t.show(0)
> 
>     def test_str_to_img(self, reset_db) -> None:
> ```

This should probably be adjacent to `test_astype` in the code, and maybe called `test_astype_str_to_img`?
___
*[`tests/test_exprs.py` line 724 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/245#-O4939D90ARiqP4uKASs:-O4939D90ARiqP4uKASt:bb3kl2s) ([raw file](https://github.com/pixeltable/pixeltable/blob/4aa3c9d321e27d553ce56bd4309da843dfa8fa1b/tests/test_exprs.py#L724)):*
> ```Python
>         img_files = img_files[:5]
>         # insert relative paths into a table
>         parent_dir = Path(img_files[0]).parent
> ```

`assert(all(parent_dir == Path(img_file).parent for img_file in img_files))`?
___
*[`tests/test_exprs.py` line 726 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/245#-O493O1N29EEBYn0dsT9:-O493O1N29EEBYn0dsTA:b-ll1qr1) ([raw file](https://github.com/pixeltable/pixeltable/blob/4aa3c9d321e27d553ce56bd4309da843dfa8fa1b/tests/test_exprs.py#L726)):*
> ```Python
>         parent_dir = Path(img_files[0]).parent
>         t = pxt.create_table('astype_test', schema={'rel_path': StringType()})
>         validate_update_status(t.insert([{'rel_path': Path(f).name} for f in img_files]), expected_rows=len(img_files))
> ```

Remove spurious list creation (can be a generator inside `t.insert`)
___
*[`tests/test_exprs.py` line 739 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/245#-O493p-C4TkVWWm97AwR:-O493p-C4TkVWWm97AwS:b11igvw) ([raw file](https://github.com/pixeltable/pixeltable/blob/4aa3c9d321e27d553ce56bd4309da843dfa8fa1b/tests/test_exprs.py#L739)):*
> ```Python
> 
>         # the same for a select list item
>         loaded_imgs = \
> ```

best style is not to end a line with a backslash (it's somewhat archaic style - all formatters will complain about this)

cf. the Google style guide:
https://google.github.io/styleguide/pyguide.html#32-line-length


<!-- Sent from Reviewable.io -->

2024-08-14 21:33 UTC, mkornacker reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/245)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @aaron-siegel)

___
*[`tests/test_exprs.py` line 720 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/245#-O4937H-7DrrKYrFfg16:-O4HmMwb3izNt22Vkfzq:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/4aa3c9d321e27d553ce56bd4309da843dfa8fa1b/tests/test_exprs.py#L720)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This should probably be adjacent to `test_astype` in the code, and maybe called `test_astype_str_to_img`?
</blockquote></details>

Done.
___
*[`tests/test_exprs.py` line 726 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/245#-O493O1N29EEBYn0dsT9:-O4HmvIsDDQ24N6jKO81:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/4aa3c9d321e27d553ce56bd4309da843dfa8fa1b/tests/test_exprs.py#L726)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Remove spurious list creation (can be a generator inside `t.insert`)
</blockquote></details>

Done.
___
*[`tests/test_exprs.py` line 739 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/245#-O493p-C4TkVWWm97AwR:-O4HndN3EK6PMT4NtFfO:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/4aa3c9d321e27d553ce56bd4309da843dfa8fa1b/tests/test_exprs.py#L739)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

best style is not to end a line with a backslash (it's somewhat archaic style - all formatters will complain about this)

cf. the Google style guide:
https://google.github.io/styleguide/pyguide.html#32-line-length
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-16 16:00 UTC, aaron-siegel approved these changes

2024-08-16 16:03 UTC, merged