Type system performance improvements
pixeltable/pixeltable pull request #264
Opened 2024-08-26 22:51 UTC by aaron-siegel

On a sample dataset of ~500k rows, achieves a > 90% reduction in running time of the type inference logic in `import_rows()` on an M3 Max CPU, from 32.1 seconds to 2.56 seconds.

Most of the reduction (from 32 -> ~6 seconds) is achieved by eliminating the use of `deepcopy()` in `ColumnType.copy()`. The remainder is achieved by reducing object creation and dynamic evaluation in `ColumnType` and subclasses.

It is assumed that `ColumnType` instances are immutable. I believe that further optimizations are possible by making `ColumnType` instances formally immutable (as frozen dataclasses, say) and minimizing object creation. But those changes would be more invasive, and I'm pretty sure this is enough to get type inference off the critical performance path.

2024-08-26 22:51 UTC, aaron-siegel commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pixeltable/pixeltable/264)
<!-- Reviewable:end -->

2024-08-26 23:00 UTC, mkornacker requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/264)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/type_system.py` line 171 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/264#-O5FuP-q8EGDGd_ujCJe:-O5FuP-q8EGDGd_ujCJf:brc02ep) ([raw file](https://github.com/pixeltable/pixeltable/blob/fa9db9afed4946bae10b3ad8e9e5cea9dfaec0b7/pixeltable/type_system.py#L171)):*
> ```Python
>         return isinstance(other, ColumnType) and self.matches(other) and self.nullable == other.nullable
> 
>     def is_supertype_of(self, other: ColumnType, ignore_nullable: bool = False) -> bool:
> ```

This should probably not do any object construction at all but simply do checks (and subclasses can specialize their own _is_supertype_of())
___
*[`pixeltable/type_system.py` line 182 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/264#-O5Ftt516SSzqUW8_TJw:-O5Ftt516SSzqUW8_TJx:bu62cpc) ([raw file](https://github.com/pixeltable/pixeltable/blob/fa9db9afed4946bae10b3ad8e9e5cea9dfaec0b7/pixeltable/type_system.py#L182)):*
> ```Python
>     def matches(self, other: ColumnType) -> bool:
>         """Two types match if they're equal, aside from nullability"""
>         # Default: just compare base types (this works for all types whose only parameter is nullable)
> ```

Add check that this is a scalar type.


<!-- Sent from Reviewable.io -->

2024-08-27 02:06 UTC, aaron-siegel reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/264)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/type_system.py` line 171 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/264#-O5FuP-q8EGDGd_ujCJe:-O5GZxxW0KAovn595yPA:bsurnhv) ([raw file](https://github.com/pixeltable/pixeltable/blob/fa9db9afed4946bae10b3ad8e9e5cea9dfaec0b7/pixeltable/type_system.py#L171)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

This should probably not do any object construction at all but simply do checks (and subclasses can specialize their own _is_supertype_of())
</blockquote></details>

I agree, but it's out of scope for this PR - it's not on the critical path to the problem at hand, and cost of object creation is tiny compared to the perf problems solved by this PR. `ColumnType` needs more substantial work to minimize object creation and it'll be easiest to consider it in the context of that future project
___
*[`pixeltable/type_system.py` line 182 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/264#-O5Ftt516SSzqUW8_TJw:-O5GZXK902hBhegxYDEN:b-taxvxl) ([raw file](https://github.com/pixeltable/pixeltable/blob/fa9db9afed4946bae10b3ad8e9e5cea9dfaec0b7/pixeltable/type_system.py#L182)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Add check that this is a scalar type.
</blockquote></details>

No- default implementation works for various non-scalars as well (Video, Audio)


<!-- Sent from Reviewable.io -->

2024-08-27 19:10 UTC, mkornacker commented on pixeltable/type_system.py
> +            # TODO In the future we should accept scalars too, which would enable us to remove this top-level check
remove todo (let's discuss this first...)

2024-08-27 19:15 UTC, mkornacker approved these changes

2024-08-28 06:32 UTC, merged