Type-checking correctness for `catalog`, `functions`, and `ext` packages
pixeltable/pixeltable pull request #277
Opened 2024-09-07 19:24 UTC by aaron-siegel

2024-09-07 19:24 UTC, aaron-siegel commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pixeltable/pixeltable/277)
<!-- Reviewable:end -->

2024-09-12 01:17 UTC, mkornacker commented on pixeltable/catalog/table.py
> +        self.add_column(type=None, stored=None, print_stats=False, **{col_name: spec})
comment: why does it need those explicitly?

2024-09-12 01:17 UTC, mkornacker commented on pixeltable/catalog/table_version.py
> +        self.cols = []  # contains complete history of columns, incl dropped ones
preserve comments

2024-09-12 01:17 UTC, mkornacker commented on pixeltable/catalog/table_version.py
> +            self, plan: Optional['exec.ExecNode'], where_clause: Optional[sql.ColumnElement[bool]],
Does it require 'bool'? If not, let's leave it off, we can't statically type-check exprs anyway.

2024-09-12 01:17 UTC, mkornacker commented on pixeltable/catalog/table_version_path.py
> -        if col_name == _POS_COLUMN_NAME and self.is_component_view():
Where did this go?

2024-09-12 01:17 UTC, mkornacker commented on pixeltable/exprs/expr.py
> +    def retarget(self, tbl: catalog.TableVersionPath) -> Self:
This is only available starting with 3.11.

2024-09-12 01:17 UTC, mkornacker commented on pixeltable/functions/string.py
> +from typing import Any, Literal, Optional
Where is Literal being used?

2024-09-12 01:17 UTC, mkornacker commented on pixeltable/metadata/schema.py
> +    id: orm.Mapped[uuid.UUID] = orm.mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, nullable=False)
requires explanatory comment

2024-09-12 01:20 UTC, mkornacker requested changes

2024-09-12 01:20 UTC, mkornacker commented on Makefile
> +	@mypy pixeltable/*.py pixeltable/catalog pixeltable/ext pixeltable/functions
dummy comment; ignore

2024-09-12 16:29 UTC, aaron-siegel reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/277)* status: 0 of 29 files reviewed, 8 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/catalog/table.py` line 291 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/277#gh-1755933375:-O6b0SfH9ePO69SkotCn:b-u6ztjm) ([raw file](https://github.com/pixeltable/pixeltable/blob/480fff23f54205d656a8067c0e3bb1ace4837019/pixeltable/catalog/table.py#L291)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

comment: why does it need those explicitly?
</blockquote></details>

mypy complains if it sees a `**{...}` argument and the call doesn't also mention the explicit named parameters.

The alternative would be a `# type: ignore` directive.
___
*[`pixeltable/catalog/table_version.py` line 153 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/277#gh-1755934407:-O6b0wal-8wnrOB3K_4C:bb7hquh) ([raw file](https://github.com/pixeltable/pixeltable/blob/480fff23f54205d656a8067c0e3bb1ace4837019/pixeltable/catalog/table_version.py#L153)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

preserve comments
</blockquote></details>

huh?
___
*[`pixeltable/catalog/table_version.py` line 836 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/277#gh-1755937598:-O6b1SNK3oEMWx9sXQ_M:bxabxgm) ([raw file](https://github.com/pixeltable/pixeltable/blob/480fff23f54205d656a8067c0e3bb1ace4837019/pixeltable/catalog/table_version.py#L836)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Does it require 'bool'? If not, let's leave it off, we can't statically type-check exprs anyway.
</blockquote></details>

It's fine without the `bool`; I removed it
___
*[`pixeltable/catalog/table_version_path.py` line 0 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/277#gh-1755939306:-O6b1fiW9Mhi-2Tw9f0_:buiraz9) ([raw file](https://github.com/pixeltable/pixeltable/blob/480fff23f54205d656a8067c0e3bb1ace4837019/pixeltable/catalog/table_version_path.py#L0)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map [this GitHub inline comment thread](https://github.com/pixeltable/pixeltable/pull/277#discussion_r1755939306) to the right spot — sorry!)*

Where did this go?
</blockquote></details>

I assume this is referring to the `RowidRef` thing?

It isn't actually being used anywhere (removing this clause broke no tests), and is statically AND semantically false, since (1) the static result type of this method is `ColumnRef`, and (2) clients of this method freely assume they're getting a `ColumnRef`.

If you think it needs to stick around, we should discuss
___
*[`pixeltable/exprs/expr.py` line 219 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/277#gh-1755941321:-O6b25na8lgbqNpJOz8p:bhskpyq) ([raw file](https://github.com/pixeltable/pixeltable/blob/480fff23f54205d656a8067c0e3bb1ace4837019/pixeltable/exprs/expr.py#L219)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

This is only available starting with 3.11.
</blockquote></details>

Not true. It's available on 3.9+ via the `typing_extensions` package, which is how I've imported it.

BTW I do all my development and testing on 3.9 for exactly this reason.
___
*[`pixeltable/functions/string.py` line 15 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/277#gh-1755942742:-O6b2Y24BhlfP_73enrW:buronh3) ([raw file](https://github.com/pixeltable/pixeltable/blob/480fff23f54205d656a8067c0e3bb1ace4837019/pixeltable/functions/string.py#L15)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Where is Literal being used?
</blockquote></details>

oops, it's not. It's residue from a failed experiment.

Fixed
___
*[`pixeltable/metadata/schema.py` line 68 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/277#gh-1755944532:-O6b2ieb8ABVfKa6blUh:bticc1h) ([raw file](https://github.com/pixeltable/pixeltable/blob/480fff23f54205d656a8067c0e3bb1ace4837019/pixeltable/metadata/schema.py#L68)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

requires explanatory comment
</blockquote></details>

I don't know if I agree. We're going to be using this pattern throughout the codebase as we do this refactor. The "explanatory comment" would be a link to this doc:

https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#whatsnew-20-orm-declarative-typing

which explains the correct (type-safe) way to define these mappings in SQLAlchemy 2.0. Do we really need to put that URL in the code base every time we follow this pattern? If not, then why here specifically (the only thing that's special about it is it happens to be the first one we've modernized?)


<!-- Sent from Reviewable.io -->

2024-09-13 05:32 UTC, mkornacker requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/277)* status: 0 of 33 files reviewed, 7 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/catalog/table.py` line 291 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/277#gh-1755933375:-O6dqXlQ6I3MxAWjAcnU:b3e4e3m) ([raw file](https://github.com/pixeltable/pixeltable/blob/480fff23f54205d656a8067c0e3bb1ace4837019/pixeltable/catalog/table.py#L291)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

mypy complains if it sees a `**{...}` argument and the call doesn't also mention the explicit named parameters.

The alternative would be a `# type: ignore` directive.
</blockquote></details>

I meant: comment in the code. Otherwise the next person might remove that again.

Maybe type: ignore is better...
___
*[`pixeltable/catalog/table_version.py` line 153 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/277#gh-1755934407:-O6dqMRrBHD1UzyCSXpW:btrlleu) ([raw file](https://github.com/pixeltable/pixeltable/blob/480fff23f54205d656a8067c0e3bb1ace4837019/pixeltable/catalog/table_version.py#L153)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

huh?
</blockquote></details>

Each of the initializations has a comment. Those need to move to the corresponding class-level declaration.
___
*[`pixeltable/catalog/table_version_path.py` line 0 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/277#gh-1755939306:-O6dr6fwDbIf2P9g89hJ:b-pf953p) ([raw file](https://github.com/pixeltable/pixeltable/blob/480fff23f54205d656a8067c0e3bb1ace4837019/pixeltable/catalog/table_version_path.py#L0)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I assume this is referring to the `RowidRef` thing?

It isn't actually being used anywhere (removing this clause broke no tests), and is statically AND semantically false, since (1) the static result type of this method is `ColumnRef`, and (2) clients of this method freely assume they're getting a `ColumnRef`.

If you think it needs to stick around, we should discuss
</blockquote></details>

Okay, we need to add a test, but this is required functionality. At least the object detection notebook is referencing this.


<!-- Sent from Reviewable.io -->

2024-09-13 08:03 UTC, aaron-siegel reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/277)* status: 0 of 33 files reviewed, 7 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/catalog/table.py` line 291 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/277#gh-1755933375:-O6eIK7X4OWwvQ5uVhja:b-rr41ox) ([raw file](https://github.com/pixeltable/pixeltable/blob/480fff23f54205d656a8067c0e3bb1ace4837019/pixeltable/catalog/table.py#L291)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

I meant: comment in the code. Otherwise the next person might remove that again.

Maybe type: ignore is better...
</blockquote></details>

Well the next person won't be able to just remove it, since that will now trigger a type checking failure in CI.

It's bothering you a lot more than it's bothering me so you make the call on what to do.
___
*[`pixeltable/catalog/table_version.py` line 153 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/277#gh-1755934407:-O6eIiWxANUFu58ZIO-C:b-yglom6) ([raw file](https://github.com/pixeltable/pixeltable/blob/480fff23f54205d656a8067c0e3bb1ace4837019/pixeltable/catalog/table_version.py#L153)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Each of the initializations has a comment. Those need to move to the corresponding class-level declaration.
</blockquote></details>

This was taken care of when merging your latest PR (which did the same thing)
___
*[`pixeltable/catalog/table_version_path.py` line 0 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/277#gh-1755939306:-O6eIoKU5o24ThZB2eGw:bojuz74) ([raw file](https://github.com/pixeltable/pixeltable/blob/480fff23f54205d656a8067c0e3bb1ace4837019/pixeltable/catalog/table_version_path.py#L0)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Okay, we need to add a test, but this is required functionality. At least the object detection notebook is referencing this.
</blockquote></details>

That's not true. The object detection notebook is running in CI now (and passing). It appears that without it, `t.pos` resolves as a `ColumnRef` instead and still gives the right answers.

If we still need it as a separate class, then either we need to (1) make RowidRef a subclass of ColumnRef (or give them a common superclass) or (2) add RowidRef to all the upstream Unions (up to Table, which makes it user-facing) or (3) replace all the Unions with Expr.


<!-- Sent from Reviewable.io -->

2024-09-17 19:25 UTC, mkornacker approved these changes

2024-09-18 04:53 UTC, merged