Inline expression fixes
pixeltable/pixeltable pull request #280
Opened 2024-09-13 15:42 UTC by aaron-siegel

Reworks the `InlineArray`/`InlineDict` pattern, fixing several issues. Functionally:
- Introduces a new `InlineList` class that is separate from `InlineArray`, cleaning up the type-munging that was present in the old class
- Interprets all Python lists as `InlineList`s (previously, Pixeltable was trying to be clever and variously interpret them as arrays or lists, leading to confusing/unexpected behavior)
- Adds a `pxt.array()` global for constructing `InlineArray`s
- Improves the DB migration tests, adding a new row to the base table after loading to ensure computed columns are functioning correctly

In addition, refactors the way elements are stored in `InlineArray`/`InlineList`/`InlineDict`. The inline exprs can contain a combination of literals and subexpressions. Previously, they were stored in a left-right tuple with literals being directly stored in the inline expr. In the new architecture, all children of inline exprs are themselves exprs, with literal children being wrapped in an instance of `expr.Literal`. This substantially simplifies the code for `Inline*` in several places, and it also fixes two bugs in the old architecture:
- Literals appearing in inline structures were not being validated properly; they would accept invalid literals and then trigger a `JSONSerialization` error downstream
- Timestamps appearing in inline structures were serialized incorrectly
The new architecture fixes these issues by unifying the code paths for literal creation and validation.

2024-09-13 15:42 UTC, aaron-siegel commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pixeltable/pixeltable/280)
<!-- Reviewable:end -->

2024-09-25 17:14 UTC, mkornacker requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/280)* status: 0 of 30 files reviewed, 9 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/type_system.py` line 400 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/280#-O7e0faE3lw3s7-b2OeT:-O7e0faE3lw3s7-b2OeU:b-n9g400) ([raw file](https://github.com/pixeltable/pixeltable/blob/3200107b862f16a0bef5445f363f63b90a8e327b/pixeltable/type_system.py#L400)):*
> ```Python
> 
>     def print_value(self, val: Any) -> str:
>         return str(val)
> ```

What is this for? The semantics of InvalidType are that it's never involved in expr evaluation, meaning there are no values. Ie, by the time you need to display values, you should have an actual type.
___
*[`pixeltable/exprs/function_call.py` line 216 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/280#-O7e3cH-ADKDj-GRq4rT:-O7e3cH-ADKDj-GRq4rU:bum1r2b) ([raw file](https://github.com/pixeltable/pixeltable/blob/3200107b862f16a0bef5445f363f63b90a8e327b/pixeltable/exprs/function_call.py#L216)):*
> ```Python
>                 ):
>                     raise excs.Error(
>                         f'Parameter {param_name} (in function {name}): argument type {arg.col_type} does not match parameter type '
> ```

name -> fn_name
___
*[`pixeltable/exprs/inline_expr.py` line 24 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/280#-O7e5E3C3zFYMjySxV1m:-O7e5E3C3zFYMjySxV1n:b-tcd2pe) ([raw file](https://github.com/pixeltable/pixeltable/blob/3200107b862f16a0bef5445f363f63b90a8e327b/pixeltable/exprs/inline_expr.py#L24)):*
> ```Python
>     """
> 
>     elements: list[Expr]
> ```

No need for this, refer to components instead. Duplicating this creates an opportunity for divergence. All Expr classes follow that pattern.
___
*[`pixeltable/exprs/inline_expr.py` line 40 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/280#-O7e5gj7B29plIpa_hMa:-O7e5gj7B29plIpa_hMb:b-ycxskz) ([raw file](https://github.com/pixeltable/pixeltable/blob/3200107b862f16a0bef5445f363f63b90a8e327b/pixeltable/exprs/inline_expr.py#L40)):*
> ```Python
>             inferred_element_type = inferred_element_type.supertype(expr.col_type)
>             if inferred_element_type is None:
>                 raise excs.Error('Could not infer element type of array')
> ```

Would be good to say something about conflicting element types and bring up the type of expr and inferred_element_type
___
*[`pixeltable/exprs/inline_expr.py` line 61 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/280#-O7e6Hf19tZP-JuS-yRe:-O7e6Hf19tZP-JuS-yRf:b-ug5rb4) ([raw file](https://github.com/pixeltable/pixeltable/blob/3200107b862f16a0bef5445f363f63b90a8e327b/pixeltable/exprs/inline_expr.py#L61)):*
> ```Python
>         return f'[{", ".join(elem_strs)}]'
> 
>     def _equals(self, _: InlineList) -> bool:
> ```

_: InlineArray
___
*[`pixeltable/exprs/inline_expr.py` line 93 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/280#-O7e6qRf9sDohO4j6MCy:-O7e6qRf9sDohO4j6MCz:b-ya81ng) ([raw file](https://github.com/pixeltable/pixeltable/blob/3200107b862f16a0bef5445f363f63b90a8e327b/pixeltable/exprs/inline_expr.py#L93)):*
> ```Python
>     """
> 
>     elements: list[Expr]
> ```

Same as above
___
*[`pixeltable/exprs/inline_expr.py` line 140 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/280#-O7e73OPEB5m06G-Qj2X:-O7e73OPEB5m06G-Qj2Y:b-o8fx0m) ([raw file](https://github.com/pixeltable/pixeltable/blob/3200107b862f16a0bef5445f363f63b90a8e327b/pixeltable/exprs/inline_expr.py#L140)):*
> ```Python
>     """
> 
>     expr_dict: dict[str, Expr]
> ```

dict[str, int], where the value is the components idx
___
*[`pixeltable/exprs/inline_expr.py` line 181 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/280#-O7e7h-C58YQUrqorMvS:-O7e7h-C58YQUrqorMvT:b-fylnqg) ([raw file](https://github.com/pixeltable/pixeltable/blob/3200107b862f16a0bef5445f363f63b90a8e327b/pixeltable/exprs/inline_expr.py#L181)):*
> ```Python
>         }
> 
>     def unwrap(self) -> dict[str, Any]:
> ```

to_dict() is more intuitive. unwrap doesn't tell me anything and I have to look up the implementation.
___
*[`pixeltable/tool/create_test_db_dump.py` line 30 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/280#-O7e998T-FGx1objJCOV:-O7e998U--a6bHTO1yHC:bp4jred) ([raw file](https://github.com/pixeltable/pixeltable/blob/3200107b862f16a0bef5445f363f63b90a8e327b/pixeltable/tool/create_test_db_dump.py#L30)):*
> ```Python
>         if sys.version_info >= (3, 10):
>             raise RuntimeError(
>                 'This script must be run on Python 3.9. '
> ```

I guess we should discuss the future of this.


<!-- Sent from Reviewable.io -->

2024-09-25 21:50 UTC, aaron-siegel reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/280)* status: 0 of 31 files reviewed, 9 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/type_system.py` line 400 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/280#-O7e0faE3lw3s7-b2OeT:-O7f1XDk1F9B-bud40SJ:b-49m06m) ([raw file](https://github.com/pixeltable/pixeltable/blob/3200107b862f16a0bef5445f363f63b90a8e327b/pixeltable/type_system.py#L400)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

What is this for? The semantics of InvalidType are that it's never involved in expr evaluation, meaning there are no values. Ie, by the time you need to display values, you should have an actual type.
</blockquote></details>

It's because I added support for `None` as a literal, with type `InvalidType(nullable=True)`. I believe this is the correct treatment of a `None` literal in the present hierarchy; another solution would be to create a separate `NoneType`.
___
*[`pixeltable/exprs/function_call.py` line 216 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/280#-O7e3cH-ADKDj-GRq4rT:-O7eke2z8Bj_o0AZQKtp:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/3200107b862f16a0bef5445f363f63b90a8e327b/pixeltable/exprs/function_call.py#L216)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

name -> fn_name
</blockquote></details>

Done.
___
*[`pixeltable/exprs/inline_expr.py` line 24 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/280#-O7e5E3C3zFYMjySxV1m:-O7f-AlbDHuK05FbErwe:b1wheun) ([raw file](https://github.com/pixeltable/pixeltable/blob/3200107b862f16a0bef5445f363f63b90a8e327b/pixeltable/exprs/inline_expr.py#L24)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

No need for this, refer to components instead. Duplicating this creates an opportunity for divergence. All Expr classes follow that pattern.
</blockquote></details>

Ah, good catch. I'd originally had it this way, but ran into problems due to the way the `components` list is repopulated with copies. But I later refactored in a way that obviates this concern. I removed the redundant `elements` list (it's definitely better this way)
___
*[`pixeltable/exprs/inline_expr.py` line 40 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/280#-O7e5gj7B29plIpa_hMa:-O7f83kVDlyBGKz1ZIBa:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/3200107b862f16a0bef5445f363f63b90a8e327b/pixeltable/exprs/inline_expr.py#L40)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Would be good to say something about conflicting element types and bring up the type of expr and inferred_element_type
</blockquote></details>

Done.
___
*[`pixeltable/exprs/inline_expr.py` line 61 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/280#-O7e6Hf19tZP-JuS-yRe:-O7f-q1eBKB4iA4V9QZ8:bt2vr1b) ([raw file](https://github.com/pixeltable/pixeltable/blob/3200107b862f16a0bef5445f363f63b90a8e327b/pixeltable/exprs/inline_expr.py#L61)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

_: InlineArray
</blockquote></details>

Fixed.
___
*[`pixeltable/exprs/inline_expr.py` line 93 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/280#-O7e6qRf9sDohO4j6MCy:-O7f-rAF0mok9IuNoswf:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/3200107b862f16a0bef5445f363f63b90a8e327b/pixeltable/exprs/inline_expr.py#L93)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[`pixeltable/exprs/inline_expr.py` line 140 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/280#-O7e73OPEB5m06G-Qj2X:-O7f-s6VCs-STimcyPbH:b46kui4) ([raw file](https://github.com/pixeltable/pixeltable/blob/3200107b862f16a0bef5445f363f63b90a8e327b/pixeltable/exprs/inline_expr.py#L140)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

dict[str, int], where the value is the components idx
</blockquote></details>

Done. Actually this can just be a list[str] since the indices are always 0, ..., n-1.
___
*[`pixeltable/exprs/inline_expr.py` line 181 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/280#-O7e7h-C58YQUrqorMvS:-O7f-vqF0JUpqoRH5Jjj:bacpt8e) ([raw file](https://github.com/pixeltable/pixeltable/blob/3200107b862f16a0bef5445f363f63b90a8e327b/pixeltable/exprs/inline_expr.py#L181)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

to_dict() is more intuitive. unwrap doesn't tell me anything and I have to look up the implementation.
</blockquote></details>

`to_dict` isn't a great name because there are so many dictionaries floating around. We also have `as_dict` for serialization, and `InlineDict` is itself already a dict of sorts. The ambiguity meant it didn't save me from having to look up the implementation; it took me an extra few minutes of code-reading to figure out which dict was implied here and I'd imagine others would similarly stumble.

How about `to_value_dict` or `unwrap_dict_values` or `expand_dict_values` or something of the sort?
___
*[`pixeltable/tool/create_test_db_dump.py` line 30 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/280#-O7e998T-FGx1objJCOV:-O7f1NTuB8mo5Eja9w28:bfvntfx) ([raw file](https://github.com/pixeltable/pixeltable/blob/3200107b862f16a0bef5445f363f63b90a8e327b/pixeltable/tool/create_test_db_dump.py#L30)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

I guess we should discuss the future of this.
</blockquote></details>

Yeah, the pickling incompatibility is going to be a real problem


<!-- Sent from Reviewable.io -->

2024-09-26 00:54 UTC, mkornacker approved these changes

2024-09-26 21:07 UTC, merged