Reformatting code cells to fit display width
pixeltable/pixeltable pull request #288
Opened 2024-09-24 22:40 UTC by mkornacker

A lot of the code cells are shown with their right side cut off due to the overly-narrow notebook display on readme.io.

2024-09-24 22:40 UTC, aaron-siegel commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pixeltable/pixeltable/288)
<!-- Reviewable:end -->

2024-09-24 23:01 UTC, aaron-siegel requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/288)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @mkornacker)

___
*[`docs/release/tutorials/audio-transcriptions.ipynb` line 497 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/288#-O7aDJJK-gK8VFzttdWs:-O7aDJJK-gK8VFzttdWt:b-4o0vhs) ([raw file](https://github.com/pixeltable/pixeltable/blob/089fa2fefd70309750f7d31db79dbf5f1d115b64/docs/release/tutorials/audio-transcriptions.ipynb#L497)):*
> ```
>     "from pixeltable.functions import whisper\n",
>     "\n",
>     "video_table['transcription'] = \\\n",
> ```

We should stick to standard coding conventions in our notebooks. In this case, (I'm quoting from the Google python style guide, but all linting tools agree on this as well, AFAIK):
- Do not use a backslash for [explicit line continuation](https://docs.python.org/3/reference/lexical_analysis.html#explicit-line-joining). Instead, make use of Python’s [implicit line joining inside parentheses, brackets and braces](http://docs.python.org/reference/lexical_analysis.html#implicit-line-joining). If necessary, you can add an extra pair of parentheses around an expression.

See: https://google.github.io/styleguide/pyguide.html Section 3.2.
___
*[`docs/release/tutorials/audio-transcriptions.ipynb` line 500 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/288#-O7aDz6i0xD9cUgq1_pY:-O7aDz6i0xD9cUgq1_pZ:bqqnkf0) ([raw file](https://github.com/pixeltable/pixeltable/blob/089fa2fefd70309750f7d31db79dbf5f1d115b64/docs/release/tutorials/audio-transcriptions.ipynb#L500)):*
> ```
>     "    whisper.transcribe(\n",
>     "        audio=video_table.audio, model='base.en')\n",
>     "video_table.select(\n",
> ```

This line fits comfortably on the readme.io display and does not need to be broken up
___
*[`docs/release/tutorials/audio-transcriptions.ipynb` line 535 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/288#-O7aF01cAxLyCsucB7d5:-O7aF01cAxLyCsucB7d6:b-7vc81w) ([raw file](https://github.com/pixeltable/pixeltable/blob/089fa2fefd70309750f7d31db79dbf5f1d115b64/docs/release/tutorials/audio-transcriptions.ipynb#L535)):*
> ```
>     "    iterator=StringSplitter.create(\n",
>     "        text=video_table.transcription.text,\n",
>     "        separators='sentence')\n",
> ```

Coding convention: I prefer to put the closing paren on a separate line, with the same indentation as the opening paren. This is the convention I've been using in other notebooks & I think we should be consistent in our docs. (Though there's less of a strict consensus on this one - Google is agnostic, but most linters agree with me, I think)
___
*[`docs/release/tutorials/audio-transcriptions.ipynb` line 617 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/288#-O7aFJoW9HdnsnUQwO23:-O7aFJoW9HdnsnUQwO24:b-td8ckf) ([raw file](https://github.com/pixeltable/pixeltable/blob/089fa2fefd70309750f7d31db79dbf5f1d115b64/docs/release/tutorials/audio-transcriptions.ipynb#L617)):*
> ```
>    ],
>    "source": [
>     "sentences_view.select(\n",
> ```

fits comfortably on a single line, doesn't need to be broken up
___
*[`docs/release/tutorials/audio-transcriptions.ipynb` line 751 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/288#-O7aFQyK8w3MInGuR-P0:-O7aFQyK8w3MInGuR-P1:bw6rj5q) ([raw file](https://github.com/pixeltable/pixeltable/blob/089fa2fefd70309750f7d31db79dbf5f1d115b64/docs/release/tutorials/audio-transcriptions.ipynb#L751)):*
> ```
>     "\n",
>     "sentences_view\\\n",
>     ".order_by(sim, asc=False)\\\n",
> ```

Avoid backslash for explicit line continuation (there are a few more of these below too)
___
*[`docs/release/tutorials/audio-transcriptions.ipynb` line 755 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/288#-O7aFgXc-cuywoxvY0g6:-O7aFgXc-cuywoxvY0g7:b-fpbanh) ([raw file](https://github.com/pixeltable/pixeltable/blob/089fa2fefd70309750f7d31db79dbf5f1d115b64/docs/release/tutorials/audio-transcriptions.ipynb#L755)):*
> ```
>     ".select(\n",
>     "    sentences_view.text, similarity=sim\n",
>     ")\\\n",
> ```

Yes! This is the preferred way to close parens for multiline expressions
___
*[`docs/release/tutorials/audio-transcriptions.ipynb` line 1239 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/288#-O7aFpbI318su-SgFygZ:-O7aFpbI318su-SgFyg_:bfdbeau) ([raw file](https://github.com/pixeltable/pixeltable/blob/089fa2fefd70309750f7d31db79dbf5f1d115b64/docs/release/tutorials/audio-transcriptions.ipynb#L1239)):*
> ```
>    "nbconvert_exporter": "python",
>    "pygments_lexer": "ipython3",
>    "version": "3.10.14"
> ```

Random comment: I suggest running your environment on Python 3.9 (our minimum supported version) as a compatibility safeguard.


<!-- Sent from Reviewable.io -->

2024-09-24 23:14 UTC, mkornacker reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/288)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @aaron-siegel)

___
*[`docs/release/tutorials/audio-transcriptions.ipynb` line 497 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/288#-O7aDJJK-gK8VFzttdWs:-O7aIrJxA3-__c0iTc9O:bdagybw) ([raw file](https://github.com/pixeltable/pixeltable/blob/089fa2fefd70309750f7d31db79dbf5f1d115b64/docs/release/tutorials/audio-transcriptions.ipynb#L497)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

We should stick to standard coding conventions in our notebooks. In this case, (I'm quoting from the Google python style guide, but all linting tools agree on this as well, AFAIK):
- Do not use a backslash for [explicit line continuation](https://docs.python.org/3/reference/lexical_analysis.html#explicit-line-joining). Instead, make use of Python’s [implicit line joining inside parentheses, brackets and braces](http://docs.python.org/reference/lexical_analysis.html#implicit-line-joining). If necessary, you can add an extra pair of parentheses around an expression.

See: https://google.github.io/styleguide/pyguide.html Section 3.2.
</blockquote></details>

It seems like continuation is more commonly used in tutorials. I agree that we should do that in the Pixeltable code per se, but I don't see what this has to do with it.
___
*[`docs/release/tutorials/audio-transcriptions.ipynb` line 500 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/288#-O7aDz6i0xD9cUgq1_pY:-O7aJ1yc8stwEnrUacoP:b22tzg7) ([raw file](https://github.com/pixeltable/pixeltable/blob/089fa2fefd70309750f7d31db79dbf5f1d115b64/docs/release/tutorials/audio-transcriptions.ipynb#L500)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This line fits comfortably on the readme.io display and does not need to be broken up
</blockquote></details>

I still think it's easier to read. What speaks against breaking it up?


<!-- Sent from Reviewable.io -->

2024-09-25 16:03 UTC, aaron-siegel approved these changes

2024-09-25 16:15 UTC, merged