Converting aggregate FunctionCalls to SQL
pixeltable/pixeltable pull request #320
Opened 2024-10-06 00:09 UTC by mkornacker

Also:
- new class ExprDict
- fixes a bug in TableVersion.insert(df), which didn't generate correct rowids
- changes limit=0 to mean 'return no rows' instead of 'return all rows'

2024-10-06 00:09 UTC, aaron-siegel commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pixeltable/pixeltable/320)
<!-- Reviewable:end -->

2024-10-09 23:42 UTC, aaron-siegel requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/320)* status: 0 of 28 files reviewed, 25 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/plan.py` line 109 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8cIzn_BCv0IdMvs5E-:-O8cIzn_BCv0IdMvs5E0:b-styobp) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L109)):*
> ```Python
>             exprs.Expr.list_subexprs(
>                 candidates, expr_class=exprs.FunctionCall,
>                 filter=lambda e: bool(e.is_agg_fn_call and not e.is_window_fn_call)))
> ```

The enclosing `bool` shouldn't be necessary here?
___
*[`pixeltable/plan.py` line 131 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8cJPGJ5suE3yMfxF_z:-O8cJPGJ5suE3yMfxFa-:b-4ear9j) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L131)):*
> ```Python
>         # check that filter doesn't contain aggregates
>         if self.filter is not None:
>             if bool(
> ```

Is the type checker demanding these `bool`s?
___
*[`pixeltable/plan.py` line 132 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8cJpXWDlyJN-CATyOq:-O8cJpXWDlyJN-CATyOr:b-51p101) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L132)):*
> ```Python
>         if self.filter is not None:
>             if bool(
>                 next(self.filter.subexprs(expr_class=exprs.FunctionCall, filter=lambda e: _is_agg_fn_call(e)), False)
> ```

This might be cleaner:
```
if any(_is_agg_fn_call(e) for e in self.filter.subexprs(expr_class=exprs.FunctionCall))
```
___
*[`pixeltable/plan.py` line 190 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8gv1OMCfEU99_UP_XA:-O8gv1OMCfEU99_UP_XB:b-69s23l) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L190)):*
> ```Python
>         row_builder.set_slot_idxs(self.agg_fn_calls)
>         row_builder.set_slot_idxs(self.agg_order_by)
> ```

extraneous newline
___
*[`pixeltable/plan.py` line 196 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8gvRf74kHNL_x5KYYb:-O8gvRf74kHNL_x5KYYc:bdtl026) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L196)):*
> ```Python
>         for fn_call in self.window_fn_calls:
>             # window functions require ordering by the group_by/order_by clauses
>             gb, ob = fn_call.get_window_sort_exprs()
> ```

i suggest using more descriptive names than `gb` and `ob` - maybe `gb_sort_key_exprs` etc.?
___
*[`pixeltable/plan.py` line 525 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8nOX4r5c3aGGrO0eLv:-O8nOX4r5c3aGGrO0eLw:b-2mwtvv) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L525)):*
> ```Python
> 
>         if verify_agg:
>             ordering: Ordering = []
> ```

What's this doing? If it's a type checker thing, you shouldn't need the extraneous declaration (just annotate with `order: Ordering` the first time it's assigned)
___
*[`pixeltable/plan.py` line 533 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8nP-qh7w-xyIbP_tPL:-O8nP-qh7w-xyIbP_tPM:befuji8) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L533)):*
> ```Python
>             for fn_call in analyzer.agg_fn_calls:
>                 # agg functions with an ordering requirement are implicitly ascending
>                 ordering = [(e, None) for e in analyzer.group_by_clause] + [(e, True) for e in fn_call.get_agg_order_by()]
> ```

How would this work if I wanted to aggregate along a different ordering? e.g. I have an aggregator `my_agg` with an ordering requirement, and I do something like

```t.order_by(t.my_col, asc=False).select(my_agg(t.my_col))```

The code would seem to imply I'd get an "Incompatible ordering requirements", but it feels like this should be a valid pattern.

Rather than making aggregators with ordering requirements implicitly ascending, might we instead consider requiring an explicit order_by in order to use them? i.e., make it an error to use an ordered aggregator without a preceding order_by?
___
*[`pixeltable/plan.py` line 549 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8gwoWG3yfYiTvjsi6f:-O8gwoWG3yfYiTvjsi6g:b-xx2fgq) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L549)):*
> ```Python
>     def _determine_ordering(cls, analyzer: Analyzer) -> list[tuple[exprs.Expr, bool]]:
>         """Returns the exprs for the ORDER BY clause of the SqlScanNode"""
>         order_by_items: list[tuple[exprs.Expr, Optional[bool]]] = []
> ```

Is this not just a `list[Ordering]`?
___
*[`pixeltable/plan.py` line 710 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8gwy_54zMWhzCmXl-e:-O8gwy_54zMWhzCmXl-f:b-4qe8do) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L710)):*
> ```Python
>         sql_elements = analyzer.sql_elements
>         is_python_agg = (
>                 not sql_elements.contains(analyzer.agg_fn_calls) or not sql_elements.contains(analyzer.window_fn_calls)
> ```

extraneous indentation
___
*[`pixeltable/plan.py` line 735 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8nSuOSDoKjWC5KQnz2:-O8nSuOSDoKjWC5KQnz3:bhcu16a) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L735)):*
> ```Python
>         sql_scan_exprs = exprs.ExprSet(candidates)
>         # we don't want to materialize Literals via a Select
>         sql_scan_exprs -= exprs.ExprSet(e for e in sql_scan_exprs if isinstance(e, exprs.Literal))
> ```

Can this be folded into a single expression with the above?

`sql_scan_exprs = exprs.ExprSet(e for e in candidates if not isinstance(e, exprs.Literal))`
___
*[`pixeltable/plan.py` line 773 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8nV-Gi9L-0okf--he_:-O8nV-Gi9L-0okf--hea:btyshx8) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L773)):*
> ```Python
>                 agg_output = exprs.ExprSet(
>                     # explicit cast to avoid typechecking error
>                     cast(list[exprs.Expr], analyzer.grouping_exprs + analyzer.agg_fn_calls + analyzer.window_fn_calls))
> ```

If you want to avoid the typecast, I think this works:

```python
exprs.ExprSet(
    itertools.chain(analyzer.grouping_exprs, analyzer.agg_fn_calls, analyzer.window_fn_calls)
)
```
The issue (I think) isn't that it needs a cast, but that `list` is not covariant in Python. The cast just causes mypy to skip past the expression that has the type error.

The following also seems to work, though in this case I'm not sure why it works and yours doesn't:
```
agg_list = analyzer.grouping_exprs + analyzer.agg_fn_calls + analyzer.window_fn_calls
agg_output = exprs.ExprSet(agg_list)
```
___
*[`pixeltable/store.py` line 136 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8cKZoR7AXjiOdXXfge:-O8cKZoR7AXjiOdXXfgf:b-vs3crb) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/store.py#L136)):*
> ```Python
> 
>     def _move_tmp_media_files(
>             self, table_rows: list[Dict[str, Any]], media_cols: list[catalog.Column], v_min: int
> ```

Lowercase the `Dict` also (here and elsewhere - since you're already lowercasing `list` and `set` and `tuple` in this file)
___
*[`pixeltable/catalog/table_version.py` line 694 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8nX0MKCYCy_0sQU8mZ:-O8n [...]

2024-10-11 19:19 UTC, mkornacker reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/320)* status: 0 of 29 files reviewed, 25 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/plan.py` line 109 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8cIzn_BCv0IdMvs5E-:-O8rGcXU2QNCVUEXwZQw:b-dp1el7) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L109)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

The enclosing `bool` shouldn't be necessary here?
</blockquote></details>

I couldn't get typechecking to pass without it, but happy to do something else here.
___
*[`pixeltable/plan.py` line 132 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8cJpXWDlyJN-CATyOq:-O8woqKN-u-cO8WYx8Nl:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L132)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This might be cleaner:
```
if any(_is_agg_fn_call(e) for e in self.filter.subexprs(expr_class=exprs.FunctionCall))
```
</blockquote></details>

Done.
___
*[`pixeltable/plan.py` line 190 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8gv1OMCfEU99_UP_XA:-O8wozyn5EskVyOmjL5b:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L190)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

extraneous newline
</blockquote></details>

Done.
___
*[`pixeltable/plan.py` line 196 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8gvRf74kHNL_x5KYYb:-O8wp86R7vJB5UxeKPcP:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L196)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

i suggest using more descriptive names than `gb` and `ob` - maybe `gb_sort_key_exprs` etc.?
</blockquote></details>

Done.
___
*[`pixeltable/plan.py` line 525 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8nOX4r5c3aGGrO0eLv:-O8wpdd804jBNCD8TKvS:b-q4rpqw) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L525)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

What's this doing? If it's a type checker thing, you shouldn't need the extraneous declaration (just annotate with `order: Ordering` the first time it's assigned)
</blockquote></details>

I'm finding this more informative.
___
*[`pixeltable/plan.py` line 533 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8nP-qh7w-xyIbP_tPL:-O8wpP6qAnsQ1usn4QAc:bfrf84r) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L533)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

How would this work if I wanted to aggregate along a different ordering? e.g. I have an aggregator `my_agg` with an ordering requirement, and I do something like

```t.order_by(t.my_col, asc=False).select(my_agg(t.my_col))```

The code would seem to imply I'd get an "Incompatible ordering requirements", but it feels like this should be a valid pattern.

Rather than making aggregators with ordering requirements implicitly ascending, might we instead consider requiring an explicit order_by in order to use them? i.e., make it an error to use an ordered aggregator without a preceding order_by?
</blockquote></details>

You are right that this should be a valid pattern, but it's not supported at the moment. Implementing that requires more drastic changes (you need to generate entirely different plans that include reordering operators).
___
*[`pixeltable/plan.py` line 549 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8gwoWG3yfYiTvjsi6f:-O8wpsH5-KwpU89WJpZz:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L549)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Is this not just a `list[Ordering]`?
</blockquote></details>

Done.
___
*[`pixeltable/plan.py` line 710 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8gwy_54zMWhzCmXl-e:-O8wpz8E9BxCoIazNMws:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L710)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

extraneous indentation
</blockquote></details>

Done.
___
*[`pixeltable/plan.py` line 735 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8nSuOSDoKjWC5KQnz2:-O8wqHeVCLYKHFwDAVLy:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L735)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Can this be folded into a single expression with the above?

`sql_scan_exprs = exprs.ExprSet(e for e in candidates if not isinstance(e, exprs.Literal))`
</blockquote></details>

Done.
___
*[`pixeltable/plan.py` line 773 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8nV-Gi9L-0okf--he_:-O8wr72n9FK3JBKUqRIC:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L773)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

If you want to avoid the typecast, I think this works:

```python
exprs.ExprSet(
    itertools.chain(analyzer.grouping_exprs, analyzer.agg_fn_calls, analyzer.window_fn_calls)
)
```
The issue (I think) isn't that it needs a cast, but that `list` is not covariant in Python. The cast just causes mypy to skip past the expression that has the type error.

The following also seems to work, though in this case I'm not sure why it works and yours doesn't:
```
agg_list = analyzer.grouping_exprs + analyzer.agg_fn_calls + analyzer.window_fn_calls
agg_output = exprs.ExprSet(agg_list)
```
</blockquote></details>

Done.
___
*[`pixeltable/store.py` line 136 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8cKZoR7AXjiOdXXfge:-O8wrEJJ5fCtmlmyzz_t:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/store.py#L136)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Lowercase the `Dict` also (here and elsewhere - since you're already lowercasing `list` and `set` and `tuple` in this file)
</blockquote></details>

Done.
___
*[`pixeltable/exec/aggregation_node.py` line 82 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8nX_HoCjJ4vyx-4Mvv:-O8wso4g9gXqS9dXK3hl:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/exec/aggregation_node.py#L82)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I'm confused, `yield` will only ever be called once? Does that imply every aggregator will only ever emit a single output batch containing the entire query results? I think this needs an explanatory comment
</blockquote></details>

Done.
___
*[`pixeltable/exec/exec_node.py` line 51 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8nZPkIEBRi4I80xfyA:-O8wtA5gBRFuWj_DcsrI:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/exec/exec_node.py#L51)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

What are these comments?
</blockquote></details>

Done.
___
*[`pixeltable/exec/ [...]

2024-10-15 23:59 UTC, aaron-siegel requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/320)* status: 0 of 29 files reviewed, 24 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/plan.py` line 525 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8nOX4r5c3aGGrO0eLv:-O9HZ-brAW8NaKYXfG5N:b-et971k) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L525)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

I'm finding this more informative.
</blockquote></details>

I checked the style guides and it's actually ok to write:
```python
ordering: OrderByClause
```
if you know that `ordering` is going to be defined prior to use in all succeeding code paths. I think that's the way to go, assuming the type checker is ok with it (the assignment to `[]` that never gets used is what was bothering me)
___
*[`pixeltable/plan.py` line 533 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8nP-qh7w-xyIbP_tPL:-O9HZwcK8KS5a44QhUe0:b-b6gv8s) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L533)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

You are right that this should be a valid pattern, but it's not supported at the moment. Implementing that requires more drastic changes (you need to generate entirely different plans that include reordering operators).
</blockquote></details>

Add a JIRA ticket so we don't lose track of this desirable enhancement?
___
*[`pixeltable/exec/sql_node.py` line 21 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8n_73NBGAwrJGDti_a:-O9H_laE-nG50V4r2qq6:b-z8tmjy) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/exec/sql_node.py#L21)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Wait, I don't think that comment is correct? The exprs don't need to be identical, one just needs to be an initial segment of the other, right? And if they're unequal, the output clause (the one that's "compatible with" the others) needs to be the longer one. i.e., "compatible with" is not a symmetric relationship, but the comment implies it is.
___
*[`pixeltable/exec/sql_node.py` line 261 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8nbgoR1EyumSsBWMcL:-O9HaGhP6-ENd7GGqZI8:b79bttz) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/exec/sql_node.py#L261)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Added explanatory comment
</blockquote></details>

Per our conversation last week, I now understand that it's unsafe to do the conversion in SQL due to possible loss of precision. We should say that in the comment. I'd also argue for adding a test that specifically would overflow the SQL decimal-to-int conversion, just to guard against someone trying to "optimize" this in the future
___
*[`pixeltable/exprs/expr_dict.py` line 11 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8cLGGa8DbbUNdfmOw_:-O9HajXp3747_YkBKVQg:b-p9qeex) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/exprs/expr_dict.py#L11)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

I don't see this as heavyweight. It's only 55 lines, the code is easy to follow and self-contained, and this frees the caller from having to create ExprWrappers.
</blockquote></details>

well, over 100 lines if you include the custom `ExprSet`, but i don't feel that strongly about it.
___
*[`pixeltable/exprs/expr_set.py` line 70 at r5](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O9Hb7PV1EB_EVRMSLw8:-O9Hb7PV1EB_EVRMSLw9:bdl5lhs) ([raw file](https://github.com/pixeltable/pixeltable/blob/506aa22d615a301a5e307f78d8ceee349e2dc9ef/pixeltable/exprs/expr_set.py#L70)):*
> ```Python
>         return self.difference(other)
> 
> ExprSet = ExprSet[Expr]  # type: ignore
> ```

I did a double-take when I saw this. Why alter the meaning of `ExprSet`? Seems super confusing (is there any precedent for doing this?)
___
*[`pixeltable/functions/globals.py` line 31 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8ncucw0bpusywg9hvW:-O9HbPs25ZZIKKicEH6g:bcm37xb) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/functions/globals.py#L31)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Let's talk about that offline. It's not clear to me why that's particularly useful here.
</blockquote></details>

`# type: ignore` is generally undesirable, and it's an avoidable inconvenience for users defining aggregators. I don't think it'll be hard to fix.


<!-- Sent from Reviewable.io -->

2024-10-16 03:10 UTC, mkornacker reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/320)* status: 0 of 29 files reviewed, 24 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/plan.py` line 525 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8nOX4r5c3aGGrO0eLv:-O9IDuZx2aEs2F4idhV2:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L525)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I checked the style guides and it's actually ok to write:
```python
ordering: OrderByClause
```
if you know that `ordering` is going to be defined prior to use in all succeeding code paths. I think that's the way to go, assuming the type checker is ok with it (the assignment to `[]` that never gets used is what was bothering me)
</blockquote></details>

Done.
___
*[`pixeltable/plan.py` line 533 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8nP-qh7w-xyIbP_tPL:-O9IEenJ29QsFnLmpWqx:b-uarmjo) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/plan.py#L533)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Add a JIRA ticket so we don't lose track of this desirable enhancement?
</blockquote></details>

Done (309)
___
*[`pixeltable/exec/sql_node.py` line 21 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8n_73NBGAwrJGDti_a:-O9IF8EQ0ZP0ymgdTH9b:b6z7fx6) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/exec/sql_node.py#L21)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Wait, I don't think that comment is correct? The exprs don't need to be identical, one just needs to be an initial segment of the other, right? And if they're unequal, the output clause (the one that's "compatible with" the others) needs to be the longer one. i.e., "compatible with" is not a symmetric relationship, but the comment implies it is.
</blockquote></details>

Each item has an expr, and those exprs need to be identical.
___
*[`pixeltable/exec/sql_node.py` line 261 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8nbgoR1EyumSsBWMcL:-O9IGBQ0CYq4mFqT1hbk:bsnmhwl) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/exec/sql_node.py#L261)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Per our conversation last week, I now understand that it's unsafe to do the conversion in SQL due to possible loss of precision. We should say that in the comment. I'd also argue for adding a test that specifically would overflow the SQL decimal-to-int conversion, just to guard against someone trying to "optimize" this in the future
</blockquote></details>

I'm not sure how to induce that, and I would say that's follow-on work.

The comment for sum.to_sql() explains why it doesn't do a conversion.
___
*[`pixeltable/exprs/expr_set.py` line 70 at r5](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O9Hb7PV1EB_EVRMSLw8:-O9IIEedBNRF5mi5Vgvg:b-w0c3o4) ([raw file](https://github.com/pixeltable/pixeltable/blob/506aa22d615a301a5e307f78d8ceee349e2dc9ef/pixeltable/exprs/expr_set.py#L70)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I did a double-take when I saw this. Why alter the meaning of `ExprSet`? Seems super confusing (is there any precedent for doing this?)
</blockquote></details>

Doesn't appear to be necessary after all
___
*[`pixeltable/functions/globals.py` line 31 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8ncucw0bpusywg9hvW:-O9IILPt3-lWFo7ZDfOT:bn3cmuj) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/functions/globals.py#L31)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

`# type: ignore` is generally undesirable, and it's an avoidable inconvenience for users defining aggregators. I don't think it'll be hard to fix.
</blockquote></details>

I'll leave a todo


<!-- Sent from Reviewable.io -->

2024-10-16 05:16 UTC, aaron-siegel requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/320)* status: 0 of 29 files reviewed, 24 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/exec/sql_node.py` line 21 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8n_73NBGAwrJGDti_a:-O9Ik1rW9nrrlrjOM7OA:b-ytarw3) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/exec/sql_node.py#L21)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Each item has an expr, and those exprs need to be identical.
</blockquote></details>

Right, but the clauses don't need to be the same length, do they? The `result` can be strictly longer than some of the elements of `clauses`. And none of the clauses can be strictly longer than the `result`. So it's not a symmetric relationship. At least that's how I'm reading the code.


<!-- Sent from Reviewable.io -->

2024-10-16 15:07 UTC, mkornacker reviewed
> Dismissed @aaron-siegel from a discussion.
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/320)* status: 0 of 29 files reviewed, 23 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/exec/sql_node.py` line 21 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8n_73NBGAwrJGDti_a:-O9KrHVI4-Q7uyQi26Ds:bckkgvy) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/exec/sql_node.py#L21)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Right, but the clauses don't need to be the same length, do they? The `result` can be strictly longer than some of the elements of `clauses`. And none of the clauses can be strictly longer than the `result`. So it's not a symmetric relationship. At least that's how I'm reading the code.
</blockquote></details>

The relationship is symmetric. If ordering A is compatible with B, then B is also compatible with A.


<!-- Sent from Reviewable.io -->

2024-10-16 15:40 UTC, aaron-siegel reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/320)* status: 0 of 29 files reviewed, 22 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/exec/sql_node.py` line 21 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/320#-O8n_73NBGAwrJGDti_a:-O9KybPSCNnJMXBlpuzy:bkw0d3f) ([raw file](https://github.com/pixeltable/pixeltable/blob/1a888cc4a34a5be51ef15d48232403bab82eeada/pixeltable/exec/sql_node.py#L21)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

The relationship is symmetric. If ordering A is compatible with B, then B is also compatible with A.
</blockquote></details>

Ok yes, it still makes sense with that definition. Still, the lengths of the sequences may differ. Things would be clearer if that were called out in the comment. As currently written it's easy to interpret it as meaning the expr sequences must be the same length (which then becomes a point of confusion when reading the code).


<!-- Sent from Reviewable.io -->

2024-10-16 15:41 UTC, aaron-siegel approved these changes

2024-10-16 15:48 UTC, merged