PXT-290: Allow APIs to accept table/column handles
pixeltable/pixeltable pull request #371
Opened 2024-11-12 09:28 UTC by anushas

This commit allows the following APIs to accept table/column handles
as an alternative to the table/column name
- drop_embedding_index and drop_index APIs accept a column reference as an alternative to the column name.
- drop_column API accepts column handle as an alternative to the column name.
- drop_table API to accept a table handle as an alternative to the table name.

This commit also adds an assertion in the catalog.Table._drop 
and catalog.View._drop internal API to assert that the dependencies
are dropped before they are invoked.

Testing: added new tests or enhanced existing ones

2024-11-12 09:29 UTC, aaron-siegel commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pixeltable/pixeltable/371)
<!-- Reviewable:end -->

2024-11-12 22:50 UTC, aaron-siegel requested changes
Good progress!

We should make the similar change to `Table.add_embedding_index()` as well.

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/371#-:-OBXYgMH2238svy2jGXo:b-en85j)* status: 0 of 5 files reviewed, 16 unresolved discussions (waiting on @anushas)

___
*[`pixeltable/catalog/table.py` line 739 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXWESf958jX-PfTXSD:-OBXWESf958jX-PfTXSE:b-uzz3cv) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/pixeltable/catalog/table.py#L739)):*
> ```Python
>     def drop_embedding_index(
>             self, *,
>             column_name: Optional[Union[str, ColumnRef]] = None,
> ```

Slightly clearer to write `Union[str, ColumnRef, None]` instead of `Optional[Union[str, ColumnRef]]` (they have identical meanings)

Also change parameter name
___
*[`pixeltable/catalog/table.py` line 795 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXWZXa22LO6_mDQ49c:-OBXWZXa22LO6_mDQ49d:b-2qg936) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/pixeltable/catalog/table.py#L795)):*
> ```Python
>         self._drop_index(column_name=column_name, idx_name=idx_name)
> 
>     def _drop_index(
> ```

We don't need to generalize the internal APIs. I'd suggest it's better to keep the simpler pattern for the internal API, and do the necessary conversions in the public-facing wrapper.
___
*[`pixeltable/catalog/table.py` line 815 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXXSiP8Uq1UVS9R6DR:-OBXXSiP8Uq1UVS9R6DS:b-7cq68d) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/pixeltable/catalog/table.py#L815)):*
> ```Python
>             else:
>                 cname = column_name.col.name
>             col = self._tbl_version_path.get_column(cname, include_bases=True)
> ```

We're converting the column reference to a string, and then calling `get_column()` on the string. That's a bit roundabout; would it work to get the col directly? i.e., replace the preceding lines with something like this?

```python
if isinstance(column_name, str):
    col = self._tbl_version_path.get_column(column_name, include_bases=True)
else:
    col = column_name.col
```
___
*[`tests/test_table.py` line 393 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXY45C8kmGVKATaFNj:-OBXY45C8kmGVKATaFNk:bs1il3z) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/tests/test_table.py#L393)):*
> ```Python
>         pxt.drop_table(t)
>         with pytest.raises(excs.Error):
>             _ = pxt.get_table('test1')
> ```

add assertions for the error messages (i realize they're missing from `test_drop_table()`; maybe we can add them there while we're at it?)
___
*[`tests/test_table.py` line 446 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXYK1aDLwXZKxRlkgh:-OBXYK1aDLwXZKxRlkgi:b-o9626w) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/tests/test_table.py#L446)):*
> ```Python
>         assert 'v2' not in pxt.list_tables()
>         assert 'v4' not in pxt.list_tables()
>         pxt.drop_table('test_tbl', force=True)  # Drops everything else
> ```

Use the handle here as well?
___
*[`tests/test_table.py` line 449 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXYPjx86hpCbprWOwG:-OBXYPjx86hpCbprWOwH:b5jd0zx) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/tests/test_table.py#L449)):*
> ```Python
>         assert len(pxt.list_tables()) == 0
> 
>     def test_drop_column_via_handle(self, reset_db) -> None:
> ```

Move this adjacent to `test_drop_column()` in the code, for clarity
___
*[`tests/test_table.py` line 451 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXYV34-dITL_QLFM8k:-OBXYV34-dITL_QLFM8l:brkiqe0) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/tests/test_table.py#L451)):*
> ```Python
>     def test_drop_column_via_handle(self, reset_db) -> None:
>         t = pxt.create_table('test1', {'c1': pxt.String, 'c2': pxt.String})
>         t.insert([{'c1':'a1', 'c2':'b1'}, {'c1':'a2', 'c2':'b2'}])
> ```

Python style: dictionary entries use a space after the colon
___
*[`tests/test_table.py` line 456 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXYbsB0FGcS8OduVOa:-OBXYbsB0FGcS8OduVOb:b-mr5w0s) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/tests/test_table.py#L456)):*
> ```Python
>             t.drop_column('c3')
>         assert 'c2' in t.columns
>         t.drop_column('c2')
> ```

use the handle here?
___
*[`pixeltable/globals.py` line 303 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXVfGG9UhhrrY27BVo:-OBXVfGG9UhhrrY27BVp:bkwx3h3) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/pixeltable/globals.py#L303)):*
> ```Python
> 
>     Args:
>         path: Path to the [`Table`][pixeltable.Table].
> ```

Update docstring
___
*[`pixeltable/catalog/table.py` line 299 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBWodkg2l8KiSYNFy0z:-OBWodkg2l8KiSYNFy1-:b-42iz9p) ([raw file](https://github.com/pixeltable/pixeltable/blob/31c875c1e0cd65e191661f4ea4e6772131b03bb1/pixeltable/catalog/table.py#L299)):*
> ```Python
>         # verify all dependents are deleted by now
>         for dep in cat.tbl_dependents[self._id]:
>             dep._check_is_dropped()
> ```

Wait, `_check_is_dropped()` throws an exception if the dependent HAS been dropped. That's the opposite of what we want, right?
___
*[`pixeltable/catalog/table.py` line 542 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBWn9nE21Up-JZZVIuy:-OBWn9nE21Up-JZZVIuz:b-nfmjqv) ([raw file](https://github.com/pixeltable/pixeltable/blob/31c875c1e0cd65e191661f4ea4e6772131b03bb1/pixeltable/catalog/table.py#L542)):*
> ```Python
>             column_names.add(col.name)
> 
>     def drop_column(self, name: Union[str, Column]) -> None:
> ```

Change the parameter name (to `col`?)
___
*[`pixeltable/catalog/table.py` line 556 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBWnSH_7_sQE07ITGu-:-OBWnSH_7_sQE07ITGu0:b-4ji6ls) ([raw file](https://github.com/pixeltable/pixeltable/blob/31c875c1e0cd65e191661f4ea4e6772131b03bb1/pixeltable/catalog/table.py#L556)):*
> ```Python
>             >>> tbl = pxt.get_table('my_table')
>             ... tbl.drop_column('col')
>             OR
> ```

same comment as above re: docstring formatting
___
*[`tests/test_index.py` line 165 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXXhAP6BV1kVeM5dE3:-OBXXhAP6BV1kVeM5dE4:b-upgesu) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/tests/test_index.py#L165)):*
> ```Python
>         assert 'duplicate index name' in str(exc_info.value).lower()
> 
>         with pytest.raises(pxt.Error):
> ```

check exception contents with an assertion on error msg (here and below)
___
*[`pixeltable/globals.py` line 250 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBWlsDm62AU3klmDidM:-OBWlsDm62AU3klmDidN:bdng3qb) ([raw file](https://github.com/pixeltable/pixeltable/blob/31c875c1e0cd65e191661f4ea4e6772131b03bb1/pixeltable/globals.py#L250)):*
> ```Python
> 
> 
> def drop_table(path: Union[str,catalog.Table], force: bool = False, ignore_errors: bool = False) -> None:
> ```

code style: space after a comma in type arguments (`Union[str, catalog.Table]`)

the parameter name should be changed to something other than `path`; maybe `tbl`
___
*[`pixeltable/globals.py` line 264 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBWmHiv57zu6SpCMvX5:-OBWmHiv57zu6SpCMvX6:bjvh2e5) ([raw file](https://github.com/pixeltable/pixeltable/bl [...]

2024-11-14 02:46 UTC, anushas reviewed
Thanks for your comments! Refreshed the PR with the following changes:
- Changed `Table.add_embedding_index()` API to allow a column reference
- Addressed all the other review comments
- Fixed a bug found while testing where a column reference of a table could be passed to another table's APIs.
 - Added _check_is_dropped() to Table.show() to throw a more graceful error when show is used on a table handle after it is dropped. Without that, show() errors out late when connecting to the underlying store/database and exposes unnecessary table details.

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/371#-:-OBcYLN33eMpClXhsJYP:b7vtx77)* status: 0 of 5 files reviewed, 16 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/globals.py` line 250 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBWlsDm62AU3klmDidM:-OBarum79RBQKnwk0Sj9:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/31c875c1e0cd65e191661f4ea4e6772131b03bb1/pixeltable/globals.py#L250)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

code style: space after a comma in type arguments (`Union[str, catalog.Table]`)

the parameter name should be changed to something other than `path`; maybe `tbl`
</blockquote></details>

Done.
___
*[`pixeltable/globals.py` line 264 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBWmHiv57zu6SpCMvX5:-OBasd836qnfBrFW7KQO:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/31c875c1e0cd65e191661f4ea4e6772131b03bb1/pixeltable/globals.py#L264)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Code blocks delineated by `>>>` and `...` in docstrings should be valid python code. I'd suggest something like this:

```
Examples:
    Drop a table by name:

    >>> pxt.drop_table('my_table')

    Drop a table given a [`Table`][pixeltable.Table] object:

    >>> t = pxt.get_table('my_table')
    ... pxt.drop_table(t)
```
</blockquote></details>

Done.
___
*[`pixeltable/globals.py` line 303 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXVfGG9UhhrrY27BVo:-OBarwMh2lUeN8rvWk3A:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/pixeltable/globals.py#L303)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Update docstring
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 299 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBWodkg2l8KiSYNFy0z:-OBau2KOCzXypcJEoXeU:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/31c875c1e0cd65e191661f4ea4e6772131b03bb1/pixeltable/catalog/table.py#L299)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Wait, `_check_is_dropped()` throws an exception if the dependent HAS been dropped. That's the opposite of what we want, right?
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 542 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBWn9nE21Up-JZZVIuy:-OBauMBO6TGKgfAZ-_m7:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/31c875c1e0cd65e191661f4ea4e6772131b03bb1/pixeltable/catalog/table.py#L542)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Change the parameter name (to `col`?)
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 556 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBWnSH_7_sQE07ITGu-:-OBaurpL7dHVxUmMMpNy:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/31c875c1e0cd65e191661f4ea4e6772131b03bb1/pixeltable/catalog/table.py#L556)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

same comment as above re: docstring formatting
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 739 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXWESf958jX-PfTXSD:-OBassLH8PQYgcEPVSrv:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/pixeltable/catalog/table.py#L739)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Slightly clearer to write `Union[str, ColumnRef, None]` instead of `Optional[Union[str, ColumnRef]]` (they have identical meanings)

Also change parameter name
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 795 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXWZXa22LO6_mDQ49c:-OBc-SuJCOaKTRq8ABwL:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/pixeltable/catalog/table.py#L795)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

We don't need to generalize the internal APIs. I'd suggest it's better to keep the simpler pattern for the internal API, and do the necessary conversions in the public-facing wrapper.
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 815 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXXSiP8Uq1UVS9R6DR:-OBc-ZHp8Twk4e3xORMc:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/pixeltable/catalog/table.py#L815)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

We're converting the column reference to a string, and then calling `get_column()` on the string. That's a bit roundabout; would it work to get the col directly? i.e., replace the preceding lines with something like this?

```python
if isinstance(column_name, str):
    col = self._tbl_version_path.get_column(column_name, include_bases=True)
else:
    col = column_name.col
```
</blockquote></details>

Done.
___
*[`pixeltable/catalog/view.py` line 199 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXXWbrETPbulItJ8x6:-OBc-cOd4WELIYFOHdqe:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/pixeltable/catalog/view.py#L199)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

missing method call `()`; without it this is just a no-op. same comment as above though regarding `_check_is_dropped()`.
</blockquote></details>

Done.
___
*[`tests/test_index.py` line 165 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXXhAP6BV1kVeM5dE3:-OBcG5cc53qloRlzZo_G:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/tests/test_index.py#L165)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

check exception contents with an assertion on error msg (here and below)
</blockquote></details>

Done.
___
*[`tests/test_table.py` line 393 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXY45C8kmGVKATaFNj:-OBcStjl6NEKoWWuDgcZ:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/tests/test_table.py#L393)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

add assertions for the error messages (i realize they're missing from `test_drop_table()`; maybe we can add them there while we're at it?)
</blockquote></details>

Done.
___
*[`tests/test_table.py` line 446 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXYK1aDLwXZKxRlkgh:-OBcP43z20sKU86SA57e:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/tests/test_table.py#L446)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Use the handle here as well?
</blockquote></details>

Done.
___
*[`tests/test_table.py` line 449 at r3](https://r [...]

2024-11-14 18:52 UTC, aaron-siegel requested changes
Great! Almost done. Mostly style comments below.

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/371#-:-OBg0Ag1-OleocNt41IN:b-qk3jvb)* status: 0 of 5 files reviewed, 12 unresolved discussions (waiting on @anushas)

___
*[`pixeltable/globals.py` line 250 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBWlsDm62AU3klmDidM:-OBfwW7Q-47r1fhDhpiW:b-6hrda6) ([raw file](https://github.com/pixeltable/pixeltable/blob/31c875c1e0cd65e191661f4ea4e6772131b03bb1/pixeltable/globals.py#L250)):*
<details><summary><i>Previously, anushas wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`table_name_or_obj` is a bit of a mouthful; I prefer just `tbl`. `@mkornacker` any preference here?
___
*[`pixeltable/globals.py` line 303 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXVfGG9UhhrrY27BVo:-OBfwh3-5MLspEShBzIy:bco4l98) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/pixeltable/globals.py#L303)):*
<details><summary><i>Previously, anushas wrote…</i></summary><blockquote>

Done.
</blockquote></details>

how about "name or [`Table`][pixeltable.Table]" object of the table to be dropped?
___
*[`pixeltable/catalog/table.py` line 542 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBWn9nE21Up-JZZVIuy:-OBfye6z25tksL_dnLrU:bcaljkb) ([raw file](https://github.com/pixeltable/pixeltable/blob/31c875c1e0cd65e191661f4ea4e6772131b03bb1/pixeltable/catalog/table.py#L542)):*
<details><summary><i>Previously, anushas wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Again, I prefer `col`, but I don't feel super strongly about it
___
*[`pixeltable/catalog/table.py` line 306 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBfxJ1e0wtAtmPd2UyI:-OBfxJ1e0wtAtmPd2UyJ:b-6zp9ko) ([raw file](https://github.com/pixeltable/pixeltable/blob/811d0d75203dedef9993318bc6d3753ac3f203f9/pixeltable/catalog/table.py#L306)):*
> ```Python
>         # verify all dependents are deleted by now
>         for dep in cat.tbl_dependents[self._id]:
>             assert dep._is_dropped == True
> ```

`assert dep._is_dropped`

As a general style note, expressions of the form `bool_predicate == True` (or `bool_predicate == False`) can usually be shortened
___
*[`pixeltable/catalog/table.py` line 607 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBfxWpA3LBF7whHQN64:-OBfxWpA3LBF7whHQN65:bv41re9) ([raw file](https://github.com/pixeltable/pixeltable/blob/811d0d75203dedef9993318bc6d3753ac3f203f9/pixeltable/catalog/table.py#L607)):*
> ```Python
>             column_names.add(col.name)
> 
>     def _check_column_str(self, column_name : str, include_bases : bool = False) -> None:
> ```

Python style: no space before the colon in type hints (`column_name: str`, not `column_name : str`)

Python style: private class methods should begin with a double underscore (`__check_column_str`, not `_check_column_str`). We haven't always observed this in the code base, but we're gradually moving towards this standard convention. (A single underscore designates a protected method)

Can the function name be made more specific?
___
*[`pixeltable/catalog/table.py` line 616 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBfytyc7ifE6uEEHSke:-OBfytyc7ifE6uEEHSkf:bf2fuwg) ([raw file](https://github.com/pixeltable/pixeltable/blob/811d0d75203dedef9993318bc6d3753ac3f203f9/pixeltable/catalog/table.py#L616)):*
> ```Python
>             tbl_cols = self._tbl_version_path.columns()
>         else:
>             tbl_cols = list(self._tbl_version.cols_by_name.values())
> ```

it shouldn't be necessary to instantiate a list here.
___
*[`pixeltable/catalog/table.py` line 630 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBfzP8UCDEWUty9E-Mo:-OBfzP8UCDEWUty9E-Mp:b-dlxfrf) ([raw file](https://github.com/pixeltable/pixeltable/blob/811d0d75203dedef9993318bc6d3753ac3f203f9/pixeltable/catalog/table.py#L630)):*
> ```Python
> 
>         Examples:
>             Drop the column `col` from the table `my_table` using column name:
> ```

"by column name" (to be consistent with the docstring for `add_embedding_index`; of the two, I like "by" better)
___
*[`pixeltable/catalog/table.py` line 876 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBg-FTFAESMMl8x5C8m:-OBg-FTFAESMMl8x5C8n:b-de9c6m) ([raw file](https://github.com/pixeltable/pixeltable/blob/811d0d75203dedef9993318bc6d3753ac3f203f9/pixeltable/catalog/table.py#L876)):*
> ```Python
>             raise excs.Error('Cannot drop an index from a snapshot')
>         self._check_is_dropped()
>         if (col is None) == (idx_name is None):
> ```

This check could be replaced with an assertion now (as the validation has moved into the user-facing method)
___
*[`pixeltable/globals.py` line 314 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBfx-cS2YlibgF5uyOe:-OBfx-cS2YlibgF5uyOf:b-a1n1q8) ([raw file](https://github.com/pixeltable/pixeltable/blob/811d0d75203dedef9993318bc6d3753ac3f203f9/pixeltable/globals.py#L314)):*
> ```Python
>         >>> pxt.drop_table('my_table')
> 
>         Drop a table by object
> ```

"Drop a table by reference"?

Also put a : at the end of these sentences
___
*[`pixeltable/globals.py` line 315 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBfx5sqCN13Vzyyxh00:-OBfx5sqCN13Vzyyxh01:b-dteovf) ([raw file](https://github.com/pixeltable/pixeltable/blob/811d0d75203dedef9993318bc6d3753ac3f203f9/pixeltable/globals.py#L315)):*
> ```Python
> 
>         Drop a table by object
>         >>> t = pxt.get_handle('my_table')
> ```

`pxt.get_table` (there is no `get_handle`)


<!-- Sent from Reviewable.io -->

2024-11-14 23:55 UTC, anushas reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/371)* status: 0 of 5 files reviewed, 12 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/globals.py` line 250 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBWlsDm62AU3klmDidM:-OBgoVJ5AIuG2E5W_0Yy:b-4nkiek) ([raw file](https://github.com/pixeltable/pixeltable/blob/31c875c1e0cd65e191661f4ea4e6772131b03bb1/pixeltable/globals.py#L250)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

`table_name_or_obj` is a bit of a mouthful; I prefer just `tbl`. `@mkornacker` any preference here?
</blockquote></details>

tbl is the name we use later for the object variable. but i have named it table. hope that works.
___
*[`pixeltable/globals.py` line 303 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXVfGG9UhhrrY27BVo:-OBgojaC8wVLbRK1hYKm:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/pixeltable/globals.py#L303)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

how about "name or [`Table`][pixeltable.Table]" object of the table to be dropped?
</blockquote></details>

Done.
___
*[`pixeltable/globals.py` line 314 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBfx-cS2YlibgF5uyOe:-OBgpKbP-x4qDH7B9a_s:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/811d0d75203dedef9993318bc6d3753ac3f203f9/pixeltable/globals.py#L314)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

"Drop a table by reference"?

Also put a : at the end of these sentences
</blockquote></details>

Done.
___
*[`pixeltable/globals.py` line 315 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBfx5sqCN13Vzyyxh00:-OBgpM_BDKwNjOvW8Fwi:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/811d0d75203dedef9993318bc6d3753ac3f203f9/pixeltable/globals.py#L315)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

`pxt.get_table` (there is no `get_handle`)
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 542 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBWn9nE21Up-JZZVIuy:-OBgKrcr9YOzd721AgWn:b-7dqg6l) ([raw file](https://github.com/pixeltable/pixeltable/blob/31c875c1e0cd65e191661f4ea4e6772131b03bb1/pixeltable/catalog/table.py#L542)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Again, I prefer `col`, but I don't feel super strongly about it
</blockquote></details>

col is variable we use in the body to represent the final Column object. but i made all the Union[str, ColumnRef] parameters consistent to use the same name - column. hope that works.
___
*[`pixeltable/catalog/table.py` line 306 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBfxJ1e0wtAtmPd2UyI:-OBgHTsA0Rz_1ZVHOELR:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/811d0d75203dedef9993318bc6d3753ac3f203f9/pixeltable/catalog/table.py#L306)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

`assert dep._is_dropped`

As a general style note, expressions of the form `bool_predicate == True` (or `bool_predicate == False`) can usually be shortened
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 607 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBfxWpA3LBF7whHQN64:-OBgJF_k7iWtEYdrRafR:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/811d0d75203dedef9993318bc6d3753ac3f203f9/pixeltable/catalog/table.py#L607)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Python style: no space before the colon in type hints (`column_name: str`, not `column_name : str`)

Python style: private class methods should begin with a double underscore (`__check_column_str`, not `_check_column_str`). We haven't always observed this in the code base, but we're gradually moving towards this standard convention. (A single underscore designates a protected method)

Can the function name be made more specific?
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 616 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBfytyc7ifE6uEEHSke:-OBgJGwL3bNGVKJBRCgp:bbok4a8) ([raw file](https://github.com/pixeltable/pixeltable/blob/811d0d75203dedef9993318bc6d3753ac3f203f9/pixeltable/catalog/table.py#L616)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

it shouldn't be necessary to instantiate a list here.
</blockquote></details>

this was needed to keep 'make typecheck' clean. otherwise complains about the tbl_cols assigned differnt types; type in if block - list[Column] - vs the type in else block -- dict_list[Column]
-
as discussed at lunch, removed the list and declared tbl_cols as Iterable.
___
*[`pixeltable/catalog/table.py` line 630 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBfzP8UCDEWUty9E-Mo:-OBgLXTI14YwW1xI67Tj:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/811d0d75203dedef9993318bc6d3753ac3f203f9/pixeltable/catalog/table.py#L630)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

"by column name" (to be consistent with the docstring for `add_embedding_index`; of the two, I like "by" better)
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 876 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBg-FTFAESMMl8x5C8m:-OBgLxWf0HBd2S41hlq6:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/811d0d75203dedef9993318bc6d3753ac3f203f9/pixeltable/catalog/table.py#L876)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This check could be replaced with an assertion now (as the validation has moved into the user-facing method)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-15 17:56 UTC, aaron-siegel approved these changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/371)* status: 0 of 5 files reviewed, 12 unresolved discussions (waiting on @anushas)

___
*[`pixeltable/globals.py` line 250 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBWlsDm62AU3klmDidM:-OBkvvlSB37tmDut8yat:bt3cx68) ([raw file](https://github.com/pixeltable/pixeltable/blob/31c875c1e0cd65e191661f4ea4e6772131b03bb1/pixeltable/globals.py#L250)):*
<details><summary><i>Previously, anushas wrote…</i></summary><blockquote>

tbl is the name we use later for the object variable. but i have named it table. hope that works.
</blockquote></details>

I mean, you're free to change the name we use later for the object variable. We should focus first on choosing the right names for the user-facing parts of the code, then adapt the internal names to accommodate that. Choosing a user-facing variable name based on some existing purely internal name is really putting the cart before the horse.

I don't have a strong preference on `table` vs. `tbl` but let's be sure we're choosing the name for the right reasons.
___
*[`pixeltable/globals.py` line 303 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBXVfGG9UhhrrY27BVo:-OBkxPio0LYUPt9r62go:b-1oozu5) ([raw file](https://github.com/pixeltable/pixeltable/blob/2b4c4241f50672babb03b5b2301e009066e1b8b6/pixeltable/globals.py#L303)):*
<details><summary><i>Previously, anushas wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I didn't mean for the quote marks to actually show up in the docstring (that'll look really weird). I now realize that my quotes were confusingly positioned and probably misleading :)
___
*[`pixeltable/catalog/table.py` line 542 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBWn9nE21Up-JZZVIuy:-OBkxuAS1WBWdUaxLB4j:b-3r8o54) ([raw file](https://github.com/pixeltable/pixeltable/blob/31c875c1e0cd65e191661f4ea4e6772131b03bb1/pixeltable/catalog/table.py#L542)):*
<details><summary><i>Previously, anushas wrote…</i></summary><blockquote>

col is variable we use in the body to represent the final Column object. but i made all the Union[str, ColumnRef] parameters consistent to use the same name - column. hope that works.
</blockquote></details>

Same comment as above. We shouldn't be basing our user-facing decisions on existing patterns in the internal code.
___
*[`pixeltable/catalog/table.py` line 616 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBfytyc7ifE6uEEHSke:-OBkxk36A1D_p3zmlpOR:b-7kd2pn) ([raw file](https://github.com/pixeltable/pixeltable/blob/811d0d75203dedef9993318bc6d3753ac3f203f9/pixeltable/catalog/table.py#L616)):*
<details><summary><i>Previously, anushas wrote…</i></summary><blockquote>

this was needed to keep 'make typecheck' clean. otherwise complains about the tbl_cols assigned differnt types; type in if block - list[Column] - vs the type in else block -- dict_list[Column]
-
as discussed at lunch, removed the list and declared tbl_cols as Iterable.
</blockquote></details>

Declare it as an `Iterable[Column]` to be specific.


<!-- Sent from Reviewable.io -->

2024-11-15 21:15 UTC, mkornacker requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/371)* status: 0 of 5 files reviewed, 20 unresolved discussions (waiting on @aaron-siegel and @anushas)

___
*[`pixeltable/globals.py` line 303 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBlUsa1EX05FdX6U__l:-OBlUsa1EX05FdX6U__m:bwzsmdg) ([raw file](https://github.com/pixeltable/pixeltable/blob/83841f731986d4f73fac078d3935c3593f231c95/pixeltable/globals.py#L303)):*
> ```Python
> 
>     Args:
>         table: name or [`Table`][pixeltable.Table] object of the table to be dropped.
> ```

No need for explicit links here, this is automatically generated. 

Take a look at this:
https://pixeltable.github.io/pixeltable/api/io/#pixeltable.io.create_label_studio_project

Also, a str argument must be the fully-qualified table path, not the name.

Elsewhere we refer to instances of Table as 'table handle'. See docstring for get_table().
___
*[`pixeltable/globals.py` line 311 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBlVxcbEJsD4b1nErG8:-OBlVxcbEJsD4b1nErG9:bb7mg8a) ([raw file](https://github.com/pixeltable/pixeltable/blob/83841f731986d4f73fac078d3935c3593f231c95/pixeltable/globals.py#L311)):*
> ```Python
> 
>     Examples:
>         Drop a table by name:
> ```

path
___
*[`pixeltable/globals.py` line 314 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBlW-yADUgYgokHL9bb:-OBlW-yADUgYgokHL9bc:b-pz9wnn) ([raw file](https://github.com/pixeltable/pixeltable/blob/83841f731986d4f73fac078d3935c3593f231c95/pixeltable/globals.py#L314)):*
> ```Python
>         >>> pxt.drop_table('my_table')
> 
>         Drop a table by reference:
> ```

handle
___
*[`pixeltable/catalog/table.py` line 612 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBlePaODUrwtfT2ku8T:-OBlePaODUrwtfT2ku8U:b-349ja6) ([raw file](https://github.com/pixeltable/pixeltable/blob/83841f731986d4f73fac078d3935c3593f231c95/pixeltable/catalog/table.py#L612)):*
> ```Python
>             raise excs.Error(f'Column {column_name!r} unknown')
> 
>     def __check_column_ref_exists(self, col_ref: ColumnRef, include_bases: bool = False) -> None:
> ```

Best to implement that in TableVersionPath as has_column_ref() (it already has a get_column() and has_column() and is the natural place for this kind of traversal)
___
*[`pixeltable/catalog/table.py` line 742 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBlWeCp-YwH2HdBUpKK:-OBlWeCp-YwH2HdBUpKL:b-knoue3) ([raw file](https://github.com/pixeltable/pixeltable/blob/83841f731986d4f73fac078d3935c3593f231c95/pixeltable/catalog/table.py#L742)):*
> ```Python
>             ...     metric='ip'
>             ... )
> ```

"Alternatively:"
___
*[`pixeltable/catalog/table.py` line 754 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBlWmNmDVF_EcmCkAN7:-OBlWmNmDVF_EcmCkAN8:b-t1ykx0) ([raw file](https://github.com/pixeltable/pixeltable/blob/83841f731986d4f73fac078d3935c3593f231c95/pixeltable/catalog/table.py#L754)):*
> ```Python
>             raise excs.Error('Cannot add an index to a snapshot')
>         self._check_is_dropped()
>         col: Column = None
> ```

remove '= None'
___
*[`pixeltable/catalog/table.py` line 782 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBleyVtBHEtaP0ZTsVX:-OBleyVtBHEtaP0ZTsVY:bbsikb8) ([raw file](https://github.com/pixeltable/pixeltable/blob/83841f731986d4f73fac078d3935c3593f231c95/pixeltable/catalog/table.py#L782)):*
> ```Python
> 
>         Args:
>             column: The name or reference of the column from which to drop the index.
> ```

name of or reference to
___
*[`pixeltable/catalog/table.py` line 831 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBlf9d56oCUuf3eaL2o:-OBlf9d56oCUuf3eaL2p:b-2gtafo) ([raw file](https://github.com/pixeltable/pixeltable/blob/83841f731986d4f73fac078d3935c3593f231c95/pixeltable/catalog/table.py#L831)):*
> ```Python
> 
>         Args:
>             column: The name or handle of the column from which to drop the index.
> ```

rephrase to match drop_embedding_index()


<!-- Sent from Reviewable.io -->

2024-11-15 21:51 UTC, aaron-siegel reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/371)* status: 0 of 5 files reviewed, 19 unresolved discussions (waiting on @anushas and @mkornacker)

___
*[`pixeltable/globals.py` line 311 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBlVxcbEJsD4b1nErG8:-OBlmzDGEm9_qdFZ7N_B:b-8rdf63) ([raw file](https://github.com/pixeltable/pixeltable/blob/83841f731986d4f73fac078d3935c3593f231c95/pixeltable/globals.py#L311)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

path
</blockquote></details>

I think "name" is clearer. I've always found the terminology "table path" slightly confusing and I suspect users will too. "path" mirrors filesystem terminology but most users probably aren't thinking about their table hierarchy as a filesystem. I'd suggest we standardize on "name" with the understanding that it means "qualified name".
___
*[`pixeltable/globals.py` line 314 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBlW-yADUgYgokHL9bb:-OBlmwzvCtcmdvphlAOj:br2gx7a) ([raw file](https://github.com/pixeltable/pixeltable/blob/83841f731986d4f73fac078d3935c3593f231c95/pixeltable/globals.py#L314)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

handle
</blockquote></details>

I actually prefer "reference" but don't feel super strongly about it.


<!-- Sent from Reviewable.io -->

2024-11-15 23:38 UTC, anushas reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/371)* status: 0 of 6 files reviewed, 19 unresolved discussions (waiting on @aaron-siegel and @mkornacker)

___
*[`pixeltable/globals.py` line 303 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBlUsa1EX05FdX6U__l:-OBm40O21B5-vK7Sb-fY:bs7wumx) ([raw file](https://github.com/pixeltable/pixeltable/blob/83841f731986d4f73fac078d3935c3593f231c95/pixeltable/globals.py#L303)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

No need for explicit links here, this is automatically generated. 

Take a look at this:
https://pixeltable.github.io/pixeltable/api/io/#pixeltable.io.create_label_studio_project

Also, a str argument must be the fully-qualified table path, not the name.

Elsewhere we refer to instances of Table as 'table handle'. See docstring for get_table().
</blockquote></details>

Done. 
___
*[`pixeltable/globals.py` line 311 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBlVxcbEJsD4b1nErG8:-OBm4OHiEPWR9bZtRyeQ:b-r52ipj) ([raw file](https://github.com/pixeltable/pixeltable/blob/83841f731986d4f73fac078d3935c3593f231c95/pixeltable/globals.py#L311)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I think "name" is clearer. I've always found the terminology "table path" slightly confusing and I suspect users will too. "path" mirrors filesystem terminology but most users probably aren't thinking about their table hierarchy as a filesystem. I'd suggest we standardize on "name" with the understanding that it means "qualified name".
</blockquote></details>

I changed it to use fully qualified name. Hope that works.
___
*[`pixeltable/globals.py` line 314 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBlW-yADUgYgokHL9bb:-OBm4_v32A0NMzTnMaUb:b-u3ge67) ([raw file](https://github.com/pixeltable/pixeltable/blob/83841f731986d4f73fac078d3935c3593f231c95/pixeltable/globals.py#L314)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I actually prefer "reference" but don't feel super strongly about it.
</blockquote></details>

I use it as handle to keep it symmetric with existing documentation
___
*[`pixeltable/catalog/table.py` line 612 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBlePaODUrwtfT2ku8T:-OBmBCPUB0e1fwYE0X4_:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/83841f731986d4f73fac078d3935c3593f231c95/pixeltable/catalog/table.py#L612)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Best to implement that in TableVersionPath as has_column_ref() (it already has a get_column() and has_column() and is the natural place for this kind of traversal)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-15 23:40 UTC, anushas commented
@mkornacker @aaron-siegel - refreshed the PR addressing the latest comments. Can you PTAL?

2024-11-16 02:32 UTC, anushas reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/371)* status: 0 of 6 files reviewed, 19 unresolved discussions (waiting on @aaron-siegel and @mkornacker)

___
*[`pixeltable/catalog/table.py` line 742 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBlWeCp-YwH2HdBUpKK:-OBmo05939RTP9iVEFx9:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/83841f731986d4f73fac078d3935c3593f231c95/pixeltable/catalog/table.py#L742)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

"Alternatively:"
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 754 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBlWmNmDVF_EcmCkAN7:-OBmo0q67Q5O_iD0U0Zj:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/83841f731986d4f73fac078d3935c3593f231c95/pixeltable/catalog/table.py#L754)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

remove '= None'
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 782 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBleyVtBHEtaP0ZTsVX:-OBmo1kdCBmwryiX4K2P:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/83841f731986d4f73fac078d3935c3593f231c95/pixeltable/catalog/table.py#L782)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

name of or reference to
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 831 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/371#-OBlf9d56oCUuf3eaL2o:-OBmo3OTDvW85W4daVol:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/83841f731986d4f73fac078d3935c3593f231c95/pixeltable/catalog/table.py#L831)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

rephrase to match drop_embedding_index()
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-16 20:19 UTC, mkornacker approved these changes

2024-11-16 20:19 UTC, mkornacker commented on pixeltable/catalog/table_version_path.py
> +    def has_column_ref(self, col_ref: exprs.ColumnRef, include_bases: bool = True) -> bool:
Remove; caller can simply call has_column() directly.

2024-11-16 20:19 UTC, mkornacker commented on pixeltable/catalog/table.py
> +        exists = self._tbl_version_path.has_column_ref(col_ref, include_bases)
simply call has_column(col_ref.col, ...)

2024-11-18 07:28 UTC, merged