PXT-288 - Provide pxt.io.export_parquet API
pixeltable/pixeltable pull request #374
Opened 2024-11-16 02:13 UTC by anushas

This commit provided an API to export the data in pixeltable as a parquet file. It renamed and used an already existing function, and added some tests. The tests reveal some unexpected behavior - particularly the datetime/timestamp column type is not working as expected. Fix for that is pending.

2024-11-16 02:13 UTC, aaron-siegel commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pixeltable/pixeltable/374)
<!-- Reviewable:end -->

2024-11-20 21:22 UTC, aaron-siegel requested changes
Don't we need to do something on the read path (import_parquet) to address the case where we get a datetime without a time zone?

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/374#-:-OCAOt4R5WQKTF3kjma8:b-fq6fvf)* status: 0 of 6 files reviewed, 16 unresolved discussions (waiting on @anushas and @mkornacker)

___
*[`pixeltable/io/parquet.py` line 44 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAR-ue9Ru5cuKlY7CW:-OCAR-ue9Ru5cuKlY7CX:blx66m9) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/pixeltable/io/parquet.py#L44)):*
> ```Python
> 
> def export_parquet(
>             df: pxt.DataFrame,
> ```

We should probably accept a table or dataframe here

`table_or_df: Union[pxt.Table, pxt.DataFrame]`
___
*[`pixeltable/io/parquet.py` line 199 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCANt6wDDN_y71JrmhF:-OCANt6wDDN_y71JrmhG:b-xwxjii) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/pixeltable/io/parquet.py#L199)):*
> ```Python
>             for batch in fragment.to_batches():
>                 dict_batch = list(iter_tuples(batch))
>                 print("DEBUG_A import dict_batch: ", dict_batch)
> ```

Remove debugging code
___
*[`pixeltable/utils/arrow.py` line 16 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAPAjb6wnEkJunkF75:-OCAPAjb6wnEkJunkF76:b8yqhxt) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/pixeltable/utils/arrow.py#L16)):*
> ```Python
> _pa_to_pt: dict[pa.DataType, ts.ColumnType] = {
>     pa.string(): ts.StringType(nullable=True),
>     pa.timestamp('us'): ts.TimestampType(nullable=True),
> ```

Remove this line, since it's no longer necessary or particularly meaningful (we have separate handling for timestamps in to_pixeltable_type now)
___
*[`pixeltable/utils/arrow.py` line 27 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAPNsL75EfsnrmTe-o:-OCAPNsMDr72HDmExInl:b-744itl) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/pixeltable/utils/arrow.py#L27)):*
> ```Python
> }
> 
> _pt_to_pa: dict[type[ts.ColumnType], pa.DataType] = {
> ```

It just occurred to me that a dictionary isn't going to work in all cases here. The pixeltable type could be something like `Image[(300, 300)]` with type parameters. That's a legacy issue that we don't necessarily need to fix in this PR, but maybe we should create a ticket for it.
___
*[`pixeltable/utils/arrow.py` line 29 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAO6xv5Lfa7AJyO8-X:-OCAO6xv5Lfa7AJyO8-Y:b439ycv) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/pixeltable/utils/arrow.py#L29)):*
> ```Python
> _pt_to_pa: dict[type[ts.ColumnType], pa.DataType] = {
>     ts.StringType: pa.string(),
>     ts.TimestampType: pa.timestamp('us', tz=_tz_def),  # postgres timestamp is microseconds
> ```

I'd suggest using UTC here rather than the system default (that is, we stick to the convention that any persisted/externalized timestamps should be given in UTC).
___
*[`tests/io/test_parquet.py` line 4 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAQfSfDuDHIqUnnXgW:-OCAQfSfDuDHIqUnnXgX:b-s7z4aq) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/tests/io/test_parquet.py#L4)):*
> ```Python
> import pathlib
> import pytest
> import pyarrow as pa
> ```

any imports of optional dependencies need to be inlined in the relevant tests or they will break CI. (we have a CI instance that runs on required dependencies only in order to validate a minimal pixeltable install)
___
*[`tests/io/test_parquet.py` line 47 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAPmpF9x_z8nX5VVk9:-OCAPmpF9x_z8nX5VVkA:br3ecq5) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/tests/io/test_parquet.py#L47)):*
> ```Python
>                     assert val == arrow_tup[col]
> 
>     def _helper_rand_timezone(self) -> datetime.timezone:
> ```

I'm not sure it's wise to have nondeterministic test parameters - it might complicate reproducing test failures. I suggest hard-coding some timezone (I've been using `America/Anchorage` in various places in the tests, for no particular reason other than it's unlikely to be the system timezone in any of our test environments)
___
*[`tests/io/test_parquet.py` line 49 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAQALv6yA52lHUPOxi:-OCAQALv6yA52lHUPOxj:b-k280ax) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/tests/io/test_parquet.py#L49)):*
> ```Python
>     def _helper_rand_timezone(self) -> datetime.timezone:
>         import random
>         import pytz
> ```

pytz is deprecated in Python 3.9+. Use zoneinfo instead (there are some examples in `test_timestamp.py`)
___
*[`tests/io/test_parquet.py` line 53 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAPgXW6znxwOvMazxL:-OCAPgXW6znxwOvMazxM:bqdlozz) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/tests/io/test_parquet.py#L53)):*
> ```Python
> 
>     def test_export_parquet_simple(self, reset_db, tmp_path: pathlib.Path) -> None:
>         # RESOLVE: check if it is possible to do this at class level for all tests?
> ```

it's not
___
*[`tests/io/test_parquet.py` line 61 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAQaSI-bkYmOUbz3U9:-OCAQaSI-bkYmOUbz3UA:b-snku69) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/tests/io/test_parquet.py#L61)):*
> ```Python
>                     {'c1': 2, 'c2': 'row2', 'c3': datetime.datetime(2012, 2, 1, 12, 0, 0, 25, tz)}])
> 
>         from pixeltable.env import Env
> ```

move to top of file
___
*[`tests/io/test_parquet.py` line 67 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAQtxX95Em3CPr_yvf:-OCAQtxX95Em3CPr_yvg:brt0hsf) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/tests/io/test_parquet.py#L67)):*
> ```Python
> 
>         export_file1 = tmp_path / 'test1.pq'
>         pxt.io.export_parquet(t._df(), export_file1)
> ```

use `t` or `t.select()` in place of `t._df()` (best to stick to the public APIs when there's a choice).
___
*[`tests/io/test_parquet.py` line 72 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAROlm6Omuf-kdRe1F:-OCAROlm6Omuf-kdRe1G:byaiky4) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/tests/io/test_parquet.py#L72)):*
> ```Python
>         assert ptest1.num_rows == 2
>         assert ptest1.column_names == ['c1', 'c2', 'c3']
>         assert ptest1.schema.types == [pa.int64(), pa.string(), pa.timestamp('us',tz=tz_default)]
> ```

style: missing space after `'us',`
___
*[`tests/io/test_parquet.py` line 79 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCARhci27TXm0hVtR3N:-OCARhci27TXm0hVtR3O:bbngf41) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/tests/io/test_parquet.py#L79)):*
> ```Python
> 
>         export_file2 = tmp_path / 'test2.pq'
>         pxt.io.export_parquet(t._df().select(t.c1, t.c2), export_file2)
> ```

`t._df().select(...)` is redundant, just do `t.select(...)`
___
*[`tests/io/test_parquet.py` line 88 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCARkZn7z9uhMQFhqhV:-OCARkZn7z9uhMQFhqhW:b-idr8l1) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/tests/io/test_parquet.py#L88)):*
> ```Python
> 
>         export_file3 = tmp_path / 'test3.pq'
>         pxt.io.export_parquet(t._df().select().where(t.c1 == 1), export_file3)
> [...]

2024-11-22 21:17 UTC, anushas reviewed
As discussed yesterday, left this one as is to match the insert behavior.

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/374#-:-OCKia-E6Zf2XrXeAjEB:b-qixl3n)* status: 0 of 6 files reviewed, 16 unresolved discussions (waiting on @aaron-siegel and @mkornacker)

___
*[`pixeltable/io/parquet.py` line 44 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAR-ue9Ru5cuKlY7CW:-OCKNIJc0nZdjsf4Yba-:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/pixeltable/io/parquet.py#L44)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

We should probably accept a table or dataframe here

`table_or_df: Union[pxt.Table, pxt.DataFrame]`
</blockquote></details>

Done.
___
*[`pixeltable/io/parquet.py` line 199 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCANt6wDDN_y71JrmhF:-OCKNQyM72btQ7VG_--W:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/pixeltable/io/parquet.py#L199)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Remove debugging code
</blockquote></details>

Done.
___
*[`pixeltable/utils/arrow.py` line 16 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAPAjb6wnEkJunkF75:-OCKNshTESwgSkQ554Ok:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/pixeltable/utils/arrow.py#L16)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Remove this line, since it's no longer necessary or particularly meaningful (we have separate handling for timestamps in to_pixeltable_type now)
</blockquote></details>

Done.
___
*[`pixeltable/utils/arrow.py` line 27 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAPNsL75EfsnrmTe-o:-OCKPK6v4IzdBDmxLImu:bho9r61) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/pixeltable/utils/arrow.py#L27)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

It just occurred to me that a dictionary isn't going to work in all cases here. The pixeltable type could be something like `Image[(300, 300)]` with type parameters. That's a legacy issue that we don't necessarily need to fix in this PR, but maybe we should create a ticket for it.
</blockquote></details>

PXT-359. Done.
___
*[`pixeltable/utils/arrow.py` line 29 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAO6xv5Lfa7AJyO8-X:-OCKUKTh4VvHnc2yCplZ:bwbhi5t) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/pixeltable/utils/arrow.py#L29)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I'd suggest using UTC here rather than the system default (that is, we stick to the convention that any persisted/externalized timestamps should be given in UTC).
</blockquote></details>

I wanted to avoid having to convert the individual row values from default to utc. But I see why you prefer the consistency. Done.
___
*[`tests/io/test_parquet.py` line 4 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAQfSfDuDHIqUnnXgW:-OCKUqUS0c5vyxVGqeCM:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/tests/io/test_parquet.py#L4)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

any imports of optional dependencies need to be inlined in the relevant tests or they will break CI. (we have a CI instance that runs on required dependencies only in order to validate a minimal pixeltable install)
</blockquote></details>

Done.
___
*[`tests/io/test_parquet.py` line 47 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAPmpF9x_z8nX5VVk9:-OCKUrg7COq8o73Fcf6C:b44rem4) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/tests/io/test_parquet.py#L47)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I'm not sure it's wise to have nondeterministic test parameters - it might complicate reproducing test failures. I suggest hard-coding some timezone (I've been using `America/Anchorage` in various places in the tests, for no particular reason other than it's unlikely to be the system timezone in any of our test environments)
</blockquote></details>

I understand, for a logical test. But think this one is a simple input and we print what we pick, so it should be okay, But I changed it to fixed timezeone to match other tests. It wouldn't work with ZoneInfo anyways. Done.
___
*[`tests/io/test_parquet.py` line 49 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAQALv6yA52lHUPOxi:-OCKipaL-HqcMJLogZ9f:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/tests/io/test_parquet.py#L49)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

pytz is deprecated in Python 3.9+. Use zoneinfo instead (there are some examples in `test_timestamp.py`)
</blockquote></details>

Done.
___
*[`tests/io/test_parquet.py` line 53 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAPgXW6znxwOvMazxL:-OCKVwew-jn_ywYcAB7I:bodyaei) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/tests/io/test_parquet.py#L53)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

it's not
</blockquote></details>

Done. Removed the RESOLVE.
___
*[`tests/io/test_parquet.py` line 61 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAQaSI-bkYmOUbz3U9:-OCKW5A_5bMIJXC3IWxD:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/tests/io/test_parquet.py#L61)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

move to top of file
</blockquote></details>

Done.
___
*[`tests/io/test_parquet.py` line 67 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAQtxX95Em3CPr_yvf:-OCKWOKj2zGdVY004lJC:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/tests/io/test_parquet.py#L67)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

use `t` or `t.select()` in place of `t._df()` (best to stick to the public APIs when there's a choice).
</blockquote></details>

Done.
___
*[`tests/io/test_parquet.py` line 72 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCAROlm6Omuf-kdRe1F:-OCKWemv6qyfr1qD68j4:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/tests/io/test_parquet.py#L72)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

style: missing space after `'us',`
</blockquote></details>

Done.
___
*[`tests/io/test_parquet.py` line 79 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCARhci27TXm0hVtR3N:-OCKWfLqCrFxU0IGX3Yo:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/tests/io/test_parquet.py#L79)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

`t._df().select(...)` is redundant, just do `t.select(...)`
</blockquote></details>

Done.
___
*[`tests/io/test_parquet.py` line 88 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/374#-OCARkZn7z9uhMQFhqhV:-OCKWiFYE53RYzWuQQK0:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/75c15ac8db773cb13c6fe9e8a92deb293f3d54b3/tests/io/test_parquet.py#L88)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><bloc [...]

2024-11-22 21:37 UTC, aaron-siegel approved these changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/374)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @mkornacker)



<!-- Sent from Reviewable.io -->

2024-11-22 22:27 UTC, merged