PXT-345 Add .txt support for DocumentType
pixeltable/pixeltable pull request #389
Opened 2024-11-22 08:53 UTC by anushas

This commit allows a .txt file to be added as a DocumentType and supports DocumentSplitter for it.

Testing: enhanced existing testcases and added a .txt specific testcase.

2024-11-22 08:53 UTC, aaron-siegel commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pixeltable/pixeltable/389)
<!-- Reviewable:end -->

2024-11-26 18:15 UTC, mkornacker requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/389)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @anushas)

___
*[`pixeltable/utils/documents.py` line 94 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/389#-OC_vULz4iqE352cRUJt:-OC_vUM-5MLIt_g1IY51:b-1ff09) ([raw file](https://github.com/pixeltable/pixeltable/blob/633fa9360aaf6801a4c072c0683e66d58cb5b195/pixeltable/utils/documents.py#L94)):*
> ```Python
>         return None
> 
> def get_txt_handle(path: str) -> Optional[str]:
> ```

Misleading naming: this is simply the text itself, not a handle to it.
___
*[`tests/test_document.py` line 245 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/389#-OC_z0Oy1yp32Ok_EmyZ:-OC_z0Oy1yp32Ok_Emy_:b77q9z6) ([raw file](https://github.com/pixeltable/pixeltable/blob/633fa9360aaf6801a4c072c0683e66d58cb5b195/tests/test_document.py#L245)):*
> ```Python
>             pxt.drop_table('chunks')
> 
>     def test_doc_splitter_txt(self, reset_db) -> None:
> ```

There is already a test_doc_splitter, why special-case text docs?
___
*[`tests/test_document.py` line 258 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/389#-OC_yynI9YiktQFOSj5x:-OC_yynI9YiktQFOSj5y:b-i6dwwm) ([raw file](https://github.com/pixeltable/pixeltable/blob/633fa9360aaf6801a4c072c0683e66d58cb5b195/tests/test_document.py#L258)):*
> ```Python
> 
>         chunks_t = pxt.create_view(
>                 'chunks', doc_t,
> ```

formatting
___
*[`pixeltable/iterators/document.py` line 157 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/389#-OC_uo6SEnaHBtQd-SBv:-OC_uo6TAd-bzQe7FUA4:b-l6mwxj) ([raw file](https://github.com/pixeltable/pixeltable/blob/633fa9360aaf6801a4c072c0683e66d58cb5b195/pixeltable/iterators/document.py#L157)):*
> ```Python
>             assert self._doc_handle.txt_doc is not None
>             self._sections = self._txt_sections()
>             #self._sections = self._pdf_sections()
> ```

remove
___
*[`pixeltable/iterators/document.py` line 397 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/389#-OC_w3WU7hW_0sq-LG0w:-OC_w3WU7hW_0sq-LG0x:b-bv3x1k) ([raw file](https://github.com/pixeltable/pixeltable/blob/633fa9360aaf6801a4c072c0683e66d58cb5b195/pixeltable/iterators/document.py#L397)):*
> ```Python
> 
>     def _txt_sections(self) -> Iterator[DocumentSection]:
>         """Create DocumentSections for text files."""
> ```

This could be more informative (you're creating a single section for the entire document).

Also add todo to add paragraphs.


<!-- Sent from Reviewable.io -->

2024-11-26 20:29 UTC, anushas reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/389)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/iterators/document.py` line 157 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/389#-OC_uo6SEnaHBtQd-SBv:-OCe4ESB9qhDg2XsOToN:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/633fa9360aaf6801a4c072c0683e66d58cb5b195/pixeltable/iterators/document.py#L157)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`pixeltable/iterators/document.py` line 397 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/389#-OC_w3WU7hW_0sq-LG0w:-OCe4H7EELnkCXn7_BHy:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/633fa9360aaf6801a4c072c0683e66d58cb5b195/pixeltable/iterators/document.py#L397)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

This could be more informative (you're creating a single section for the entire document).

Also add todo to add paragraphs.
</blockquote></details>

Done.
___
*[`pixeltable/utils/documents.py` line 94 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/389#-OC_vULz4iqE352cRUJt:-OCe4amUAuWB03dQfZ4x:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/633fa9360aaf6801a4c072c0683e66d58cb5b195/pixeltable/utils/documents.py#L94)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Misleading naming: this is simply the text itself, not a handle to it.
</blockquote></details>

Done.
___
*[`tests/test_document.py` line 245 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/389#-OC_z0Oy1yp32Ok_EmyZ:-OCe7PtH61TCsXTg4CXQ:b1ngz4g) ([raw file](https://github.com/pixeltable/pixeltable/blob/633fa9360aaf6801a4c072c0683e66d58cb5b195/tests/test_document.py#L245)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

There is already a test_doc_splitter, why special-case text docs?
</blockquote></details>

as discussed, added comments.
___
*[`tests/test_document.py` line 258 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/389#-OC_yynI9YiktQFOSj5x:-OCe9UC64i-mtRfjc6hn:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/633fa9360aaf6801a4c072c0683e66d58cb5b195/tests/test_document.py#L258)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

formatting
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-26 21:01 UTC, mkornacker requested changes

2024-11-26 21:01 UTC, mkornacker commented on tests/test_document.py
> +                            'chunks', doc_t,
The formatting is still off. Did you run pylint?

See elsewhere in the code base for examples of multi-line function calls. Indentation is generally 4 spaces.

2024-11-26 22:32 UTC, anushas reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/389)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @mkornacker)



<!-- Sent from Reviewable.io -->

2024-11-26 22:32 UTC, anushas commented on tests/test_document.py
> +                            'chunks', doc_t,
Hmm. I was keeping 4 spaces from where  the function call brace is at in previous line. But looks like we do 4 spaces from the beginning of newline. Adjusted. PTAL. 
<!-- Reviewable comment -OCeaATyCd3QY6fwgyhA:bx7ec0d -->
<!-- Sent from Reviewable.io -->

2024-11-27 00:42 UTC, mkornacker requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/389)* status: 0 of 6 files reviewed, 8 unresolved discussions (waiting on @anushas)

___
*[`tests/test_document.py` line 245 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/389#-OCf36Mz8XJ3R2Qbw91h:-OCf36Mz8XJ3R2Qbw91i:b-5xdeyo) ([raw file](https://github.com/pixeltable/pixeltable/blob/0c6bb50e5739c9f9ec4ac948519599e310a3fc4a/tests/test_document.py#L245)):*
> ```Python
>             pxt.drop_table('chunks')
> 
>     # test_doc_splitter above already tests the behaviour
> ```

Function comments go in the docstring.
___
*[`tests/test_document.py` line 252 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/389#-OCf3DSkAU1HwVTUZbuh:-OCf3DSlET61vWG1qj2i:b3kre) ([raw file](https://github.com/pixeltable/pixeltable/blob/0c6bb50e5739c9f9ec4ac948519599e310a3fc4a/tests/test_document.py#L252)):*
> ```Python
>         skip_test_if_not_installed('spacy')
> 
>         # DocumentSplitter does not support XML
> ```

?


<!-- Sent from Reviewable.io -->

2024-11-27 01:24 UTC, anushas reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/389)* status: 0 of 6 files reviewed, 8 unresolved discussions (waiting on @mkornacker)

___
*[`tests/test_document.py` line 245 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/389#-OCf36Mz8XJ3R2Qbw91h:-OCfCjXb6rrFuXLU11A_:bxc0hzo) ([raw file](https://github.com/pixeltable/pixeltable/blob/0c6bb50e5739c9f9ec4ac948519599e310a3fc4a/tests/test_document.py#L245)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Function comments go in the docstring.
</blockquote></details>

done. sorry, thought that was only for external api doctoring. 
___
*[`tests/test_document.py` line 252 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/389#-OCf3DSkAU1HwVTUZbuh:-OCfCUqA8Te40Uhq4TJE:buzzxp3) ([raw file](https://github.com/pixeltable/pixeltable/blob/0c6bb50e5739c9f9ec4ac948519599e310a3fc4a/tests/test_document.py#L252)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

?
</blockquote></details>

sorry, copy pasted from the other test. removed.


<!-- Sent from Reviewable.io -->

2024-11-27 04:09 UTC, mkornacker approved these changes

2024-11-27 04:09 UTC, mkornacker commented on tests/test_document.py
> +        ''' Test the DocumentSplitter with a .txt file
Docstrings start and end with """ (not ''').

2024-11-27 17:55 UTC, anushas commented on tests/test_document.py
> +        ''' Test the DocumentSplitter with a .txt file
wow. Corrected.
<!-- Reviewable comment -OCikQju0_A-Me-bLchW:b-n7sorz -->
<!-- Sent from Reviewable.io -->

2024-11-27 19:03 UTC, merged