[WiP] Tool calling
pixeltable/pixeltable pull request #416
Opened 2024-12-20 22:54 UTC by aaron-siegel

Adds a method `pxt.tools()` that allows a collection of UDFs to be cast as LLM tools. The general workflow is:

```python
tools = pxt.tools(stock_price)
t.add_computed_column(response=chat_completions(model='gpt-4o-mini', messages=messages, tools=tools)
t.add_computed_column(tool_calls=tools.invoke(t.response))
```

The output of `pxt.tools()` is an instance of a Pydantic model `pxt.func.Tools` that can be invoked or converted to a dict.

This PR also upgrades `FunctionCall` to allow Pydantic model instances as parameters. More generally, a Pydantic model instance can be cast as a Literal, which will cause it to be converted to a dict.

2024-12-20 22:54 UTC, aaron-siegel commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pixeltable/pixeltable/416)
<!-- Reviewable:end -->

2024-12-22 23:53 UTC, mkornacker reviewed
Quick comments:
- I'm not onboard with using Pydantic here, as discussed earlier
- I'm not onboard with using the OpenAI format here, as discussed earlier.

2024-12-23 19:12 UTC, aaron-siegel commented
@mkornacker Please tell me what your suggested alternatives are.

2025-01-04 04:21 UTC, mkornacker requested changes
It doesn't look like this generalizes to non-OpenAI tool dicts and function invocations. We should probably do a whiteboard discussion.

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/416#-:-OFjXZU0Eeg_x2j9tpFJ:bjur1vs)* status: 0 of 14 files reviewed, 6 unresolved discussions (waiting on @aaron-siegel)

___
*[`tests/functions/test_openai.py` line 99 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OFhWqp8-rXWMAYtIUQm:-OFhWqp8-rXWMAYtIUQn:b5fbkpy) ([raw file](https://github.com/pixeltable/pixeltable/blob/c283c1ff3dc4c511e9c9c11b533ca520dcb1cd1b/tests/functions/test_openai.py#L99)):*
> ```Python
>         assert "\\'messages\\' must contain the word \\'json\\'" in str(exc_info.value)
> 
>     def test_tool_invocations(self, reset_db) -> None:
> ```

Also add a test_anthropic.test_tool_invocation().
___
*[`tests/functions/test_openai.py` line 118 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OFhXM5ZE-K6cl1xX4tc:-OFhXM5ZE-K6cl1xX4td:b-lxjlnb) ([raw file](https://github.com/pixeltable/pixeltable/blob/c283c1ff3dc4c511e9c9c11b533ca520dcb1cd1b/tests/functions/test_openai.py#L118)):*
> ```Python
>         res = t.select(t.output, t.tool_calls).head()
> 
>         # First promprt results in tool invocation + no message output
> ```

prompt
___
*[`tests/functions/test_openai.py` line 231 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OFhWdN6-QzqqzxE3GQV:-OFhWdN6-QzqqzxE3GQW:ba0qrdc) ([raw file](https://github.com/pixeltable/pixeltable/blob/c283c1ff3dc4c511e9c9c11b533ca520dcb1cd1b/tests/functions/test_openai.py#L231)):*
> ```Python
> 
> @pxt.udf
> def stock_price(ticker: str) -> Optional[float]:
> ```

Move to top (easier to read that way)?
___
*[`pixeltable/func/tools.py` line 32 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OFjXJFs7kOF5eF8cLJt:-OFjXJFs7kOF5eF8cLJu:b-dpjrw2) ([raw file](https://github.com/pixeltable/pixeltable/blob/c283c1ff3dc4c511e9c9c11b533ca520dcb1cd1b/pixeltable/func/tools.py#L32)):*
> ```Python
>     def ser_model(self) -> dict[str, Any]:
>         return {
>             'type': 'function',
> ```

This won't work for Anthropic.
___
*[`pixeltable/func/tools.py` line 105 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OFiA3B85YhIeIwaE0zk:-OFiA3B85YhIeIwaE0zl:bmjyrsa) ([raw file](https://github.com/pixeltable/pixeltable/blob/c283c1ff3dc4c511e9c9c11b533ca520dcb1cd1b/pixeltable/func/tools.py#L105)):*
> ```Python
> def _extract_arg(tool_calls: list[dict], func_name: str, param_name: str) -> Any:
>     for tool_call in tool_calls:
>         if tool_call['function']['name'] == func_name:
> ```

This doesn't work for Anthropic tool use.

Here is a sample response:
{
  "stop\_reason": "tool\_use",
  "tool\_use": {
    "name": "get\_stock\_price",
    "input": {
      "company": "General Motors"
    }
  }
}
___
*[`pixeltable/functions/openai.py` line 195 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OFjVXFY81gMHg6ZrAcv:-OFjVXFY81gMHg6ZrAcw:b-z2w84t) ([raw file](https://github.com/pixeltable/pixeltable/blob/c283c1ff3dc4c511e9c9c11b533ca520dcb1cd1b/pixeltable/functions/openai.py#L195)):*
> ```Python
>     temperature: Optional[float] = None,
>     top_p: Optional[float] = None,
>     tools: Optional[Tools] = None,
> ```

Why is this necessary? And how does this work, given that the completions.create() call requires a dict?


<!-- Sent from Reviewable.io -->

2025-01-07 19:57 UTC, aaron-siegel reviewed
Anthropic is working now.

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/416#-:-OG1IWMHBE40jatUMb9I:b549j1g)* status: 0 of 17 files reviewed, 6 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/func/tools.py` line 32 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OFjXJFs7kOF5eF8cLJt:-OG1IQ0kB9OdIVI-83HC:bw9v1i2) ([raw file](https://github.com/pixeltable/pixeltable/blob/c283c1ff3dc4c511e9c9c11b533ca520dcb1cd1b/pixeltable/func/tools.py#L32)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

This won't work for Anthropic.
</blockquote></details>

It does - see the latest PR update.
___
*[`pixeltable/func/tools.py` line 105 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OFiA3B85YhIeIwaE0zk:-OG1IKcg-sun0vZX5zLH:bcr4zrw) ([raw file](https://github.com/pixeltable/pixeltable/blob/c283c1ff3dc4c511e9c9c11b533ca520dcb1cd1b/pixeltable/func/tools.py#L105)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

This doesn't work for Anthropic tool use.

Here is a sample response:
{
  "stop\_reason": "tool\_use",
  "tool\_use": {
    "name": "get\_stock\_price",
    "input": {
      "company": "General Motors"
    }
  }
}
</blockquote></details>

It does now. I had to do some refactoring (per discussion w/ Jacob on slack a few weeks ago)
___
*[`pixeltable/functions/openai.py` line 195 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OFjVXFY81gMHg6ZrAcv:-OG14a6v16Y_t430qa8B:b7fezij) ([raw file](https://github.com/pixeltable/pixeltable/blob/c283c1ff3dc4c511e9c9c11b533ca520dcb1cd1b/pixeltable/functions/openai.py#L195)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Why is this necessary? And how does this work, given that the completions.create() call requires a dict?
</blockquote></details>

Oops, this was just an incorrect type hint. Always surprises me when these things slip by mypy. Fixed.
___
*[`tests/functions/test_openai.py` line 99 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OFhWqp8-rXWMAYtIUQm:-OG1IIkN0hl2_w23gTHx:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/c283c1ff3dc4c511e9c9c11b533ca520dcb1cd1b/tests/functions/test_openai.py#L99)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Also add a test_anthropic.test_tool_invocation().
</blockquote></details>

Done.
___
*[`tests/functions/test_openai.py` line 118 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OFhXM5ZE-K6cl1xX4tc:-OG1IDJA-luqjZvbITUi:b-886gsx) ([raw file](https://github.com/pixeltable/pixeltable/blob/c283c1ff3dc4c511e9c9c11b533ca520dcb1cd1b/tests/functions/test_openai.py#L118)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

prompt
</blockquote></details>

Fixed
___
*[`tests/functions/test_openai.py` line 231 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OFhWdN6-QzqqzxE3GQV:-OG1IEpK4CKza4FLO9aK:b-5r829o) ([raw file](https://github.com/pixeltable/pixeltable/blob/c283c1ff3dc4c511e9c9c11b533ca520dcb1cd1b/tests/functions/test_openai.py#L231)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Move to top (easier to read that way)?
</blockquote></details>

I moved it to tests/utils.py so it can be shared w/ Anthropic etc.


<!-- Sent from Reviewable.io -->

2025-01-08 22:55 UTC, mkornacker reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/416)* status: 0 of 27 files reviewed, 13 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/type_system.py` line 343 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OG70Tm836JinFk8rv8W:-OG70Tm836JinFk8rv8X:b-d1vvnt) ([raw file](https://github.com/pixeltable/pixeltable/blob/0a810576179ca48487678b2a9fc7798d2fe70688/pixeltable/type_system.py#L343)):*
> ```Python
>                 if t is PIL.Image.Image:
>                     return ImageType(nullable=nullable_default)
>                 if issubclass(t, Sequence) or issubclass(t, Mapping) or issubclass(t, pydantic.BaseModel):
> ```

Where is this being used?
___
*[`pixeltable/exprs/function_call.py` line 202 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OG712RCEhuvEDLWcz7t:-OG712RCEhuvEDLWcz7u:by3kccc) ([raw file](https://github.com/pixeltable/pixeltable/blob/0a810576179ca48487678b2a9fc7798d2fe70688/pixeltable/exprs/function_call.py#L202)):*
> ```Python
> 
>             if not isinstance(arg, Expr):
>                 if arg is not None:
> ```

Combine w/ preceding if
___
*[`pixeltable/func/aggregate_function.py` line 142 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OG71C9n3rv4H4nQc4Oe:-OG71C9n3rv4H4nQc4Of:bqqovla) ([raw file](https://github.com/pixeltable/pixeltable/blob/0a810576179ca48487678b2a9fc7798d2fe70688/pixeltable/func/aggregate_function.py#L142)):*
> ```Python
>         return self
> 
>     def _docstring(self) -> Optional[str]:
> ```

I'm just remembering: we need to prevent agg functions from being used as tools, those can't be invoked like regular functions.
___
*[`pixeltable/func/tools.py` line 18 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OG71z1P4G2Q9EtPGvgu:-OG71z1P4G2Q9EtPGvgv:b-lcfmhc) ([raw file](https://github.com/pixeltable/pixeltable/blob/0a810576179ca48487678b2a9fc7798d2fe70688/pixeltable/func/tools.py#L18)):*
> ```Python
> # The Tool and Tools classes are containers that hold Pixeltable UDFs and related metadata, so that they can be
> # realized as LLM tools. They are implemented as Pydantic models in order to provide a canonical way of converting
> # to JSON, via the Pydantic `model_serializer` interface. In this way, they can be passed directly as UDF
> ```

That's not really the reason. The real reason is that they can be converted to json-serializable dicts via a standard interface, even though they contain Function instances, which themselves aren't json-serializable. You should also explain why we're  not using a dataclass here.

Speaking  of converting to dict, wasn't that supposed to happen in Expr.from_object()?
___
*[`pixeltable/func/tools.py` line 39 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OG73ipd0JuMJyOt1JRk:-OG73ipd0JuMJyOt1JRl:b4wpvmy) ([raw file](https://github.com/pixeltable/pixeltable/blob/0a810576179ca48487678b2a9fc7798d2fe70688/pixeltable/func/tools.py#L39)):*
> ```Python
>             'name': self.name or self.fn.name,
>             'description': self.description or self.fn._docstring(),
>             'parameters': {
> ```

Why don't we serialize these like we do in Signature.as_dict(). That way, we record everything that's available to  us. The vendor-specific udf can  do the translation.
___
*[`pixeltable/func/tools.py` line 71 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OG75oxd1rDPRvlptxCN:-OG75oxd1rDPRvlptxCO:b-aay5u) ([raw file](https://github.com/pixeltable/pixeltable/blob/0a810576179ca48487678b2a9fc7798d2fe70688/pixeltable/func/tools.py#L71)):*
> ```Python
>         if param.col_type.is_bool_type():
>             return _extract_bool_tool_arg(tool_calls, func_name=func_name, param_name=param.name)
>         assert False
> ```

datetime? Seems pretty important.
___
*[`pixeltable/globals.py` line 715 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OG7-pe1051CcECeEbYp:-OG7-pe1051CcECeEbYq:bs5mms3) ([raw file](https://github.com/pixeltable/pixeltable/blob/0a810576179ca48487678b2a9fc7798d2fe70688/pixeltable/globals.py#L715)):*
> ```Python
>         >>> tools = pxt.tools(stock_price, weather_quote)
> 
>         Create a tools instance, some of whose UDFs that have customized metadata:
> ```

"UDFs have"


<!-- Sent from Reviewable.io -->

2025-01-09 03:53 UTC, aaron-siegel reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/416)* status: 0 of 27 files reviewed, 13 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/globals.py` line 715 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OG7-pe1051CcECeEbYp:-OG85PfB3Dv49E8xxD33:b-886gsx) ([raw file](https://github.com/pixeltable/pixeltable/blob/0a810576179ca48487678b2a9fc7798d2fe70688/pixeltable/globals.py#L715)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

"UDFs have"
</blockquote></details>

Fixed
___
*[`pixeltable/type_system.py` line 343 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OG70Tm836JinFk8rv8W:-OG85hzf9tdEdRyXAReN:b410c1u) ([raw file](https://github.com/pixeltable/pixeltable/blob/0a810576179ca48487678b2a9fc7798d2fe70688/pixeltable/type_system.py#L343)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Where is this being used?
</blockquote></details>

it's called by `from_object`
___
*[`pixeltable/exprs/function_call.py` line 202 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OG712RCEhuvEDLWcz7t:-OG86zupDGGYkAX99XdU:b-yp1kzs) ([raw file](https://github.com/pixeltable/pixeltable/blob/0a810576179ca48487678b2a9fc7798d2fe70688/pixeltable/exprs/function_call.py#L202)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Combine w/ preceding if
</blockquote></details>

that doesn't work b/c the `continue` is part of the outer `if`
___
*[`pixeltable/func/aggregate_function.py` line 142 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OG71C9n3rv4H4nQc4Oe:-OG88uu1CB4szsapSkg2:b-o52677) ([raw file](https://github.com/pixeltable/pixeltable/blob/0a810576179ca48487678b2a9fc7798d2fe70688/pixeltable/func/aggregate_function.py#L142)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

I'm just remembering: we need to prevent agg functions from being used as tools, those can't be invoked like regular functions.
</blockquote></details>

Good call. I added a check for this.
___
*[`pixeltable/func/tools.py` line 18 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OG71z1P4G2Q9EtPGvgu:-OG7Ifme8a5PJy3D-WeD:bheub9y) ([raw file](https://github.com/pixeltable/pixeltable/blob/0a810576179ca48487678b2a9fc7798d2fe70688/pixeltable/func/tools.py#L18)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

That's not really the reason. The real reason is that they can be converted to json-serializable dicts via a standard interface, even though they contain Function instances, which themselves aren't json-serializable. You should also explain why we're  not using a dataclass here.

Speaking  of converting to dict, wasn't that supposed to happen in Expr.from_object()?
</blockquote></details>

Technically it happens in JsonType._create_literal which is called by from_object

I expanded on the code comment
___
*[`pixeltable/func/tools.py` line 39 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OG73ipd0JuMJyOt1JRk:-OG8AJtY1RUYBQD3Pl80:b-6d17jv) ([raw file](https://github.com/pixeltable/pixeltable/blob/0a810576179ca48487678b2a9fc7798d2fe70688/pixeltable/func/tools.py#L39)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Why don't we serialize these like we do in Signature.as_dict(). That way, we record everything that's available to  us. The vendor-specific udf can  do the translation.
</blockquote></details>

Signature.as_dict() has a bunch of stuff that's not relevant here and it would be a lot more cumbersome to translate between it and the vendor code.

This is the format that is near-universal for tool parameters btw (OpenAI and Anthropic and Pydantic all use it)
___
*[`pixeltable/func/tools.py` line 71 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/416#-OG75oxd1rDPRvlptxCN:-OG8Ant21UIfYtlT4sjJ:bvzowj2) ([raw file](https://github.com/pixeltable/pixeltable/blob/0a810576179ca48487678b2a9fc7798d2fe70688/pixeltable/func/tools.py#L71)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

datetime? Seems pretty important.
</blockquote></details>

Do the providers support it? I don't see it used anywhere in the OpenAI documentation, for example. If they do, we have to worry about datetime formatting which could be a rabbit hole (e.g. are we sure all the providers use the same format?)

OpenAI also supports a bunch of other stuff not included here, such as arrays or enums (the latter of which can be really useful for tools b/c they constrain the model's responses). I don't think it's necessary to flesh out all of these capabilities in this PR.


<!-- Sent from Reviewable.io -->

2025-01-09 23:50 UTC, mkornacker approved these changes

2025-01-10 23:33 UTC, merged