Phase 1 of parallel execution
pixeltable/pixeltable pull request #418
Opened 2024-12-22 20:11 UTC by mkornacker

Contains:
- AsyncExprEvalNode: functionally identical replacement of ExprEvalNode, but with async fine-grained scheduling, minus the cohort logic
- ExecNode switched to async execution (__aiter__() instead of __iter__())

Subsequent phases:
2: async udfs with resource pools for accurate rate-limited parallel execution of external API calls
3: parallel local execution via Ray

2024-12-22 20:11 UTC, aaron-siegel commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pixeltable/pixeltable/418)
<!-- Reviewable:end -->

2024-12-30 20:18 UTC, aaron-siegel reviewed
Some random early comments, will take a closer look next week.

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/418#-:-OFOD3OH2LVhEuIMTEPj:b-4ibrxv)* status: 0 of 28 files reviewed, 4 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/dataframe.py` line 440 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OFDqrJB78DVl1XG06O1:-OFDqrJB78DVl1XG06O2:b9wq4sg) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2d53c41139343a7f43a15a6eb8562e1e542280d/pixeltable/dataframe.py#L440)):*
> ```Python
>         return DataFrameResultSet(list(self._output_row_iterator(conn)), self.schema)
> 
>     async def _acollect(self, conn: sql.engine.Connection) -> DataFrameResultSet:
> ```

Factor out an `_async_output_row_iterator` to match the pattern used by `_collect()`?
___
*[`pyproject.toml` line 225 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OFDqBYMEIrVoTHahYgT:-OFDqBYMEIrVoTHahYgU:b-jhgchd) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2d53c41139343a7f43a15a6eb8562e1e542280d/pyproject.toml#L225)):*
> ```TOML
> quote-style = "single"
> line-ending = "auto"
> indent-style = "space"
> ```

No harm in including them of course, but just fyi 'auto' and 'space' are the defaults here, which is why I left them out
___
*[`pixeltable/catalog/table_version.py` line 735 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OFDu06F6b0uhHGFo4UL:-OFDu06F6b0uhHGFo4UM:bz9jiri) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2d53c41139343a7f43a15a6eb8562e1e542280d/pixeltable/catalog/table_version.py#L735)):*
> ```Python
>         if conn is None:
>             #with Env.get().engine.begin() as conn:
>             with Env.get().engine.connect().execution_options(isolation_level='REPEATABLE READ') as conn:
> ```

Feels like this logic should be buried in Env, as in

`Env.get().connect_db()`

or some such (are we ever going to want a different isolation level?)
___
*[`pixeltable/func/callable_function.py` line 39 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OFDvSTg44sswJGAf86R:-OFDvSTg44sswJGAf86S:b3kre) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2d53c41139343a7f43a15a6eb8562e1e542280d/pixeltable/func/callable_function.py#L39)):*
> ```Python
>         self.self_name = self_name
>         self.batch_size = batch_size
>         if inspect.iscoroutinefunction(py_fn):
> ```

?


<!-- Sent from Reviewable.io -->

2024-12-30 20:31 UTC, mkornacker reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/418)* status: 0 of 28 files reviewed, 4 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/catalog/table_version.py` line 735 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OFDu06F6b0uhHGFo4UL:-OFOFke20P5qLs-Wv7Ft:bysehxm) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2d53c41139343a7f43a15a6eb8562e1e542280d/pixeltable/catalog/table_version.py#L735)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Feels like this logic should be buried in Env, as in

`Env.get().connect_db()`

or some such (are we ever going to want a different isolation level?)
</blockquote></details>

This will be removed, it was just to get some test to pass. Anusha already fixed that bug.


<!-- Sent from Reviewable.io -->

2025-01-15 19:24 UTC, aaron-siegel requested changes
I'm going to be posting comments in batches, since this review will take several passes; here's the first batch (more to come).

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/418#-:-OGfQ8EM8Av5jwqiy8D5:bv8ct8)* status: 0 of 38 files reviewed, 27 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/func/callable_function.py` line 39 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OFDvSTg44sswJGAf86R:-OGfNiEl4M_4KPAxnf3u:b-q0u3le) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2d53c41139343a7f43a15a6eb8562e1e542280d/pixeltable/func/callable_function.py#L39)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

?
</blockquote></details>

(extraneous code?)
___
*[`pixeltable/exprs/row_builder.py` line 74 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfN8gg8Zg5hhB2LnEn:-OGfN8gg8Zg5hhB2LnEo:b-c6ljok) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exprs/row_builder.py#L74)):*
> ```Python
> 
>     # dependents[i] = direct dependents of expr with slot idx i; dependents[i, j] == True: expr j depends on expr i
>     dependents: np.ndarray
> ```

I liked how you put `# (of bool)` (for example) to indicate the dtypes of your ndarrays in `DataRow`; I'd suggest doing the same here
___
*[`pixeltable/exec/cache_prefetch_node.py` line 172 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfEXtd01ui006wQoBV:-OGfEXtd01ui006wQoBW:boufyxp) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/cache_prefetch_node.py#L172)):*
> ```Python
>         input_batch: Optional[DataRowBatch]
>         try:
>             input_batch = await input.__anext__()
> ```

Does next() not work here? Seems awkward to call __anext__() directly
___
*[`pixeltable/func/function.py` line 77 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfO-QbAKGE43nJjjyE:-OGfO-QbAKGE43nJjjyF:b-1rqje8) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/func/function.py#L77)):*
> ```Python
>     @abc.abstractmethod
>     def is_async(self) -> bool:
>         pass
> ```

For abstract methods I prefer the syntax
```
@abstractmethod
def is_async(self) -> bool: ...
```
(similar to `@overload` signatures)
___
*[`pixeltable/func/function.py` line 189 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfOTPV3obahmNXHahx:-OGfOTPV3obahmNXHahy:b-loouj) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/func/function.py#L189)):*
> ```Python
>         return fn
> 
>     def __default_resource_pool(self) -> Optional[str]:
> ```

Doesn't this need `self, *args, **kwargs` as the signature?
___
*[`pixeltable/functions/openai.py` line 109 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfPMKd2xB3hwB9AizV:-OGfPMKd2xB3hwB9AizW:b-3eoq7k) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/functions/openai.py#L109)):*
> ```Python
>     # examples: 1d2h3ms, 4m5.6s
>     # fractional seconds can be reported as 0.5s or 500ms
>     pattern = re.compile(r'(?:(\d+)d)?(?:(\d+)h)?(?:(\d+)ms)|(?:(\d+)m)?(?:([\d.]+)s)?')
> ```

make this a global variable (so we only compile the RE once)
___
*[`pixeltable/functions/openai.py` line 488 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfPi6UE8ieeIRnd9f9:-OGfPi6UE8ieeIRnd9fA:b-1hj9ok) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/functions/openai.py#L488)):*
> ```Python
> 
> 
> @embeddings.resource_pool
> ```

You don't actually need to declare these all separately, if they have the same method body; just put this at the bottom of the file:

```
@chat_completions.resource_pool
@embeddings.resource_pool
@image_generations.resource_pool
# etc
def _(model: str) -> str:
    ...
```
___
*[`pixeltable/exec/data_row_batch.py` line 25 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfEjpz2H2y1JvcIhB2:-OGfEjpz2H2y1JvcIhB3:bfyol4z) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/data_row_batch.py#L25)):*
> ```Python
> 
>     def __init__(
>         self, tbl: Optional[catalog.TableVersion], row_builder: exprs.RowBuilder, len: Optional[int] = None,
> ```

I realize this is a legacy issue but it'd be best not to have a variable named `len` since that's a builtin.
___
*[`pixeltable/exec/data_row_batch.py` line 27 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfFDeLBADUwIHMcFv6:-OGfFDeLBADUwIHMcFv7:b-szqa4p) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/data_row_batch.py#L27)):*
> ```Python
>         self, tbl: Optional[catalog.TableVersion], row_builder: exprs.RowBuilder, len: Optional[int] = None,
>         rows: Optional[list[exprs.DataRow]] = None
>     ):
> ```

I think this would now benefit from a docstring explaining the difference between specifying `len` and `rows`
___
*[`pixeltable/exec/data_row_batch.py` line 28 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfEygo3KPwyw9uXEAO:-OGfEygo3KPwyw9uXEAP:b-43fbot) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/data_row_batch.py#L28)):*
> ```Python
>         rows: Optional[list[exprs.DataRow]] = None
>     ):
>         assert not(len is not None and rows is not None)
> ```

`len is None or rows is None` would avoid the double negative
___
*[`pixeltable/exec/exec_node.py` line 8 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfFJqO1K-FsV0A9if7:-OGfFJqO1K-FsV0A9if8:b-ckb5ov) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/exec_node.py#L8)):*
> ```Python
> import logging
> from typing import Iterable, Iterator, Optional, TypeVar, AsyncIterator, AsyncIterable
> from concurrent.futures import ThreadPoolExecutor
> ```

sort imports
___
*[`pixeltable/exec/exec_node.py` line 61 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfFx5Y0jEd6hUnBiLo:-OGfFx5Y0jEd6hUnBiLp:be6qb2r) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/exec_node.py#L61)):*
> ```Python
>             _ = asyncio.get_event_loop()
>             import nest_asyncio
>             nest_asyncio.apply()
> ```

yikes, this literally monkeypatches asyncio in place?

Is there any issue with this being called multiple times (once per iteration)? Would it make more sense to do it once and for all in `env`?
___
*[`pixeltable/plan.py` line 780 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfDkdXBtaF1MATls8H:-OGfDkdXBtaF1MATls8I:b-25646z) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/plan.py#L780)):*
> ```Python
>                 plan = exec.ExprEvalNode(row_builder, eval_ctx.target_exprs, sql_exprs, input=plan)
>             # we're returning everything to the user, so we might as well do it in a single batch
>             # TODO: fix batching
> ```

clarify the scope of this TODO (unless it's going to be fixed as part of this PR)
___
*[`pixeltable/dataframe.py` line 279 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGekw7P4cebTIGJcPsl:-OGekw7P4cebTIGJcPsm:bigsne4) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/dataframe.py#L279)):*
> ```Python
>         try:
>             async for row_batch in plan:
>                 for row in row_batch:
> ```

instead of this:
```python
for row in row_batch:
    yield row
```
you can just do this:
```python
yield from row_batch
```
___ [...]

2025-01-15 23:10 UTC, aaron-siegel requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/418)* status: 0 of 38 files reviewed, 27 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/env.py` line 785 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGen6TG669w4JasCvoi:-OGgDqGw9Q9fRbuStRUY:b-bf8sym) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/env.py#L785)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Why not give this a default? Something like this should work

```python
resource_limits: dict[str, RateLimitInfo] = field(default_factory=lambda: {})
```

Then you can instantiate using `RateLimitsInfo()` instead of the awkward `RateLimitsInfo({})`
</blockquote></details>

Actually, even simpler:
```
resource_limits: dict[str, RateLimitInfo] = field(default_factory=dict)
```


<!-- Sent from Reviewable.io -->

2025-01-16 23:39 UTC, aaron-siegel requested changes
Added review comments for Scheduler.

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/418#-:-OGlThwD0saE9uqVjnwu:bvmkx8z)* status: 0 of 38 files reviewed, 42 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/exec/expr_eval/schedulers.py` line 24 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGlM_WbAFn938qsCMUv:-OGlM_WbAFn938qsCMUw:b-l51o84) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/schedulers.py#L24)):*
> ```Python
>     - limit the number of in-flight requests based on the open file limit
>     """
>     @dataclass
> ```

`@dataclass(frozen=True)`?
___
*[`pixeltable/exec/expr_eval/schedulers.py` line 30 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGlMbnG1sgIGc0Pz_pV:-OGlMbnG1sgIGc0Pz_pW:b-l51o84) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/schedulers.py#L30)):*
> ```Python
>         max_tokens: int
> 
>     @dataclass
> ```

`@dataclass(frozen=True)`?
___
*[`pixeltable/exec/expr_eval/schedulers.py` line 47 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGlNEZx-SsO235h2byl:-OGlMtGwACm0BK36svdB:b-amnfuu) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/schedulers.py#L47)):*
> ```Python
>     # scheduling-related state
>     pool_info: env.RateLimitsInfo
>     est_usage: dict[str, Union[int, float]]  # value per resource; accumulated estimates since the last util. report
> ```

why not just make the value type a `float`?
___
*[`pixeltable/exec/expr_eval/schedulers.py` line 91 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGlO7hv3eaxFZ_-XAML:-OGlO7hv3eaxFZ_-XAMM:bx3qonm) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/schedulers.py#L91)):*
> ```Python
>             if not self.pool_info.is_initialized():
>                 # wait for a single request to get rate limits
>                 _logger.debug(f'initializing rate limits for {self.resource_pool}')
> ```

This module would benefit greatly from some more extensive description somewhere in the code of the scheduling strategy. Right now, certain key details have to be inferred from the code (e.g., the fact that we send a "trial balloon" request to get rate limit info from the headers before we start parallelizing)
___
*[`pixeltable/exec/expr_eval/schedulers.py` line 100 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGlPZLY4zqxXoXbYgYc:-OGlPZLY4zqxXoXbYgYd:b3sw2ha) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/schedulers.py#L100)):*
> ```Python
>             limits_info = self._check_resource_limits(request_resources)
>             if limits_info is not None:
>                 # wait for capacity to free up
> ```

Clarify code comment: "The resource described by `limits_info` is at capacity; wait for it to free up"
___
*[`pixeltable/exec/expr_eval/schedulers.py` line 122 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGlPyf12dFGyJ-kASkW:-OGlPyf12dFGyJ-kASkX:bybctcu) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/schedulers.py#L122)):*
> ```Python
>                     # we have nothing in particular to wait for: wait for an arbitrary amount of time and then
>                     # re-evaluate the rate limits
>                     aws.append(asyncio.sleep(1.0))
> ```

Maybe wise to add some jitter here? `0.75 + random() / 2` or some such, in place of hardcoded `1.0`
___
*[`pixeltable/exec/expr_eval/schedulers.py` line 149 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGlOrJ9CZHrXL2El8TW:-OGlOrJ9CZHrXL2El8TX:b-4ivic4) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/schedulers.py#L149)):*
> ```Python
> 
>     def _check_resource_limits(self, request_resources: dict[str, int]) -> Optional[env.RateLimitInfo]:
>         """Returns the most underprovisioned resource, or None if all resources are within limits"""
> ```

Not quite accurate, right? It actually returns the earliest underprovisioned resource in iteration order.

"at capacity" or "near capacity" is a better term than "underprovisioned" here (it isn't really about how it's provisioned)
___
*[`pixeltable/exec/expr_eval/schedulers.py` line 158 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGlS6uBD9EBV1bOYMi0:-OGlS6uBD9EBV1bOYMi1:b-3ef0h5) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/schedulers.py#L158)):*
> ```Python
> 
>     @abc.abstractmethod
>     def _get_request_resources(self, request: FnCallArgs) -> dict[str, int]:
> ```

I prefer `_get_estimated_resources()` here.
___
*[`pixeltable/exec/expr_eval/schedulers.py` line 160 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGlQzWP5pnk_JSmA4dC:-OGlQzWQ3enDoc7AAq5v:b-9khez4) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/schedulers.py#L160)):*
> ```Python
>     def _get_request_resources(self, request: FnCallArgs) -> dict[str, int]:
>         """Return estimated resource usage for the given request"""
>         pass
> ```

I prefer to omit the `pass` in abstract methods and keep only the docstring (or put `...` if there is no docstring)

That's the convention recommended by Ramalho.
___
*[`pixeltable/exec/expr_eval/schedulers.py` line 173 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGlRGvNDrVqFVRs5QnP:-OGlRGvNDrVqFVRs5QnQ:bbbyt6s) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/schedulers.py#L173)):*
> ```Python
> 
>     async def _exec(self, request: FnCallArgs, num_retries: int, is_task: bool) -> None:
>         assert not request.row.has_val[request.fn_call.slot_idx] and not request.row.has_exc(request.fn_call.slot_idx)
> ```

break into two assertions (easier to read + makes debugging easier if one of them fires)
___
*[`pixeltable/exec/expr_eval/schedulers.py` line 209 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGlJW5g16-tdhNSv0YM:-OGlJW5g16-tdhNSv0YN:baten98) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/schedulers.py#L209)):*
> ```Python
> 
> 
> class AnthropicScheduler(RateLimitsScheduler):
> ```

We should be keeping the provider-specific logic out of the core exec classes; better to put this in `pxt.functions.anthropic` (see next comment).
___
*[`pixeltable/exec/expr_eval/schedulers.py` line 215 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGlJdrxEtFKipXBYv_v:-OGlJdryC-lyvXTX0KTz:biu1ksb) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/schedulers.py#L215)):*
> ```Python
>     @classmethod
>     def matches(cls, resource_pool: str) -> bool:
>         return resource_pool.startswith('anthropic:')
> ```

This is a bit of an antipattern. Better would be to put AnthropicScheduler in `pxt.functions.anthropic`, and provide a way for UDFs that register a resource pool to also register a scheduler that goes along with it; for example, by returning the resource pool as a ResourceInfo struct instead of a string. (I don't feel strongly about this last part, or about the specific architecture & registration mechanism, other than it's not ideal to group these in the core exec package or identify them via hardcoded strings)
___
*[`pixeltable/exec/expr_eval/schedulers.py` line 220 at r3](https://reviewable.io/reviews/pixeltable/pi [...]

2025-01-17 23:06 UTC, mkornacker reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/418)* status: 0 of 38 files reviewed, 42 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/dataframe.py` line 440 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OFDqrJB78DVl1XG06O1:-OGh4bjNAfcD5-E2BT0a:b-714wne) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2d53c41139343a7f43a15a6eb8562e1e542280d/pixeltable/dataframe.py#L440)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Factor out an `_async_output_row_iterator` to match the pattern used by `_collect()`?
</blockquote></details>

There is no consumer of this other than _acollect() (_output_row_iterator() is used elsewhere, but I don't see right now where _async_output_row_iterator() might be useful). And it wouldn't save on code and introduces another indirection, so I decided against it.
___
*[`pixeltable/dataframe.py` line 279 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGekw7P4cebTIGJcPsl:-OGh3p851mXgdQnsP0b2:b7sb0ve) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/dataframe.py#L279)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

instead of this:
```python
for row in row_batch:
    yield row
```
you can just do this:
```python
yield from row_batch
```
</blockquote></details>

Mypy complains because row_batch.iter() is not an async iter.
___
*[`pixeltable/env.py` line 75 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGemXMG6g51XILJh91P:-OGhCtwx210uLORTG84X:b-99p696) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/env.py#L75)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This is doing something very similar to `get_client`. You might look at how client registration is done via the `@env.register_client` decorator as a way of specifying different kinds of resource pools without hard-coding `RateLimitsInfo`.

More generally though, I wonder if we should combine `get_client` and `get_resource_pool_info` into a shared `get_resource` abstraction that can be used to register and retrieve arbitrary resources. The configuration mechanism in `get_client` could be useful for resource pools (or other resources) as well. We don't need to do that in this PR but something to consider for the future.
</blockquote></details>

I'm not sure how that's going to work - get_client() uses a static string, but resource pool names are generated based on the function args.

I made get_resource_pool_info() take a class to avoid hardwiring RateLimitsInfo.
___
*[`pixeltable/env.py` line 785 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGen6TG669w4JasCvoi:-OGhDQgDDbwEI8xuduBz:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/env.py#L785)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Actually, even simpler:
```
resource_limits: dict[str, RateLimitInfo] = field(default_factory=dict)
```
</blockquote></details>

Done.
___
*[`pixeltable/env.py` line 801 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGelz0iCp5kWjHNGXSD:-OGhFHnY0crTytJtBocw:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/env.py#L801)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This would be a lot clearer written like so:
```python
for k, v in kwargs.items():
    if v is not None:
        ...
```
</blockquote></details>

Done.
___
*[`pixeltable/env.py` line 813 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfDT3PEY7wWkhgXrvX:-OGhFfv55GHucUt5pkPY:b-m8akgs) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/env.py#L813)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Is `recorded_at` always `datetime.now()`? If so, does it need to be a parameter?
</blockquote></details>

I want all RateLimitInfo instances that get updated in the same record() call to have the same recorded_at.
___
*[`pixeltable/plan.py` line 780 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfDkdXBtaF1MATls8H:-OGhGOYM2trKEZ81vgXc:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/plan.py#L780)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

clarify the scope of this TODO (unless it's going to be fixed as part of this PR)
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table_version.py` line 735 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OFDu06F6b0uhHGFo4UL:-OGhGgzE88_yNi93EorU:bb6un1j) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2d53c41139343a7f43a15a6eb8562e1e542280d/pixeltable/catalog/table_version.py#L735)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

This will be removed, it was just to get some test to pass. Anusha already fixed that bug.
</blockquote></details>

Done
___
*[`pixeltable/exec/cache_prefetch_node.py` line 172 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfEXtd01ui006wQoBV:-OGhGkn_ERerIkcmJohh:b-8drrb5) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/cache_prefetch_node.py#L172)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Does next() not work here? Seems awkward to call __anext__() directly
</blockquote></details>

No, and anext() was only introduced in Python 3.10.
___
*[`pixeltable/exec/data_row_batch.py` line 25 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfEjpz2H2y1JvcIhB2:-OGhHMaID4Ejh8WUHrDW:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/data_row_batch.py#L25)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I realize this is a legacy issue but it'd be best not to have a variable named `len` since that's a builtin.
</blockquote></details>

Done.
___
*[`pixeltable/exec/data_row_batch.py` line 27 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfFDeLBADUwIHMcFv6:-OGhHYCg5IUJLNmMJMWL:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/data_row_batch.py#L27)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I think this would now benefit from a docstring explaining the difference between specifying `len` and `rows`
</blockquote></details>

Done.
___
*[`pixeltable/exec/data_row_batch.py` line 28 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfEygo3KPwyw9uXEAO:-OGhHjEo6jyb_IccCs57:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/data_row_batch.py#L28)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

`len is None or rows is None` would avoid the double negative
</blockquote></details>

Done.
___
*[`pixeltable/exec/exec_node.py` line 8 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfFJqO1K-FsV0A9if7:-OGhHnmKBdvDRmv4BuH0:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/exec_node.py#L8)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

sort imports
</blockquote></details>

Done.
___
*[`pixeltable/exec/exec_node.py` line 61 a [...]

2025-01-18 02:37 UTC, aaron-siegel requested changes
A few more comments from the remaining files. Will make a 2nd pass on Tuesday and address any updates/responses then

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/418#-:-OGrG91BCDxHP9cPBsVS:b-dq4xgg)* status: 0 of 38 files reviewed, 46 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/exec/expr_eval/evaluators.py` line 109 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGrBQV_AxgzXaeM1z2y:-OGrBQV_AxgzXaeM1z2z:bzh1r2c) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/evaluators.py#L109)):*
> ```Python
> 
>         if self.batch_size is not None:
>             if not self.is_closed and (len(queue_items) + self.input_queue.qsize() < self.batch_size):
> ```

I find the naming of `queue_items`, `_queued_items()`, and `input_queue` to be very confusing. I had to read the code several times to understand what they all do. Something like this would be a lot clearer up front (if I understand what each of them means):

`queue_items` -> `fn_calls`
`input_queue` -> `fn_call_batch_queue`
`_queued_items()` -> `fn_call_batch_queue_iter()`

Each one also needs a code comment explaining what it does. Likewise,

`combined_items` -> `combined_fn_calls` (below)
___
*[`pixeltable/exec/expr_eval/evaluators.py` line 125 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGrChs73EvR7Il444f_:-OGrChs73EvR7Il444fa:b-z9p46h) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/evaluators.py#L125)):*
> ```Python
>                     assert self.input_queue.empty()  # we saw all queued items
>                     for item in batch_items:
>                         self.input_queue.put_nowait(item)
> ```

Add comment: Put the excess rows back on the batch queue
___
*[`pixeltable/exec/expr_eval/evaluators.py` line 181 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGrE5cB3a_2p-qA0VeE:-OGrE5cB3a_2p-qA0VeF:bcrcybj) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/evaluators.py#L181)):*
> ```Python
> 
>     async def eval_async(self, item: FnCallArgs) -> None:
>         assert not item.row.has_val[self.fn_call.slot_idx] and not item.row.has_exc(self.fn_call.slot_idx)
> ```

break into two separate assertions?
___
*[`pixeltable/exec/expr_eval/expr_eval_node.py` line 172 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGrFHP545VVrDJAjLjA:-OGrFHP545VVrDJAjLjB:b-jnejw4) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/expr_eval_node.py#L172)):*
> ```Python
>             return
>         assert self.current_input_batch is not None
>         avail_current_batch_rows = len(self.current_input_batch) - self.input_row_idx
> ```

"batch" has become a somewhat overloaded term. To reduce confusion, I wonder if it makes sense to use "batch" exclusively for function call batches, and invent another term ("input segment" or "input cluster" or some such?) on the inbound side.


<!-- Sent from Reviewable.io -->

2025-01-22 18:31 UTC, mkornacker reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/418)* status: 0 of 40 files reviewed, 46 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/exec/expr_eval/evaluators.py` line 109 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGrBQV_AxgzXaeM1z2y:-OHEE1z0E5CbS3aUsPOS:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/evaluators.py#L109)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I find the naming of `queue_items`, `_queued_items()`, and `input_queue` to be very confusing. I had to read the code several times to understand what they all do. Something like this would be a lot clearer up front (if I understand what each of them means):

`queue_items` -> `fn_calls`
`input_queue` -> `fn_call_batch_queue`
`_queued_items()` -> `fn_call_batch_queue_iter()`

Each one also needs a code comment explaining what it does. Likewise,

`combined_items` -> `combined_fn_calls` (below)
</blockquote></details>

Done.
___
*[`pixeltable/exec/expr_eval/evaluators.py` line 125 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGrChs73EvR7Il444f_:-OHEELFF-QsinFeiv0q5:baoha9q) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/evaluators.py#L125)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Add comment: Put the excess rows back on the batch queue
</blockquote></details>

It says that 3 lines above
___
*[`pixeltable/exec/expr_eval/evaluators.py` line 181 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGrE5cB3a_2p-qA0VeE:-OHEEROs3squgvyAsjf2:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/evaluators.py#L181)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

break into two separate assertions?
</blockquote></details>

Done.
___
*[`pixeltable/exec/expr_eval/expr_eval_node.py` line 172 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGrFHP545VVrDJAjLjA:-OHEEeLe7adIbPQU2p9-:bbxuosl) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/expr_eval_node.py#L172)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

"batch" has become a somewhat overloaded term. To reduce confusion, I wonder if it makes sense to use "batch" exclusively for function call batches, and invent another term ("input segment" or "input cluster" or some such?) on the inbound side.
</blockquote></details>

They refer to the same thing (a collection of rows that need to be processed in the same way).
___
*[`pixeltable/exec/expr_eval/schedulers.py` line 91 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGlO7hv3eaxFZ_-XAML:-OHEGoJ06sLDeSFlCS5T:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/schedulers.py#L91)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This module would benefit greatly from some more extensive description somewhere in the code of the scheduling strategy. Right now, certain key details have to be inferred from the code (e.g., the fact that we send a "trial balloon" request to get rate limit info from the headers before we start parallelizing)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-23 23:55 UTC, aaron-siegel requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/418)* status: 0 of 40 files reviewed, 16 unresolved discussions (waiting on @mkornacker)

___
*[`pyproject.toml` line 225 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OFDqBYMEIrVoTHahYgT:-OHKAFGe9RYYcu-0zRaa:b5rekjs) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2d53c41139343a7f43a15a6eb8562e1e542280d/pyproject.toml#L225)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

No harm in including them of course, but just fyi 'auto' and 'space' are the defaults here, which is why I left them out
</blockquote></details>

Bumping this comment; is it intentional to include these formatter config changes in this PR?
___
*[`pixeltable/env.py` line 813 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfDT3PEY7wWkhgXrvX:-OHKAg88EvjnLy6lmrxa:b-2egbng) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/env.py#L813)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

I want all RateLimitInfo instances that get updated in the same record() call to have the same recorded_at.
</blockquote></details>

Aha, makes sense.
___
*[`pixeltable/exec/cache_prefetch_node.py` line 172 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfEXtd01ui006wQoBV:-OHKAuB_-gDHN_5Ey398:b-i5f7vt) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/cache_prefetch_node.py#L172)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

No, and anext() was only introduced in Python 3.10.
</blockquote></details>

Ok. Sad but ok :)
___
*[`pixeltable/exec/exec_node.py` line 61 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfFx5Y0jEd6hUnBiLo:-OHKBMJA9t4ujI5-_3zh:b-4kd1at) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/exec_node.py#L61)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

It's only called once - this is a generator.

You need to do it for the running loop.
</blockquote></details>

Ok, but once per exec node, right? So over the lifetime of the application there could be numerous calls.
___
*[`pixeltable/exec/expr_eval/expr_eval_node.py` line 172 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGrFHP545VVrDJAjLjA:-OHKETTGCUidxUO-kJrO:bcrei9r) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/expr_eval_node.py#L172)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

They refer to the same thing (a collection of rows that need to be processed in the same way).
</blockquote></details>

Kinda, but the treatment is sufficiently different that I think the terminology would benefit from disambiguation, especially since we often use "batch" without a qualifier.

Not something urgent we need to resolve now but just a thought.
___
*[`pixeltable/exec/expr_eval/schedulers.py` line 122 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGlPyf12dFGyJ-kASkW:-OHKEz6q0qcXBXzd-U-3:b-6sa2ct) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/schedulers.py#L122)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

What would that  do?
</blockquote></details>

It's generally good practice any time you're doing retries via backoff. The reason is that if you have multiple threads/processes that are all competing for the constrained resource and are all using a fixed backoff, then the competition tends to concentrate. (They all get stuck at the same time, they all wait exactly 1 second, and then there's a concentrated flood when they all wake up at the same time.) So we add some randomness to ensure they wake up at different times.

I think this is probably only relevant here in cases where there are multiple Pixeltable instances that are competing against the same rate limit pool but that's not an inconceivable scenario, and I've become accustomed to always build in jitter when backing off as a general best practice.
___
*[`pixeltable/exec/expr_eval/schedulers.py` line 149 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGlOrJ9CZHrXL2El8TW:-OHKGTbF7btWFjMNPCqv:b9jnnlg) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/schedulers.py#L149)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still not quite accurate? If resource A is at 96% capacity and resource B is at 98% capacity, and resource A is first in iteration order (of the request_resources dict), then it will return resource A, even though resource B is more exhausted.
___
*[`pixeltable/exprs/data_row.py` line 131 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfI9s0Bpkj6kTlQbsr:-OHKHLwn0bm15DI4ZimP:b5jwa0m) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exprs/data_row.py#L131)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

That would only return excs[0] or excs[1]
</blockquote></details>

Oh duh. sorry
___
*[`pixeltable/exprs/data_row.py` line 144 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfISdUE4MyztpXMV7x:-OHKHWva-oYEPnFOdOoi:bufy5wv) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exprs/data_row.py#L144)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Wait I don't see it, len is commented out now?
___
*[`pixeltable/exprs/function_call.py` line 39 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfJiw6A-NlMj2g_84E:-OHKX1Ol624gdltkU6SW:b6jgw2i) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exprs/function_call.py#L39)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

They aren't really arguments (because they may not be given as arguments), they are the values that the parameters take on for this function call.

Augmented comment.
</blockquote></details>

I see what you're saying. Sometimes they're arguments and sometimes they're defaults. But see my comment below

Another thought, the pattern of using a Left/Right tuple to express "either a component index or a static value" is common enough in the codebase that I think it deserves a named tuple (and I think this would make the code that uses it a lot more readable). (Doesn't have to be done in this PR)
___
*[`pixeltable/exprs/function_call.py` line 425 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfLIGA43AiZIMHfIk1:-OHKY4vy30EHByPgnC5b:blworr8) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exprs/function_call.py#L425)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

How so?
</blockquote></details>

Because `param_values` returns a single dict and can contain component indices, which aren't values (they're expression references).

When reading code my natural expectation would be that if there's a variable named `param_values` and a method named `get_param_values()`, then the latter returns the contents of the former. That's not what's happening here; there's a lot more going on.

An alternative could be to call the method `resolve_param_values` or `evaluate_parameters` or some such
___
*[`pi [...]

2025-01-24 00:02 UTC, aaron-siegel approved these changes
Approved with a few more comments. I think the new architecture for registering RateLimitsInfo structures is a big improvement

> Reviewed 28 of 28 files at r1, 2 of 2 files at r2, 19 of 19 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/418#-:-OHKbFB74Q_k8H7KAuAx:boyhakk)* status: 11 of 40 files reviewed, 16 unresolved discussions (waiting on @mkornacker)



<!-- Sent from Reviewable.io -->

2025-01-24 01:52 UTC, mkornacker reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/418)* status: 11 of 40 files reviewed, 16 unresolved discussions (waiting on @aaron-siegel)

___
*[`pyproject.toml` line 225 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OFDqBYMEIrVoTHahYgT:-OHKfHqgEsrKZImpPChW:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2d53c41139343a7f43a15a6eb8562e1e542280d/pyproject.toml#L225)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Bumping this comment; is it intentional to include these formatter config changes in this PR?
</blockquote></details>

Done.
___
*[`pixeltable/exec/exec_node.py` line 61 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfFx5Y0jEd6hUnBiLo:-OHKerQw-BoCgPJmRdsh:bpu1pnq) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/exec_node.py#L61)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Ok, but once per exec node, right? So over the lifetime of the application there could be numerous calls.
</blockquote></details>

No, only for the root of the execution plan. It's only the surrounding code, like StoreTable.insert_rows(), that calls the sync iterator. The exec nodes themselves use the async interface.
___
*[`pixeltable/exec/expr_eval/evaluators.py` line 94 at r5](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OHKEEN33qT1C7Yk68S-:-OHKgARH-kTE4ZqKcNiG:b-hff6wv) ([raw file](https://github.com/pixeltable/pixeltable/blob/73fc54649cea3c9f480913b6b75345ba88fa9af4/pixeltable/exec/expr_eval/evaluators.py#L94)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Add comment explaining what this is.
</blockquote></details>

renamed
___
*[`pixeltable/exec/expr_eval/schedulers.py` line 122 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGlPyf12dFGyJ-kASkW:-OHKgJSB2oaZ6o6m1Oo8:b-sug6ur) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/schedulers.py#L122)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

It's generally good practice any time you're doing retries via backoff. The reason is that if you have multiple threads/processes that are all competing for the constrained resource and are all using a fixed backoff, then the competition tends to concentrate. (They all get stuck at the same time, they all wait exactly 1 second, and then there's a concentrated flood when they all wake up at the same time.) So we add some randomness to ensure they wake up at different times.

I think this is probably only relevant here in cases where there are multiple Pixeltable instances that are competing against the same rate limit pool but that's not an inconceivable scenario, and I've become accustomed to always build in jitter when backing off as a general best practice.
</blockquote></details>

There is no backoff or retry here.

Anyway, changed the logic.
___
*[`pixeltable/exec/expr_eval/schedulers.py` line 149 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGlOrJ9CZHrXL2El8TW:-OHKz0XaAQ5VjBVByNAr:b1bbgou) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exec/expr_eval/schedulers.py#L149)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Still not quite accurate? If resource A is at 96% capacity and resource B is at 98% capacity, and resource A is first in iteration order (of the request_resources dict), then it will return resource A, even though resource B is more exhausted.
</blockquote></details>

min() picks the one with the lowest relative remaining.
___
*[`pixeltable/exec/expr_eval/schedulers.py` line 237 at r5](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OHKHBlX9_jnjaZekZZP:-OHKzJ-r-f2hEmgP2XlU:b-v22se1) ([raw file](https://github.com/pixeltable/pixeltable/blob/73fc54649cea3c9f480913b6b75345ba88fa9af4/pixeltable/exec/expr_eval/schedulers.py#L237)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

It's not clear to me how this is being used now? It never seems to get expanded?
</blockquote></details>

Expanded? Phase 1.2 will add a RequestRateScheduler here.
___
*[`pixeltable/exprs/data_row.py` line 144 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfISdUE4MyztpXMV7x:-OHKzcNI8ciElmFtWtyg:bss4a2b) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exprs/data_row.py#L144)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Wait I don't see it, len is commented out now?
</blockquote></details>

Removed.
___
*[`pixeltable/exprs/function_call.py` line 39 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfJiw6A-NlMj2g_84E:-OHKzk1e1GQbT4y4FI8u:b-bq08oe) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exprs/function_call.py#L39)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I see what you're saying. Sometimes they're arguments and sometimes they're defaults. But see my comment below

Another thought, the pattern of using a Left/Right tuple to express "either a component index or a static value" is common enough in the codebase that I think it deserves a named tuple (and I think this would make the code that uses it a lot more readable). (Doesn't have to be done in this PR)
</blockquote></details>

Yeah, maybe.
___
*[`pixeltable/exprs/function_call.py` line 425 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OGfLIGA43AiZIMHfIk1:-OHL-5Hv8TxiZ5qX7sVd:by60mgj) ([raw file](https://github.com/pixeltable/pixeltable/blob/6761d6ecd0c7335a0f8a8fd492af27cab6d41423/pixeltable/exprs/function_call.py#L425)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Because `param_values` returns a single dict and can contain component indices, which aren't values (they're expression references).

When reading code my natural expectation would be that if there's a variable named `param_values` and a method named `get_param_values()`, then the latter returns the contents of the former. That's not what's happening here; there's a lot more going on.

An alternative could be to call the method `resolve_param_values` or `evaluate_parameters` or some such
</blockquote></details>

Renamed param_values to _param_values.
___
*[`pixeltable/functions/openai.py` line 661 at r5](https://reviewable.io/reviews/pixeltable/pixeltable/418#-OHK_PhFCdyNvx7HopJC:-OHL-Hs67vYoc-6V5Ki1:b-k2ckv8) ([raw file](https://github.com/pixeltable/pixeltable/blob/73fc54649cea3c9f480913b6b75345ba88fa9af4/pixeltable/functions/openai.py#L661)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

We may not need the separate `_resource_pool()` function now? (Since it's only called once now, it could just be folded into the decorated method? Unless you're planning on parameterizing it later or some such)
</blockquote></details>

Not following. It's already parameterized (with the model). In phase 1.2 we'll also have per-endpoint pool names (rate-limits:openai:... vs request-rate:openai:..., depending on which endpoints provide rate-related headers).


<!-- Sent from Reviewable.io -->

2025-01-24 04:01 UTC, merged