PXT-179 Add a if_exists parameter to add_* APIs
pixeltable/pixeltable pull request #422
Opened 2024-12-24 19:41 UTC by anushas

This commit adds a new parameter - if_exists - for the add_embedding_index,
add_columns, add_column, and add_computed_column APIs which can be used
to handle scenarios where an index name or column name may already exist.
It can direct the API to not add the index or column and return, or raise it as an error,
or replace the existing index or column with a new one if it has no dependents.

Also fixed minor bugs as agreed:
- fixed the add column APIs to raise an error when used with a snapshot, instead
of an assertion failure later in the code.
- fixed the create_view API to not allow base table column names in additional_columns
when creating a view/snapshot to make it consistent with add column APIs. 

Testing: added new testcases for the new parameter and bugfixes.

2024-12-24 19:41 UTC, aaron-siegel commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pixeltable/pixeltable/422)
<!-- Reviewable:end -->

2024-12-24 22:43 UTC, anushas commented
One of the CI builds failed with the following docstring warnings; taking a look. make test and make typecheck was all clean before I submitted the PR.

> Run mkdocs build --strict
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /home/runner/work/pixeltable/pixeltable/target/site
WARNING -  griffe: pixeltable/catalog/table.py:5[18](https://github.com/pixeltable/pixeltable/actions/runs/12485609721/job/34844620730?pr=422#step:18:19): Parameter '-' does not appear in the function signature
WARNING -  griffe: pixeltable/catalog/table.py:519: Parameter '-' does not appear in the function signature
WARNING -  griffe: pixeltable/catalog/table.py:5[20](https://github.com/pixeltable/pixeltable/actions/runs/12485609721/job/34844620730?pr=422#step:18:21): Parameter '-' does not appear in the function signature
WARNING -  griffe: pixeltable/catalog/table.py:521: Failed to get 'name: description' pair from 'Defaults to `'error'`.'
WARNING -  griffe: pixeltable/catalog/table.py:5[22](https://github.com/pixeltable/pixeltable/actions/runs/12485609721/job/34844620730?pr=422#step:18:23): Failed to get 'name: description' pair from 'Note that the if_exists parameter is applied to all columns in the schema.'
WARNING -  griffe: pixeltable/catalog/table.py:523: Failed to get 'name: description' pair from 'To apply different behaviors to different columns, please use [`add_column()`][pixeltable.Table.add_column] for each column.'
WARNING -  griffe: pixeltable/catalog/table.py:676: Confusing indentation for continuation line [24](https://github.com/pixeltable/pixeltable/actions/runs/12485609721/job/34844620730?pr=422#step:18:25) in docstring, should be 4 * 2 = 8 spaces, not 5
>
> Aborted with 7 warnings in strict mode!
Error: Process completed with exit code 1.

2024-12-25 01:08 UTC, anushas commented
Resolved the mkdocs issue (due to indentation) and resolved the conflict with latest main.

2025-01-03 17:32 UTC, mkornacker requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/422)* status: 0 of 11 files reviewed, 21 unresolved discussions (waiting on @aaron-siegel and @anushas)

___
*[`pixeltable/catalog/column.py` line 179 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/422#-OFhBYnJAOYrqFygjnJc:-OFhBYnJAOYrqFygjnJd:ba5yzoc) ([raw file](https://github.com/pixeltable/pixeltable/blob/de1cc83d363f1065d17f61e32667a8c6336c65b2/pixeltable/catalog/column.py#L179)):*
> ```Python
>         """ Returns True if this column has dependent user columns"""
>         dependent_user_cols = [c for c in self.dependent_cols if c.name is not None]
>         return len(dependent_user_cols) > 0
> ```

More concise and fewer intermediate objects:
any(c.name is not None for c in ...)
___
*[`tests/test_table.py` line 1709 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/422#-OFdaiSLBn51f3aD8JoY:-OFdaiSLBn51f3aD8JoZ:b6y41hq) ([raw file](https://github.com/pixeltable/pixeltable/blob/de1cc83d363f1065d17f61e32667a8c6336c65b2/tests/test_table.py#L1709)):*
> ```Python
>         orig_cnames = t.columns
>         # See create_test_tbl for the column names and types
>         assert 'c1' in orig_cnames and type(t.c1.col.col_type) == pxt.StringType
> ```

Remove, not necessary. Also, all member variables of ColumnRef are internal and shouldn't be used here.
___
*[`tests/test_table.py` line 1716 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/422#-OFdb8-48HbSIcGRPbXv:-OFdb8-48HbSIcGRPbXw:b-ytm9xn) ([raw file](https://github.com/pixeltable/pixeltable/blob/de1cc83d363f1065d17f61e32667a8c6336c65b2/tests/test_table.py#L1716)):*
> ```Python
>         # invalid if_exists is rejected
>         expected_err_str = "if_exists must be one of: ['error', 'ignore', 'replace', 'replace_force']"
>         assert_raises_error(expected_err_str, t.add_column, non_existing_col1=pxt.Int, if_exists='invalid')
> ```

I'm finding these tests harder to read than before. Something like this would look better:

with xyz(expected_error_str):
    _ = t.add_column(...)
___
*[`tests/test_view.py` line 229 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/422#-OFdc2XSBAYgOhPv9QX4:-OFdc2XSBAYgOhPv9QX5:b-i6dwwm) ([raw file](https://github.com/pixeltable/pixeltable/blob/de1cc83d363f1065d17f61e32667a8c6336c65b2/tests/test_view.py#L229)):*
> ```Python
>         reload_tester.run_reload_test()
> 
>     def _test_if_exists_ignore(self, v: catalog.View, col_name: str,
> ```

formatting
___
*[`tests/test_view.py` line 233 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/422#-OFdcZtK1R3GZfH8WgZf:-OFdcZtK1R3GZfH8WgZg:b-95ktsb) ([raw file](https://github.com/pixeltable/pixeltable/blob/de1cc83d363f1065d17f61e32667a8c6336c65b2/tests/test_view.py#L233)):*
> ```Python
>         func, *args, **kwargs) -> None:
>         """ Test if_exists='ignore' parameter in add column methods for views """
>         func(*args, **kwargs)
> ```

Why pass this in if all you're doing is invoking it (without using the result)?
___
*[`tests/test_view.py` line 237 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/422#-OFdbwgL205juuLa0wUF:-OFdbwgM0VcXiAE-IWyY:b-i6dwwm) ([raw file](https://github.com/pixeltable/pixeltable/blob/de1cc83d363f1065d17f61e32667a8c6336c65b2/tests/test_view.py#L237)):*
> ```Python
>         assert v.select(getattr(v, col_name)).collect()[0][col_name] == orig_val
> 
>     def _test_add_column_if_exists(self, v: catalog.View, t: catalog.Table, col_name: str,
> ```

formatting
___
*[`pixeltable/catalog/table.py` line 444 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/422#-OFdWIPf2HflgrE2BqYK:-OFdWIPf2HflgrE2BqYL:b-9fzbo5) ([raw file](https://github.com/pixeltable/pixeltable/blob/de1cc83d363f1065d17f61e32667a8c6336c65b2/pixeltable/catalog/table.py#L444)):*
> ```Python
>         self.add_column(stored=None, print_stats=False, on_error='abort', if_exists='error', **{col_name: spec})
> 
>     def __column_has_dependents(self, col: Column) -> bool:
> ```

Make it protected (ie, '_column_...'). That should generally be the default.
___
*[`pixeltable/catalog/table.py` line 446 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/422#-OFhBydlBE2iEBG2MVFH:-OFhBydlBE2iEBG2MVFI:bw95e1j) ([raw file](https://github.com/pixeltable/pixeltable/blob/de1cc83d363f1065d17f61e32667a8c6336c65b2/pixeltable/catalog/table.py#L446)):*
> ```Python
>     def __column_has_dependents(self, col: Column) -> bool:
>         """Returns True if the column has dependents, False otherwise."""
>         assert col is not None
> ```

check that column belongs to this table
___
*[`pixeltable/catalog/table.py` line 447 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/422#-OFdFs2M7S4pBTdu1eHt:-OFdFs2M7S4pBTdu1eHu:bxgjh9y) ([raw file](https://github.com/pixeltable/pixeltable/blob/de1cc83d363f1065d17f61e32667a8c6336c65b2/pixeltable/catalog/table.py#L447)):*
> ```Python
>         """Returns True if the column has dependents, False otherwise."""
>         assert col is not None
>         if col._has_dependent_user_columns:
> ```

Is this called anywhere else? Might be best to inline the logic here.
___
*[`pixeltable/catalog/table.py` line 450 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/422#-OFdIKJ4BMvRA_CJJw-H:-OFdIKJ4BMvRA_CJJw-I:b-7t8um0) ([raw file](https://github.com/pixeltable/pixeltable/blob/de1cc83d363f1065d17f61e32667a8c6336c65b2/pixeltable/catalog/table.py#L450)):*
> ```Python
>             return True
>         dependent_stores = [
>             (view, store)
> ```

any()
___
*[`pixeltable/catalog/table.py` line 460 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/422#-OFdSsJi3yEP9j6U1KFP:-OFdSsJi3yEP9j6U1KFQ:b-uuws8u) ([raw file](https://github.com/pixeltable/pixeltable/blob/de1cc83d363f1065d17f61e32667a8c6336c65b2/pixeltable/catalog/table.py#L460)):*
> ```Python
> 
>     def __skip_or_drop_existing_columns(self, new_col_spec: dict[str, Any], if_exists: IfExistsParam) -> None:
>         """ Check for existing column in the new column specification and handle them according to the if_exists parameter.
> ```

grammar
___
*[`pixeltable/catalog/table.py` line 464 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/422#-OFdTUn-4HcLEeY7mdft:-OFdTUn-4HcLEeY7mdfu:bxj3mxt) ([raw file](https://github.com/pixeltable/pixeltable/blob/de1cc83d363f1065d17f61e32667a8c6336c65b2/pixeltable/catalog/table.py#L464)):*
> ```Python
>         Note that this function will remove any column names from the passed in `new_col_spec` if `if_exists='ignore'`.
> 
>         Args:
> ```

This is not a user-facing function, and it doesn't need to produce markdown. Condense the comment (remove Args and Raises, etc.; look at other code).

The same applies elsewhere.
___
*[`pixeltable/catalog/table.py` line 499 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/422#-OFdVyA--JSemQTJbQVO:-OFdVyA--JSemQTJbQVP:b74r4xg) ([raw file](https://github.com/pixeltable/pixeltable/blob/de1cc83d363f1065d17f61e32667a8c6336c65b2/pixeltable/catalog/table.py#L499)):*
> ```Python
>                     self.drop_column(new_col_name)
>                     assert new_col_name not in self._tbl_version.cols_by_name
>         # remove the existing columns from new_col_spec when if_exists='ignore'
> ```

precede w/ blank line (and in general use blank lines to break up the code where useful)
___
*[`pixeltable/catalog/table.py` line 500 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/422#-OFdTGWq--Pgu4iV_du9:-OFdTGWq--Pgu4iV_duA:b-3ywpv1) ([raw file](https://github.com/pixeltable/pixeltable/blob/de1cc83d363f1065d17f61e32667a8c6336c65b2/pixeltable/catalog/table.py#L500)):*
> ```Python
>                     assert new_col_name not in self._tbl_version.cols_by_name
>         # remove the existing columns from new_col_spec when if_exists='ignore'
>         for _cname in cols_to_ignore:
> ```

Why _cname?
___
*[`pixeltable/catalog/table.py` line 553 at r2](https://reviewable.io/reviews/pixeltable/pixelta [...]

2025-01-11 01:11 UTC, mkornacker commented on pixeltable/catalog/table.py
> +        ):
More concise, without creating intermediate objects:

any(col in store.get_local_columns()
           for view in [self] + self._get_views(recursive=True)
           for store in view._tbl_version.external_stores.values())

2025-01-11 01:11 UTC, mkornacker commented on pixeltable/catalog/table.py
> +    def _ignore_or_drop_existing_columns(self, new_col_spec: dict[str, Any], if_exists: IfExistsParam) -> list[str]:
You don't need the dict, you only need dict.keys()

2025-01-11 01:14 UTC, mkornacker reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/422)* status: 0 of 11 files reviewed, 24 unresolved discussions (waiting on @aaron-siegel and @anushas)

___
*[`tests/test_dirs.py` line 43 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/422#-OGHuqa73CE-U9rEhgwq:-OGHuqa73CE-U9rEhgwr:bjz3lmy) ([raw file](https://github.com/pixeltable/pixeltable/blob/1335645e49408d91448576ca0b383c0f89466334/tests/test_dirs.py#L43)):*
> ```Python
>         with pytest.raises(excs.Error, match=r'already exists'):
>             pxt.create_dir('dir1.t1')
>         with pytest.raises(excs.Error, match=r"No such path"):
> ```

Single quotes


<!-- Sent from Reviewable.io -->

2025-01-11 02:51 UTC, anushas reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/422)* status: 0 of 11 files reviewed, 24 unresolved discussions (waiting on @aaron-siegel and @mkornacker)

___
*[`tests/test_dirs.py` line 43 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/422#-OGHuqa73CE-U9rEhgwq:-OGIGVKz0hhI1IsORbRz:bb4m79) ([raw file](https://github.com/pixeltable/pixeltable/blob/1335645e49408d91448576ca0b383c0f89466334/tests/test_dirs.py#L43)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Single quotes
</blockquote></details>

Done. other instances too.


<!-- Sent from Reviewable.io -->

2025-01-11 02:51 UTC, anushas commented on pixeltable/catalog/table.py
> +        ):
Done.
<!-- Reviewable comment -OGIGFTK33d9yRZB9Dm-:b-896fix -->
<!-- Sent from Reviewable.io -->

2025-01-11 02:51 UTC, anushas commented on pixeltable/catalog/table.py
> +    def _ignore_or_drop_existing_columns(self, new_col_spec: dict[str, Any], if_exists: IfExistsParam) -> list[str]:
Done.
<!-- Reviewable comment -OGIGPxR6VZnN4rnLDtb:b-896fix -->
<!-- Sent from Reviewable.io -->

2025-01-13 16:59 UTC, mkornacker commented on pixeltable/catalog/table.py
> +    def _ignore_or_drop_existing_columns(self, new_col_names: list[str], if_exists: IfExistsParam) -> list[str]:
if you make new_col_names a Sequence[str], you can simply pass in keys().

2025-01-13 19:01 UTC, anushas commented on pixeltable/catalog/table.py
> +    def _ignore_or_drop_existing_columns(self, new_col_names: list[str], if_exists: IfExistsParam) -> list[str]:
I tried, but it gives me typecheck error dict_keys is not compatible with sequence. So reverted.

2025-01-13 19:46 UTC, merged

2025-01-13 21:55 UTC, mkornacker commented on pixeltable/catalog/table.py
> +    def _ignore_or_drop_existing_columns(self, new_col_names: list[str], if_exists: IfExistsParam) -> list[str]:
Iterable would work.