PXT-373 - Add if_not_exists parameter to drop_* APIs
pixeltable/pixeltable pull request #423
Opened 2024-12-25 00:29 UTC by anushas

This commit adds a new parameter - if_not_exists - to the drop_dir, drop_table,
drop_embedding_index, drop_index and drop_column APIs. This can be used to
direct the API to either raise an error or do nothing and return when a dir/table/index/column
does not exist.

Testing: added new test for the new parameter.

2024-12-25 00:29 UTC, aaron-siegel commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pixeltable/pixeltable/423)
<!-- Reviewable:end -->

2025-01-07 21:11 UTC, aaron-siegel requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/423)* status: 0 of 9 files reviewed, 9 unresolved discussions (waiting on @anushas and @mkornacker)

___
*[`pixeltable/globals.py` line 448 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OG1MIwwA8VVnh9G_Yh6:-OG1MIwwA8VVnh9G_Yh7:b91jarj) ([raw file](https://github.com/pixeltable/pixeltable/blob/8c2d7d49f5b650ef11c9cf1574dc5afd4ce74051/pixeltable/globals.py#L448)):*
> ```Python
>         if_not_exists: Directive regarding how to handle if the path does not exist.
>             Must be one of the following:
>             - `'error'`: raise an error
> ```

Be sure to run `mkdocs build` locally and look at the generated output to make sure it's formatted intelligibly. mkdocstrings can sometimes be fussy about markdown spacing and formatting.
___
*[`pixeltable/globals.py` line 453 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OG1MW455EJcCUr2ttVl:-OG1MW455EJcCUr2ttVm:buqzcpj) ([raw file](https://github.com/pixeltable/pixeltable/blob/8c2d7d49f5b650ef11c9cf1574dc5afd4ce74051/pixeltable/globals.py#L453)):*
> ```Python
> 
>     Raises:
>         Error: If the name is invalid, or name does not exist and `if_not_exists='error'`,
> ```

this is hard for me to parse; maybe would be clearer as a bulleted list?
___
*[`pixeltable/globals.py` line 454 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OG1MrKW1g8GmgzSCvr3:-OG1MrKW1g8GmgzSCvr4:b-jhmcti) ([raw file](https://github.com/pixeltable/pixeltable/blob/8c2d7d49f5b650ef11c9cf1574dc5afd4ce74051/pixeltable/globals.py#L454)):*
> ```Python
>     Raises:
>         Error: If the name is invalid, or name does not exist and `if_not_exists='error'`,
>             or does not designate a table object, or has dependents and `force='False'`.
> ```

`'False'` should not be in strings
___
*[`pixeltable/catalog/table.py` line 705 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OG1Ym_XEXY5Wm9gcOxK:-OG1XF4c5iDw80TlB6og:b-xuuxl4) ([raw file](https://github.com/pixeltable/pixeltable/blob/8c2d7d49f5b650ef11c9cf1574dc5afd4ce74051/pixeltable/catalog/table.py#L705)):*
> ```Python
>             column_names.add(col.name)
> 
>     def __check_column_name_exists(self, column_name: str, include_bases: bool = False, if_not_exists: IfNotExistsParam = IfNotExistsParam.ERROR) -> bool:
> ```

The semantics of these `__check` methods are pretty confusing now (they're trying to do two things at once). I'd suggest just keeping them as they were before, and performing the `if_not_exists` check in the calling function(s). There's not much benefit in parameterizing them this way, since they only get called using the `if_not_exists` parameter in one place (unless i'm missing something).
___
*[`pixeltable/catalog/table.py` line 749 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OG1Wstm-5QAa-xio9iW:-OG1Wstm-5QAa-xio9iX:bjgmm3h) ([raw file](https://github.com/pixeltable/pixeltable/blob/8c2d7d49f5b650ef11c9cf1574dc5afd4ce74051/pixeltable/catalog/table.py#L749)):*
> ```Python
>         """
>         self._check_is_dropped()
>         if self.get_metadata()['is_snapshot']:
> ```

Better to use `self._tbl_version_path.is_snapshot()`
___
*[`pixeltable/catalog/table.py` line 755 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OG1Y17fDeR1rL5s0FzY:-OG1Y17fDeR1rL5s0FzZ:b65n6fn) ([raw file](https://github.com/pixeltable/pixeltable/blob/8c2d7d49f5b650ef11c9cf1574dc5afd4ce74051/pixeltable/catalog/table.py#L755)):*
> ```Python
>         if isinstance(column, str):
>             exists = self.__check_column_name_exists(column, False, _if_not_exists)
>             if not exists and _if_not_exists == IfNotExistsParam.IGNORE:
> ```

`_if_not_exists == IfNotExistsParam.IGNORE` is a superfluous condition (it has to be such or the preceding line would have thrown an exception); either remove it or make it an assertion
___
*[`pixeltable/catalog/table.py` line 757 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OG1Y8bo4IYL-iaZ3h_u:-OG1Y8bo4IYL-iaZ3h_v:b-wjo7qe) ([raw file](https://github.com/pixeltable/pixeltable/blob/8c2d7d49f5b650ef11c9cf1574dc5afd4ce74051/pixeltable/catalog/table.py#L757)):*
> ```Python
>             if not exists and _if_not_exists == IfNotExistsParam.IGNORE:
>                 return
>             assert exists
> ```

Redundant assertion (we just checked for it)
___
*[`pixeltable/catalog/table.py` line 902 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OG1ZMo4DLTsM2HAz2Wd:-OG1ZMo4DLTsM2HAz2We:b3xesqv) ([raw file](https://github.com/pixeltable/pixeltable/blob/8c2d7d49f5b650ef11c9cf1574dc5afd4ce74051/pixeltable/catalog/table.py#L902)):*
> ```Python
>                     The column must have only one embedding index.
>             idx_name: The name of the index to drop.
>             if_not_exists: Directive for handling a non-existent index. Must be one of the following:
> ```

Instead of "Directive for..." how about this: "Controls the behavior if the specified index does not exist."
___
*[`tests/utils.py` line 533 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OG1ZrsVDa7L3O0xwt9r:-OG1ZrsVDa7L3O0xwt9s:b-76di5q) ([raw file](https://github.com/pixeltable/pixeltable/blob/8c2d7d49f5b650ef11c9cf1574dc5afd4ce74051/tests/utils.py#L533)):*
> ```Python
>     assert diff.getbbox() is None, context
> 
> def assert_raises_error(expected_message, func, *args, **kwargs):
> ```

This is a rather awkward pattern; it makes the testing code hard to read and defeats the type checker (and we do want to get to a place where the testing code is type checked and can serve to validate type correctness of our usage patterns). And it doesn't generalize to situations where the code block is something other than a function call, such as an arithmetic expression.

I understand that you're trying to reduce code sprawl in the very common pattern of examining an error message string. Another way to do that would be with a custom context manager:

```python
with raises_pxt_error('expecting to see this string'):
    func(...)
```

Or you can do this using pytest's built-in `match` feature:
```python
with pytest.raises(excs.Error, match=r'expecting to see this string'):
    func(...)
```
but the latter has its own issues (it uses a regex, which is powerful but can also be harder to read if the exception message has a lot of special characters that need to be escaped).

I'd argue that trying to make things even more concise by eliminating the context manager entirely (to go from 2 lines of code to 1) isn't worth the cost in readability and type safety.


<!-- Sent from Reviewable.io -->

2025-01-09 22:51 UTC, anushas reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/423)* status: 0 of 9 files reviewed, 9 unresolved discussions (waiting on @aaron-siegel and @mkornacker)

___
*[`pixeltable/globals.py` line 448 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OG1MIwwA8VVnh9G_Yh6:-OGB_XXk3Bz-3TkRxzUa:bgs156w) ([raw file](https://github.com/pixeltable/pixeltable/blob/8c2d7d49f5b650ef11c9cf1574dc5afd4ce74051/pixeltable/globals.py#L448)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Be sure to run `mkdocs build` locally and look at the generated output to make sure it's formatted intelligibly. mkdocstrings can sometimes be fussy about markdown spacing and formatting.
</blockquote></details>

Done. Corrected it for the create APIs as well. Also removed mentions of default. 
___
*[`pixeltable/globals.py` line 453 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OG1MW455EJcCUr2ttVl:-OGBbnNH2zieUGzQMPVu:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/8c2d7d49f5b650ef11c9cf1574dc5afd4ce74051/pixeltable/globals.py#L453)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

this is hard for me to parse; maybe would be clearer as a bulleted list?
</blockquote></details>

Done.
___
*[`pixeltable/globals.py` line 454 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OG1MrKW1g8GmgzSCvr3:-OGBaUrC4uKOnwEQIQPr:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/8c2d7d49f5b650ef11c9cf1574dc5afd4ce74051/pixeltable/globals.py#L454)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

`'False'` should not be in strings
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 705 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OG1Ym_XEXY5Wm9gcOxK:-OGBxyfC2732QEPJ0vMn:bncypd6) ([raw file](https://github.com/pixeltable/pixeltable/blob/8c2d7d49f5b650ef11c9cf1574dc5afd4ce74051/pixeltable/catalog/table.py#L705)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

The semantics of these `__check` methods are pretty confusing now (they're trying to do two things at once). I'd suggest just keeping them as they were before, and performing the `if_not_exists` check in the calling function(s). There's not much benefit in parameterizing them this way, since they only get called using the `if_not_exists` parameter in one place (unless i'm missing something).
</blockquote></details>

Done. Sorry.
___
*[`pixeltable/catalog/table.py` line 749 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OG1Wstm-5QAa-xio9iW:-OGBc48t3ZzyWGqUqi7m:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/8c2d7d49f5b650ef11c9cf1574dc5afd4ce74051/pixeltable/catalog/table.py#L749)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Better to use `self._tbl_version_path.is_snapshot()`
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 755 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OG1Y17fDeR1rL5s0FzY:-OGBdQJX4bffAlaic-7l:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/8c2d7d49f5b650ef11c9cf1574dc5afd4ce74051/pixeltable/catalog/table.py#L755)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

`_if_not_exists == IfNotExistsParam.IGNORE` is a superfluous condition (it has to be such or the preceding line would have thrown an exception); either remove it or make it an assertion
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 757 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OG1Y8bo4IYL-iaZ3h_u:-OGBdVaI50rgvVKg6TA2:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/8c2d7d49f5b650ef11c9cf1574dc5afd4ce74051/pixeltable/catalog/table.py#L757)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Redundant assertion (we just checked for it)
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 902 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OG1ZMo4DLTsM2HAz2Wd:-OGBe7q2675uqvpXmhMc:b-m5bbeo) ([raw file](https://github.com/pixeltable/pixeltable/blob/8c2d7d49f5b650ef11c9cf1574dc5afd4ce74051/pixeltable/catalog/table.py#L902)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Instead of "Directive for..." how about this: "Controls the behavior if the specified index does not exist."
</blockquote></details>

Do you feel strongly about changing this? If yes, I will need to do it symmetrically for all the APIs that mention "Directive for...."
___
*[`tests/utils.py` line 533 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OG1ZrsVDa7L3O0xwt9r:-OGCDddmEDIdF2mtghUf:blebiys) ([raw file](https://github.com/pixeltable/pixeltable/blob/8c2d7d49f5b650ef11c9cf1574dc5afd4ce74051/tests/utils.py#L533)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This is a rather awkward pattern; it makes the testing code hard to read and defeats the type checker (and we do want to get to a place where the testing code is type checked and can serve to validate type correctness of our usage patterns). And it doesn't generalize to situations where the code block is something other than a function call, such as an arithmetic expression.

I understand that you're trying to reduce code sprawl in the very common pattern of examining an error message string. Another way to do that would be with a custom context manager:

```python
with raises_pxt_error('expecting to see this string'):
    func(...)
```

Or you can do this using pytest's built-in `match` feature:
```python
with pytest.raises(excs.Error, match=r'expecting to see this string'):
    func(...)
```
but the latter has its own issues (it uses a regex, which is powerful but can also be harder to read if the exception message has a lot of special characters that need to be escaped).

I'd argue that trying to make things even more concise by eliminating the context manager entirely (to go from 2 lines of code to 1) isn't worth the cost in readability and type safety.
</blockquote></details>

Done. as discussed.


<!-- Sent from Reviewable.io -->

2025-01-10 00:58 UTC, aaron-siegel requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/423)* status: 0 of 9 files reviewed, 11 unresolved discussions (waiting on @anushas and @mkornacker)

___
*[`pixeltable/catalog/table.py` line 902 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OG1ZMo4DLTsM2HAz2Wd:-OGCgwvv1KSBC7gz_-aw:b26rtmy) ([raw file](https://github.com/pixeltable/pixeltable/blob/8c2d7d49f5b650ef11c9cf1574dc5afd4ce74051/pixeltable/catalog/table.py#L902)):*
<details><summary><i>Previously, anushas wrote…</i></summary><blockquote>

Do you feel strongly about changing this? If yes, I will need to do it symmetrically for all the APIs that mention "Directive for...."
</blockquote></details>

"directive" sounded a little unusual to me but i don't feel super strongly about it.
___
*[`pixeltable/globals.py` line 613 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OGCfV4eBRhJPm6jFMAJ:-OGCfV4eBRhJPm6jFMAK:b-ajjg5a) ([raw file](https://github.com/pixeltable/pixeltable/blob/f006f0bb559cb222cf70482ce20a3f33f6917c86/pixeltable/globals.py#L613)):*
> ```Python
> 
>     Raises:
>         Error: If the path is invalid, or does not exist and `if_not_exists='error'`,
> ```

Make this a bulleted list too?
___
*[`tests/test_dirs.py` line 183 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OGChEVo3PbSqzf4Of5T:-OGChEVo3PbSqzf4Of5U:b-tqqj1o) ([raw file](https://github.com/pixeltable/pixeltable/blob/f006f0bb559cb222cf70482ce20a3f33f6917c86/tests/test_dirs.py#L183)):*
> ```Python
>         # bad name
>         expected_err = 'invalid path format'
>         with pytest.raises(excs.Error, match=re.compile(expected_err, re.IGNORECASE)):
> ```

You shouldn't need to use `re.compile`, just use a string comprehension.
```python
with pytest.raises(excs.Error, match=r'invalid path format'):
```

IMO that makes the code a lot more readable. See the section on `match` in the pytest docs: https://docs.pytest.org/en/7.1.x/how-to/assert.html


<!-- Sent from Reviewable.io -->

2025-01-10 09:12 UTC, anushas reviewed
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/423)* status: 0 of 9 files reviewed, 11 unresolved discussions (waiting on @aaron-siegel and @mkornacker)

___
*[`pixeltable/globals.py` line 613 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OGCfV4eBRhJPm6jFMAJ:-OGEHUBxCaK9lu1D3pbL:b-d9qrip) ([raw file](https://github.com/pixeltable/pixeltable/blob/f006f0bb559cb222cf70482ce20a3f33f6917c86/pixeltable/globals.py#L613)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Make this a bulleted list too?
</blockquote></details>

Done. Did it for create apis too.
___
*[`pixeltable/catalog/table.py` line 902 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OG1ZMo4DLTsM2HAz2Wd:-OGEOpg1E1oX6zc0VVp_:b83nsq2) ([raw file](https://github.com/pixeltable/pixeltable/blob/8c2d7d49f5b650ef11c9cf1574dc5afd4ce74051/pixeltable/catalog/table.py#L902)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

"directive" sounded a little unusual to me but i don't feel super strongly about it.
</blockquote></details>

in my head, it still feels like a user directive that controls the behaviour. i am leaving it as is. thanks.
___
*[`tests/test_dirs.py` line 183 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/423#-OGChEVo3PbSqzf4Of5T:-OGEOoTV0dxGSjI7Mrs-:b-yh6uo4) ([raw file](https://github.com/pixeltable/pixeltable/blob/f006f0bb559cb222cf70482ce20a3f33f6917c86/tests/test_dirs.py#L183)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

You shouldn't need to use `re.compile`, just use a string comprehension.
```python
with pytest.raises(excs.Error, match=r'invalid path format'):
```

IMO that makes the code a lot more readable. See the section on `match` in the pytest docs: https://docs.pytest.org/en/7.1.x/how-to/assert.html
</blockquote></details>

I used it primarily for ignoring case. I have changed it back to be case sensitive. It is indeed more readable, thanks.


<!-- Sent from Reviewable.io -->

2025-01-10 17:34 UTC, aaron-siegel approved these changes

2025-01-10 20:41 UTC, merged