Add mintlify [WIP]
pixeltable/pixeltable pull request #424
Opened 2024-12-26 20:05 UTC by jacobweiss2305

2024-12-26 20:05 UTC, aaron-siegel commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pixeltable/pixeltable/424)
<!-- Reviewable:end -->

2025-02-25 23:17 UTC, aaron-siegel requested changes

2025-02-25 23:17 UTC, aaron-siegel commented on docs/mintlify/docs/overview/installation.mdx
> +      <Step title="Create environment">
Mention that any Python version 3.9 or above can be used?

2025-02-25 23:17 UTC, aaron-siegel commented on docs/mintlify/docs/overview/installation.mdx
> +  You can also try Pixeltable directly in Google Colab using our [Pixeltable Basics Tutorial](https://docs.pixeltable.com/docs/pixeltable-basics).
I'd put this at the top.

2025-02-25 23:17 UTC, aaron-siegel commented on docs/mintlify/docs/overview/pixeltable.mdx
> +description: 'Pixeltable is a declarative data infrastructure for building multimodal AI applications, enabling incremental storage, transformation, indexing, and orchestration of data.'
"infrastructure" is a mass noun ("Pixeltable is declarative data infrastructure" or "Pixeltable is a declarative data framework" or some such)

2025-02-25 23:17 UTC, aaron-siegel commented on docs/mintlify/docs/overview/pixeltable.mdx
> +    Define transformations once, they run automatically on new data.
comma splice (use a semicolon instead, or re-word)

2025-02-25 23:17 UTC, aaron-siegel commented on docs/mintlify/docs/overview/installation.mdx
> +    schema_or_df={
Avoid referencing `schema_or_df` directly. It's meant to be used as a positional parameter, and we're going to revert the name to `schema` soon which will break any examples that are using it as a keyword arg (and any user code that is modeled off such examples)

2025-02-25 23:17 UTC, aaron-siegel commented on docs/mintlify/docs/overview/installation.mdx
> +    pxt.init()
Mention that the user needs to restart their Python session first (otherwise this isn't going to help)

2025-02-25 23:17 UTC, aaron-siegel commented on docs/mintlify/docs/overview/installation.mdx
> +    For CUDA/GPU support:
These steps shouldn't be necessary. GPU support should be automatic once torch is installed.

If we're going to provide this section, let's make sure we add links to each step that give details on how to do them, AND let's make sure we've tested the workflow against a real situation that simulates what we're trying to troubleshoot. Otherwise these are at best unhelpful (and at worst lead users down a blind alley)

2025-02-25 23:17 UTC, aaron-siegel commented on docs/mintlify/docs/overview/installation.mdx
> +  <Card title="Quick Start Tutorial" icon="play" href="/docs/tutorials/quickstart">
When I clicked on this, it took me back to the Introduction page, which confused me.

2025-02-25 23:17 UTC, aaron-siegel commented on docs/mintlify/docs/overview/installation.mdx
> +  <Card title="Example Gallery" icon="images" href="/docs/examples/gallery">
Same problem here. Broken links?

2025-02-25 23:17 UTC, aaron-siegel commented on docs/mintlify/docs/overview/installation.mdx
> +- 📚 Check our [Documentation](https://docs.pixeltable.com)
Isn't someone (by definition) already checking out our documentation if they're reading this?

2025-02-25 23:17 UTC, aaron-siegel commented on docs/mintlify/docs/overview/installation.mdx
> +<RequestExample>
Why is this here in the "installation" section?

2025-02-25 23:17 UTC, aaron-siegel commented on docs/mintlify/docs/overview/quick-start.mdx
> +## Installation
I just finished reading the "Installation" page, but now there's a separate "Quick Start / Installation" section with different instructions. (These instructions don't say anything about venvs, but they do involve installing torch etc).

Would be clearer to say "first, install Pixeltable" (with an appropriate link to the "real" installation page) and then have as a separate step
```bash
pip install -U torch transformers openai
```

2025-02-25 23:17 UTC, aaron-siegel commented on docs/mintlify/docs/overview/quick-start.mdx
> +    This creates a persistent and verstioned table that holds data.
typo: versioned

2025-02-25 23:17 UTC, aaron-siegel commented on docs/mintlify/docs/overview/quick-start.mdx
> +    from pixeltable.functions import huggingface, openai
it'd be clearer to relocate these imports to the code blocks that actually use them

2025-02-25 23:17 UTC, aaron-siegel commented on docs/mintlify/docs/overview/quick-start.mdx
> +  3. Orchestrate the GPT-4 API call
typo: orchestrated

2025-02-25 23:17 UTC, aaron-siegel commented on docs/mintlify/docs/overview/quick-start.mdx
> +## Key Features
The structure of this is identical to what's on the introduction page, but the content is slightly different - is that intentional?

2025-02-25 23:17 UTC, aaron-siegel commented on docs/mintlify/docs/overview/quick-start.mdx
> +## Custom Functions
Custom UDFs

2025-02-25 23:17 UTC, aaron-siegel commented on docs/mintlify/docs/overview/configuration.mdx
> +- System configuration file (`$PIXELTABLE_HOME/config.toml`)
Give the specific location please. I always find it annoying when documentation refers to an environment variable like `$HOME` as part of a pathname. Better to add "usually `~/.pixeltable/config.toml` on Linux/MacOS or `...` on Windows" (I don't know the windows path)

2025-02-25 23:17 UTC, aaron-siegel commented on docs/mintlify/docs/overview/configuration.mdx
> +  Verbosity for Pixeltable console logging (0: minimum, 1: normal, 2: maximum)
We're going to have a real problem keeping the docs in sync; in a recent PR I changed this to "Verbosity level for Pixeltable console output (`0` = warnings only, `1` = normal, `2` = verbose)" (and also added a new config option). But now I see I'm going to have to update the mintlify docs with any such change as well.

2025-02-25 23:17 UTC, aaron-siegel commented on docs/mintlify/docs/overview/configuration.mdx
> +<CardGroup cols={1}>
Why is the format different here vs. the system settings? Also, there are a whole bunch that are missing.

2025-02-27 18:18 UTC, jacobweiss2305 commented on docs/mintlify/docs/overview/installation.mdx
> +      <Step title="Create environment">
We do mention 3.9 or higher:
![image](https://github.com/user-attachments/assets/3a87faf4-5867-448d-be0e-988d9164cd29)

2025-02-27 18:22 UTC, jacobweiss2305 commented on docs/mintlify/docs/overview/installation.mdx
> +  You can also try Pixeltable directly in Google Colab using our [Pixeltable Basics Tutorial](https://docs.pixeltable.com/docs/pixeltable-basics).
Done

2025-02-27 18:26 UTC, jacobweiss2305 commented on docs/mintlify/docs/overview/pixeltable.mdx
> +description: 'Pixeltable is a declarative data infrastructure for building multimodal AI applications, enabling incremental storage, transformation, indexing, and orchestration of data.'
Done, replaced with `database`

2025-02-27 18:32 UTC, jacobweiss2305 commented on docs/mintlify/docs/overview/pixeltable.mdx
> +    Define transformations once, they run automatically on new data.
done

2025-02-27 18:37 UTC, jacobweiss2305 commented on docs/mintlify/docs/overview/installation.mdx
> +    schema_or_df={
done

2025-02-27 18:39 UTC, jacobweiss2305 commented on docs/mintlify/docs/overview/installation.mdx
> +    pxt.init()
Done

2025-02-27 18:41 UTC, jacobweiss2305 commented on docs/mintlify/docs/overview/installation.mdx
> +    For CUDA/GPU support:
done

2025-02-27 18:43 UTC, jacobweiss2305 commented on docs/mintlify/docs/overview/installation.mdx
> +  <Card title="Quick Start Tutorial" icon="play" href="/docs/tutorials/quickstart">
Fixed

2025-02-27 18:44 UTC, jacobweiss2305 commented on docs/mintlify/docs/overview/installation.mdx
> +  <Card title="Example Gallery" icon="images" href="/docs/examples/gallery">
fixed

2025-02-27 18:45 UTC, jacobweiss2305 commented on docs/mintlify/docs/overview/installation.mdx
> +- 📚 Check our [Documentation](https://docs.pixeltable.com)
Correct. I removed.

2025-02-27 18:46 UTC, jacobweiss2305 commented on docs/mintlify/docs/overview/installation.mdx
> +<RequestExample>
The reason its in the installation section is IF the user is having issues installing they can quickly reference a support link. 

If they are going through installation, I am assuming they are relatively new. They aren't going to want to find or search or docs for getting help.

2025-02-27 18:49 UTC, jacobweiss2305 commented on docs/mintlify/docs/overview/quick-start.mdx
> +## Installation
Okay i mentioned a link to our installation section as a pre-cursor.

2025-02-27 18:50 UTC, jacobweiss2305 commented on docs/mintlify/docs/overview/quick-start.mdx
> +    This creates a persistent and verstioned table that holds data.
done

2025-02-27 18:53 UTC, jacobweiss2305 commented on docs/mintlify/docs/overview/quick-start.mdx
> +    from pixeltable.functions import huggingface, openai
done

2025-02-27 18:54 UTC, jacobweiss2305 commented on docs/mintlify/docs/overview/quick-start.mdx
> +  3. Orchestrate the GPT-4 API call
done

2025-02-27 18:56 UTC, jacobweiss2305 commented on docs/mintlify/docs/overview/quick-start.mdx
> +## Key Features
Yes, after the user builds the app. We want to add a quick feedback loop on what they built and how they were able to do it with our features. Should it match verbatim? IDK. I can change if you want

2025-02-27 18:58 UTC, jacobweiss2305 commented on docs/mintlify/docs/overview/quick-start.mdx
> +## Custom Functions
The acroynm is not know to users at first. I recommend we do Custom Functions (UDFs).

2025-02-27 19:01 UTC, jacobweiss2305 commented on docs/mintlify/docs/overview/configuration.mdx
> +- System configuration file (`$PIXELTABLE_HOME/config.toml`)
done

2025-02-27 19:02 UTC, jacobweiss2305 commented on docs/mintlify/docs/overview/configuration.mdx
> +  Verbosity for Pixeltable console logging (0: minimum, 1: normal, 2: maximum)
Yes we will need to discuss our workflow. I went ahead and updated to the new Verbosity level.

2025-02-27 19:19 UTC, jacobweiss2305 commented on docs/mintlify/docs/overview/configuration.mdx
> +<CardGroup cols={1}>
Okay filled in missing keys and standardized the format to match the other sections

2025-03-03 22:24 UTC, pierrebrunelle approved these changes

2025-03-04 02:00 UTC, merged