Update dependencies for python 3.12 compatibility
pixeltable/pixeltable pull request #97
Opened 2024-03-20 21:01 UTC by aaron-siegel

Here's a PR with updated dependencies that works with python 3.12.

Several key dependencies had to be updated. A side effect is that it closes the door on supporting 3.8.

We can discuss whether it makes sense to merge to master (how important is it to support 3.12 at this time?)

2024-03-20 21:10 UTC, orm011 reviewed
Maybe we should split the task of removing 3.9 support with providing 3.12. eg. Pytorch is currently only providing "experimental" support for 3.12. 
One larger issue I ran into just a few minutes ago is how narrow the allowed versions for dependencies are. This causes false-positive conflicts when installing other packages, like unstructured.

I wonder if trying to support 3.12 right now will make it harder to get the  false-positive conflict problem in order soon, without providing much upside:  (possibly needing to specify different ranges depending on the python version  as done for numpy  in your diff below).  

It seems to me false-positive version conflict is a blocker for open source release, while 3.12 is not

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/97#-:-NtSfgAwEZgFsRGhUmGW:byn6t4e)* status: 0 of 4 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-03-20 21:29 UTC, orm011 requested changes
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/97)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @aaron-siegel)

___
*[`poetry.lock` line 773 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/97#-NtSkW6rBr9pCZAWhpxr:-NtSkW6rBr9pCZAWhpxs:b2kx1we) ([raw file](https://github.com/pixeltable/pixeltable/blob/04294fd530865942722b752e480c8aeb73c20671/poetry.lock#L773)):*
> ```TOML
>     {version = ">=1.16,<2.0", markers = "python_version <= \"3.11\""},
>     {version = ">=1.26.0rc1,<2.0", markers = "python_version >= \"3.12\""},
> ]
> ```

question: 
if we simply provided ">= 1.16,<2.0" as numpy versions, would dependency resolution at install time (on the client side) use the appropriate numpy version depending on its python version ? If so, we wouldn't need to be this explicit, and we could focus on widening the version as much as possible.


<!-- Sent from Reviewable.io -->

2024-03-29 16:03 UTC, orm011 reviewed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/97)* status: all files reviewed, 1 unresolved discussion (waiting on @aaron-siegel)



<!-- Sent from Reviewable.io -->

2024-04-16 16:50 UTC, orm011 requested changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/97)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @aaron-siegel and @mkornacker)

___
*[`poetry.lock` line 3410 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/97#-Nvbo1y5-ULmQqu1nMhj:-Nvbo1y6Dnk5ANkk4rEM:b3ufssi) ([raw file](https://github.com/pixeltable/pixeltable/blob/3aa3c7f3959d2728de5b190a07bae787fc3493cf/poetry.lock#L3410)):*
> ```TOML
> [package.dependencies]
> numpy = [
>     {version = ">=1.22.4,<2", markers = "python_version < \"3.11\""},
> ```

How come we need this case-by-case breakdown for numpy but not for other libraries?  Wouldn't this be something the dependency resolution takes care of?


<!-- Sent from Reviewable.io -->

2024-04-16 16:52 UTC, mkornacker approved these changes

2024-04-16 16:52 UTC, mkornacker commented on pyproject.toml
> +pandas = "^2.2.0"
Does 2.0.0 work here or do we really need 2.2.0? No need to be overly restrictive.

Same for pillow (10.0 vs 10.2)

2024-04-16 16:52 UTC, orm011 approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/97)* status: all files reviewed, 3 unresolved discussions (waiting on @aaron-siegel)



<!-- Sent from Reviewable.io -->

2024-04-16 17:22 UTC, merged